### ISSUE TITLE
[Enhancement/Issue] Special Taxation for Second Hand articles

### ISSUE THREAD

**Issue by benchonaut** [opensourcepos/opensourcepos#1375]
@jekkos @SteveIreland 

Hi, i don't know about other countries in detail , 
but in germany the formula for taxation of second hand things is not 
VALUE*1.19 , 
instead you subtract the price you gave to the previous owner 
e.g.  (19% tax)
Somebody brings a used shirt to your shop,
you pay him EUR 3
you sell it for EUR 10 ( would be 8,4x EUR without taxes for retail things)
tax calculation in this case is (10-3)/1.19 ( because your "retail value" for used things is 5,88 EUR).

How to implement that , because the algorithm differs from any "standard" calculation ?

Regards

**Comment by jekkos** [comment]
So but this only applies to second hand items? You mean that in other cases you have tax eclusive pricing?

Currently the  POS only allow you to set tax included for the whole setup. Not sure if this is something foreseen in the taxes story of @SteveIreland?

**Comment by daN4cat** [comment]
Tax categories/slabs/tiers should be entities that define taxation rules at item level or customer level and attachable to one of the two core objects.

**Comment by jekkos** [comment]
Ok was just looking into the upgrade SQL for tax categories. There are no foreign key constraints between the tables which I rather have fixed.

Also how is one supposed to manage tax categories? There seems to be no way of editing what is in the db. After clearing out this table things seem a bit broken. It might be more efficient to replace the tax categories with part of the attributes story, eg define an attribute type that links an item to a tax category.

**Comment by SteveIreland** [comment]
I was wondering if anyone would notice the lack of tax category management besides myself.  I figured I could add that before anyone noticed or as soon as someone needs to add something different. I predefined the traditional sales tax item categories of Service typically 0% tax rate, Standard tax rate, and Alcohol (typically a higher tax rate).

When you do the "attributes story", if we develop software around a particular attribute (such as tax category) then it seems to me that it would need to be a "system defined" attribute that would need to have some additional constraints placed on it so that the programming that is dependent on it existing won't  fail.   I've found soft attributes that are user defined to be unreliable for much more than user defined reporting.

**Comment by SteveIreland** [comment]
For this particular request, it seems to be a unique VAT tax calculation that is triggered based on the sale of a particular item type ... maybe?  A new item type of  "Resale Item" that computes the tax amount for the sale of that item based on the difference between the extended sale price and the extended cost (instead of simply the extended price?  I'm not a vat tax person, but that seems to be the case here.  I would imagine that the discount would need to be taken into account for the final extended price.

If this is the case then I could add this pretty easily and would be happy to do so.

The temptation would be to make it a new item tax category, but since this request doesn't simply define a new tax rate (from what's been provided thus far), but a different tax algorithm then the more stable approach is to add a new item type.  If there is also a different tax rate then a new item tax category is going to be required, but I would do both.   Since the Item Tax Category is simply a name that can change to another language then it cannot be used to control programming logic.

**Comment by daN4cat** [comment]
BTW @jekkos attributes are descriptions of your data whilst tax categories have rules affecting the end result. I wouldn't mix up the two although are both aggregate to items, but tax category can be even aggregated to customers.

@SteveIreland the fact that tax categories cannot be edited is something I spotted and reported already. Those should be editable. However I'm getting confused between those categories and the other view of the tax associated to customers. Why different views?

**Comment by jekkos** [comment]
@daN4cat Well the fact that you cannot edit them could be solved easily by letting a user attach a set of tax rules to a category. For me that's where the two worlds  come together, on one hand you have your item description together with categorization, to which you can optionally then attach a set of tax rules.

**Comment by benchonaut** [comment]
(The whole Setup is running with "VAT included" to be legit, since the "sale price" was imported from a previous solution) 

(And yes, the Problem of how you detect the item state [new|used] is a good question , in this case a custom field is used for the state of the article (5 new , 4 mint , 3 very good and so on) .. 
so a custom rule editor ( e.g. IF(CUSTOM_X==5) THEN TAXFORMULA=PRICE*0.19 ... ELSE TAXFORMULA= (PRICE-COST)*0.19 )

**Comment by SteveIreland** [comment]
hmmm .... complication .... I assumed that a used item would have a different item code and therefore I could assign a new item type to it that would trigger the new resale tax calculation.

Adding a new product state value field seems to move it into the custom development domain - but that's a decision for the deciders.

**Comment by SteveIreland** [comment]
Regarding Tax Categories, for now I'll add support for changing the values of item tax categories.  It will just be another Store Configuration option for taxes similar to dinner tables.  There should be three "starting" categories that can be renamed and then additional tax categories can be added.

**Comment by daN4cat** [comment]
@SteveIreland since you are adding something to Store Config,  could you please create a tax tab and move all the tax configurations to it? Now it's time to have a dedicated tab.

**Comment by SteveIreland** [comment]
Okay

**Comment by jekkos** [comment]
Closing this one, thanks to @SteveIreland we have plenty of options to define tax rules for items now.
