### ISSUE TITLE
Upgrade to HTML5

### ISSUE THREAD

**Issue by bill-goldberg** [opensourcepos/opensourcepos#1497]
Please guide me for upgrading this application to html5.

**Comment by daN4cat** [comment]
And the rationale for that is?

**Comment by bill-goldberg** [comment]
Just want some html5 tags to add in this application

**Comment by SteveIreland** [comment]
This seems like an easy low risk change .... right up my alley.  😉

**Comment by SteveIreland** [comment]
I noticed that someone created a $_doctypes variable.  I'm assuming that this either was originally in support of a configurable document type or was something that someone started and never followed through on,  Is there any reason that we would want the document type configurable instead of being locked in to html5?  I personally think html5 is perfectly fine and the correct direction forward for OSPOS.

**Comment by daN4cat** [comment]
@SteveIreland to be honest I have no idea. Where is that $_doctypes?

**Comment by daN4cat** [comment]
OK, found it, it's in application/config/doctypes.php. It's a CodeIgniter thingy.

**Comment by daN4cat** [comment]
@SteveIreland you probably need to check what needs to change in our views.
I didn't look in great detail myself, but I assume you first need to change the DOCTYPE in login.php and partial/header and then UTF-8 and etc.

However the issues will pop up from the deprecated tags. And I'm sure they are used, so it's a tedious job to validate all the views.

See details about HTML 5 changes: https://www.w3schools.com/html/html5_intro.asp
