### ISSUE TITLE
Odd issue related to Migration

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#1576]
### Issue / Question / Bug

Just installed OSPOS  3.2.0 - 4f5ad57.

It looked like the migration attempted to "kick off" and failed with an invalid index named tax_decimal (which seems like a really odd message which didn't make any sense to me) so it dumped a lot of errors to the screen.

I resolved the issue by immediately deleting /application/migrations/20170502221506_sales_tax_data.php

Since I don't need to run the migration this resolved the issue so that I could continue.  Unfortunately I was in a "go live" situation so I couldn't take the time to explore the issue further.  This did not happen when I went live with a 3.2.0 pre-release last weekend, so it seems that something must have changed in the area of the migrations.

I just want report the issue here so I don't forget to explore this further.

But I should first ask ... was the migration changed to automatically kick off?

**Comment by daN4cat** [comment]
No, what I changed was to hide the button if there is no need for a migration. Outside that, there is no automatic kick off, you need to click the button.

I'm constantly doing it because I'm going through some upgrade drills of a current live database so I know you need to explicitly push that button to get things finalised.

**Comment by daN4cat** [comment]
I never bumped into the error you described.

**Comment by SteveIreland** [comment]
I will try to recreate the issue next weekend

**Comment by daN4cat** [comment]
@SteveIreland I bumped into this error once, over the week-end. I retook our old database done all the automated SQL scripting update, started the latest app code and the migration was automatically kick started dumping a lot of errors on the page. However at the end of that process I checked the error_log to find that the migration took place automatically and all was fine after that step.

That is strange, because what I added is just a check whether a migration is required, but it might be that the CI function I used is not correct and kick starts an upgrade.

I'll check again over the week end and read better CI documentation.

**Comment by daN4cat** [comment]
The "funny" thing here is that invoking latest() to check if the application is on the latest migration triggers the migration execution. Same with current(). So there is no way to just check if a migration is required.
I found this story a bit weird. Maybe the migration could be triggered automatically on first login if required or simply moved to Store Config instead of having a big icon.

**Comment by jekkos** [comment]
Hmm I'm actually fine with having it as a module that makes it clear directly that migration needs to be done, instead of burying it next to the other thousands of configuration tabs we already have..

but then of course it should only show if it's applicable. Think the only way to do that currently is by writing a db schema version to the db and compare it with our code version. If both are the same then we can show the module, otherwise we hide it. Might also be nice to show both strings somewhere in this module which will make troubleshooting easier

**Comment by SteveIreland** [comment]
I introduced the ability to hide a module (introduced with the office menu feature) by simply setting the sort number to zero.  So that's a simple way of hiding it regardless of whether it is authorized to anyone.

**Comment by daN4cat** [comment]
@jekkos @SteveIreland @objecttothis @odiea 

OK, the migration story changed a bit:

* Upgrade happens automatically to the latest and if required at login time, so the first login will be longer but everything is setup to work properly after that. This should reduce a number of issues related to "how to upgrade"
* Upgrade from 3.0.2 to 3.1.1, new tax and from 3.1.1 to 3.2.0 are now done using the Migration tool and automatically. SQL scripts moved from database to migrate/sqlscripts and are read from the two newly created migrate classes and applied. Easy trick that does the job well.

What to do going forward?

* Ideally we should split the upgrade to 3.2.0 to a number of smaller upgrades so we can incrementally add new changes and leverage the migration to do everything automatically at each first login.
Doing this we can work on separate incremental features without having to merge in one big sql script all the version upgrades. If somebody fancy working on this I'm fine, otherwise I will look into this one of the next times. Please bear in mind that if you add something changing the SQL script in migrate/sqlscript will not be enough anymore because the date of the migration script doesn't change. The only way to trigger a new upgrade is to add a new migration script or rename the current one to a newer time and date.

**Comment by daN4cat** [comment]
Forgot, old Migrate controller and view are gone. It's all done automatically at login time.

**Comment by objecttothis** [comment]
This is great @daN4cat kudos. How are we keeping track of the current installed version and the new version?  I ask because the version number is listed in the config.php, but this often gets overwritten when uploading upgrade files.  Also, does the automated script account for skipped versions?  for example if I upgrade to 3.2.0 but then I miss two releases (3.2.1 and 3.2.2) and then upgrade to 3.3.3 will the automated database upgrade script know to apply both 3.2.1 and 3.2.2 db upgrade scripts?  Also, how are db errors handled.  Is it just reported in the log?

**Comment by daN4cat** [comment]
It executes in series according to the oldest date to the newest from the upgrading starting point. So if you have done all the manual upgrades from 2.4 to 3.0 then the application will do 3.0.2 to 3.1.1, then tax migration and then 3.1.1 to 3.2.0.
Going forward there will be a stored starting point and it should be simpler.

**Comment by daN4cat** [comment]
Hope this explained a bit the story but I guess we can refine it a bit more.

**Comment by objecttothis** [comment]
the store's starting point I'm assuming is in the database? I may be wrong but the three common errors with database upgrades that we see are 1. not running all the upgrade scripts or running them out of order. 2. errors caused by key, value pairs already existing 3. failed foreign key constraints. @daN4cat's changes eliminate 1. 2 can be remedied by adding the IGNORE keyword to any SQL that adds a key, value pair so that it will just skip that one if the key, value exists. 3. usually occurs with upgrades from older upgrades.
I think sticking things in try catch clauses and reporting failure with a general message to check the log could be a good way to handle errors. also making it clear whether the upgrade continued after, or reverted all changes. I know that partial script runs cause errors on subsequent runs.

**Comment by daN4cat** [comment]
It's in the database, it's migration table and contains just one entry, the last date and time of the last migration class file that was executed.

Yes we can change the SQL scripts adding ignore. At the moment and error is reported and everything logged in error_log. I believe we can improve that logging story to. Yesterday I wanted to change that as fix two other issues.
