### ISSUE TITLE
Error on running upgrade script

### ISSUE THREAD

**Issue by esbyrt** [opensourcepos/opensourcepos#1614]
### IMPORTANT IMPORTANT IMPORTANT

1. Chose what you want to report between the sections "New Feature / Enhancement" and "Issue / Question / Bug".
2. Remove just the one of the two sections you don't need 
3. Remove this section as it's just a guideline
4. Fill in all the details as requested by the section you chose

If you remove the complete template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhancement

*For New Features or Enhancements please clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for older versions.*

### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:
Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

[x] I'm reporting an issue of an unmodified OSPOS installation
[x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
[x] I read the README, WHATS_NEW and UPGRADE
[x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
[x] I read the wiki
[x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
 I'm aware the latest master could be a development version and therefore not stable
 I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report
Installation information

OSPOS version is: 3.1.1
OSPOS git commit hash is:
PHP version is: (e.g. 5.5, 5.6, 7.0, 7.1) 5.5
MySQL or MariaDB version is: (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2) 10.0.32
OS and version is: (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10) Windows 10
WebServer is: (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13) Apache 2.4.27
(If applicable) Installation package for the LAMP/LEMP stack is: (e.g. WAMP, XAMPP)

### Expected behaviour
Script completes without error

### Actual behaviour
I got the following error when I ran the upgrade script for 3.0.2 to 3.1.1

Error
SQL query:
INSERT INTO `ospos_app_config` (`key`, `value`) VALUES
('barcode_formats', '[]'),
('receiving_calculate_average_price', '0')
MySQL said: Documentation
#1062 - Duplicate entry 'receiving_calculate_average_price' for key 'PRIMARY'

### Steps to reproduce the issue
At a quick run through everything seems to functioning ok. Should I be concerned about this error?
Thanks

**Comment by objecttothis** [comment]
You are getting the error because your database already includes those two entries.  No, you do not need to worry about this error.

@daN4cat @jekkos I believe this may be happeneing because those two keys were introduced sometime before 3.0.2.  I think we can avoid further people getting the error by removing those additions from 3.0.2_to_3.1.1.sql and placing them in the upgrade script where they were introduced.  I think barcode formats probably belongs in 2.3.1_to_2.3.2 (at least that's where most of the other barcode additions are.  I have no idea on where receiving_calculate_average_price needs to go.

**Comment by daN4cat** [comment]
Barcode formats is 3.1.0, it related to create Barcode out of weights for cases like vegetables, meat and you then pay at cashier till.

The receiving is the issue and don't know when that was introduced but we can safely remove. Default mode if nothing exists in the database is = 0. Next time you save a value it creates the key. So that was not really required anyway.

**Comment by esbyrt** [comment]
Thanks for looking at the error! Good to know all is fine. I will carry on then.

**Comment by daN4cat** [comment]
In master
