### ISSUE TITLE
price of the item with tax included ?

### ISSUE THREAD

**Issue by guillermohaad** [opensourcepos/opensourcepos#1628]
Hi friends,

I have a question: 
how could you check the price of the item with tax included to the customer?  should we include a column "with tax" at the end? 
![image](https://user-images.githubusercontent.com/12921805/30653913-07bdf6c0-9df2-11e7-98d6-c3daa873174e.png)

![image](https://user-images.githubusercontent.com/12921805/30654240-f8ec0b18-9df2-11e7-9744-7c9bf26d001a.png)

**Comment by jekkos** [comment]
If you want to enable tax inclusive pricing you have prices all tax inclusive from the start. Currently there's no extra column in the other case to show how much the price is after adding up taxes, so to me that's a feature request.

**Comment by SteveIreland** [comment]
If we are talking about a sales tax based system then it seems to me to be technically incorrect to include a tax on this screen since the tax would be based on the location of the customer the item is  being sold to - unless you're only going to consider the origin tax rate (the rate assigned to walk-in customers).  If I understand this request correctly then maybe it should be optional - or a custom report provided via Reportico.  (nudge-nudge-wink-wink)

**Comment by odiea** [comment]
Shouldn't his retail price be the price with tax included. So he needs to adjust his Retail price to include the tax. Unless he is expecting the program to do that for him instead of a calculator.

**Comment by odiea** [comment]
Then at the Register he can show his Customer what his Retail price is without tax.
![2017-09-20 19_43_36-wedidit _ powered by ospos 3 1 0](https://user-images.githubusercontent.com/10962177/30675148-20a5f3d2-9e3c-11e7-943b-8981896949a4.png)

**Comment by guillermohaad** [comment]
@odiea  totally agree, I apologize for the question, which does not make sense.
Thank you @SteveIreland @jekkos 
Close

**Comment by odiea** [comment]
@guillermohaad No apologies necessary. There is a learning curve to use this program so issues or suggestions are helpful.
