### ISSUE TITLE
Unchecked Office Icon in Store Config

### ISSUE THREAD

**Issue by bill-goldberg** [opensourcepos/opensourcepos#1643]
i was just checking the store config options and i unchecked the option "show office icon" but now unable to revert it back as there is no way to access store config... please help me out this...

**Comment by SteveIreland** [comment]
In the browser URL replace "home" with "office" and press enter

**Comment by SteveIreland** [comment]
Example: 
![image](https://user-images.githubusercontent.com/23066623/30861417-a63eaa2e-a298-11e7-888f-e00df2bc8653.png)

The intent of that checkbox is to require accessing the office menu bar from a URL instead of from the home menu bar.  This was to make it behave somewhat like a third party package.  It would be perfect except that you still need to log in via the home page first.  I have a bookmark for the office page (just in case I accidentally click on the check box to not show the office icon.

**Comment by bill-goldberg** [comment]
Thank you very much.. @SteveIreland
