### ISSUE TITLE
Branch was deleted

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#1682]
Hi everyone.  Not sure the reasoning but it appears that the htaccess-combine-modrewrite branch I created off the master was deleted by someone.  Perhaps it was an accident, but if there is a reason for it please let me know.

**Comment by SteveIreland** [comment]
I hear nothing .... I see nothing ... I know nothing.

**Comment by jekkos** [comment]
Didn't delete it either. Can you push it back again from your local machine?

**Comment by objecttothis** [comment]
Probably.  Since I punted the changed until later I will just leave it as is and re-add it when the time comes.

**Comment by daN4cat** [comment]
Apologies for the belated reply but I started a new job yesterday and so my attention is somewhere else.

I did delete two branches but those after I merged the Try&Catch and the Office icon shift to master, no other code was there because I took everything.
I don't remember other branches outside those two.

**Comment by objecttothis** [comment]
congrats on the new job @daN4cat
