### ISSUE TITLE
Change Tax Rate from % to price value

### ISSUE THREAD

**Issue by kyawsuthway98** [opensourcepos/opensourcepos#1710]
How can I change Tax Rate from % to price value help please

**Comment by SteveIreland** [comment]
What country is this and in what scenario is a tax a fixed amount instead of a percent of sale?  Is it based on item category?

A fixed amount would normally be handled as non-stock item with a description that represents the fee that is being charged.

"Tax Rate" by definition is a percent and there is too much code behind that to try to morph it into something else.

**Comment by kyawsuthway98** [comment]
Well I Just want to add service change as 500 instead of % and I don’t want to add it manually so I want to fix it in tax area

**Comment by daN4cat** [comment]
So it's a service charge not a tax.

**Comment by kyawsuthway98** [comment]
Is there any way to change tax 2 from % to price value

**Comment by daN4cat** [comment]
It's easier to add a service charge feature than fiddle with taxes. Follow that approach and implement it.
If you make it positive and negative could become a fixed discount too.
Happy coding...

**Comment by kyawsuthway98** [comment]
Ok Then, I will try adding a service charge feature. Please help me to find out where can I learn about that feature.

**Comment by daN4cat** [comment]
Probably what you can do is start the sale register list of items with a preloaded item that is a service charge one. That could be even easier. You need to check Controllers/Sales and also library sale_lib.
