### ISSUE TITLE
/ospos/public/  shows 500 internal error

### ISSUE THREAD

**Issue by xpertHands** [opensourcepos/opensourcepos#1745]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is:opensourcepos-opensourcepos-7751379
- OSPOS git commit hash is: 
- PHP version is:      5.6.31
- MySQL or MariaDB version is:      mysql  Ver 15.1, Distrib 10.1.25-MariaDB
- OS and version is:     Windows 7
- WebServer is:      Apache/2.4.26 (Win32)
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:      (e.g. WAMP, XAMPP)

Expected behaviour

To a login screen, so that I can continue installation

Actual behaviour

Internal error 500
and tail error.log doesn't log or tell what went wrong

Steps to reproduce the issue

just go to ip_address/ospos/public/

Hi everyone, It seems I've bumped across something common that ospos beginner bumped into. I have read some of closed issues and faq. and they all suggest to edit .htaccess file of public/ to rewrite accordingly ( on subdir, instead of web root )

I have edited application/config/database.php with necessary information too
( in fact whether I have or have not, hitting ip_address/public will just spit 500 error for no reason )

I did that, but none seems to effect. hitting ip_address/ospos/public will just give me 500 internal error. Strangely apache2 error log doesn't give anything useful and I have been reading some of past issues but could not get past this

*Note : I have other applications running on same host, same apache2 but no problems for them even I encounter 500 on this specific ospos installation

Many thanks,

**Comment by daN4cat** [comment]
Tick the checkboxes....

**Comment by mckaygerhard** [comment]
@xpertHands that @daN4cat means its go to firts entry in this issue, here in right corner of the issue title below here a little pen, click to EDIT the issue and property fill the entire issue template, by fill with "x" inside the "[" and "]", taking in consideration that the issue was not closed and are waiting for that..

this issue are related to #1716 the default instalation assumed ospos hijacked all the root webserver..

the 500 error are due you do not set property "very bad hardcoded" rewrite rules in the htaccess files, 

if you set corrected rewrite rules the 500 error will gone. but still its and issue fir ospos...

**Comment by daN4cat** [comment]
Hijack is your interpretation and quite misleading statement. Also you are not forced to install in the root, that's another misleading statement. You can freely install it in . subdir and just adjust .htaccess.

Therefore please refrain from shooting out confusing statements just because it's not like you want.

**Comment by daN4cat** [comment]
By the way, I see not adjustement to the original issue text with no checkboxes being ticked.
If no progress on that matter I will close this issue over the weekend.

**Comment by mckaygerhard** [comment]
as you said, its my interpretation i'm the user right? i will use it! i'm the need of .. so it's my interpretation, request etc,
