### ISSUE TITLE
Evaluation: demo database and terminal

### ISSUE THREAD

**Issue by klodoma** [opensourcepos/opensourcepos#1750]
This is not an issue, it's just a question.

### Background information
Just took the latest version for evaluation

### Issue / Bug  / Question / New Feature
Hi, 

I try to evaluate the opensourcepos capabilities. 
Currently I have 2 questions:

- do you have a "demo" database, with some pre-filled data?
- does it have a sales terminal?

Thanks.

**Comment by SteveIreland** [comment]
There isn't a demo database.  Probably because no one here is trying to convince anyone to use it .... nearly all of us use it in our own businesses or a friends business and aren't motivated to do much more than maintain a quality product.  In addition, the various configurations would require creating numerous "demo databases".  Something that's not really practical.

I think the answer to the 2nd question is "yes", but then the real answer depends on what your definition of "sales terminal" is and not my definition.

**Comment by daN4cat** [comment]
1. no demo, but somebody here could have some playground website to share
2. it's a web based solution, so your sales terminal is a web browser showing a sales register

**Comment by klodoma** [comment]
Thx for the quick answers. 

Terminal or sales register, yes this is what I was looking for. 
Where can I access that? I can't find it. 

![screenshot_16](https://user-images.githubusercontent.com/944350/34081028-8d4f5672-e347-11e7-92ab-71ee506ac805.png)
![screenshot_17](https://user-images.githubusercontent.com/944350/34081029-8d78de84-e347-11e7-826e-c34eadf85296.png)

**Comment by daN4cat** [comment]
From the top menu, click the icon with the shopping basket. That's the Sales register.

**Comment by daN4cat** [comment]
The window you opened is the permission to grant to users. Sales enables just Sales register to a user.

**Comment by klodoma** [comment]
Got it! THANK YOU!
