### ISSUE TITLE
PHP Error log not available.

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#1770]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is:3.2.0
- OSPOS git commit hash is: 
- PHP version is:      (e.g. 5.5, 5.6, 7.0, 7.1) 7
- MySQL or MariaDB version is:      (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2) MariaDB
- OS and version is:      (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10) Windows 10
- WebServer is:      (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is:      (e.g. WAMP, XAMPP) XAMPP

### Issue /  Question 

If at login time you read "The installation is not correct, check your php.ini file.", please check the error_log in public folder to understand what's wrong. Any PHP extension related issue is due to one of the point below.

I cannot find any error log in the public folder nor can I see any error logs  in the application/logs folder.

**Comment by mckaygerhard** [comment]
a very popular issue.. maybe we need a better documentation or a better behaviour for the hardcoded ospos web root path, why nobody can see that?

**Comment by SteveIreland** [comment]
I think everyone sees it .... but everyone's target platform architecture can be different.

So the best that can be recommended is to refer to your platform's documentation as to how to achieve this or that.

When I develop on my laptop the error log is under my wamp logs folder.  I doubt that knowledge would be helpful to you (unless you are running under the wamp platform which isn't very likely).

When I installed the first time I was a bit confused by the architecture because I had never installed anything before where the library folders weren't dropped into the public root folder.  But the intent of OSPOS (justifiably so for improved security) is that the library folders are dropped a level higher.  In that way I don't have to play any games with the rewrite.

I think the message is probably true for the configuration of the original developer so it should be corrected to be less specific.

**Comment by odiea** [comment]
I assumed that when it states that it is written to the public folder that it would be there. I have a couple Ubuntu servers and can not locate it there either.

**Comment by SteveIreland** [comment]
If it says it should be there then I would assume it would be there too.

I think in most cases the person doing the installation can configure the error log to be dropped anywhere on the system.  On a hosted site I think it is usually in the folder just above the public folder but I'm sure that is dependent on the preference of the hosting services.

A public folder is a terrible place for an error log (for reasons of security).

**Comment by mckaygerhard** [comment]
first of all: what error log are referending the ospos installer? PLEASE BICHT! be clear!

second all the documentation are very out of sync from the hardcoded assumed ¿environment of the ospos code

for most unixes and linuxes if are reference as error web serve log from php/web call, must be in `/var/log/<webserversoftwarename>/error.log` its a standar, event if we use a abberration like XAMP in that case will be in `<pathofxamp>/apache/log/error.log`

the bad hardcoded rewrite rules, the need of and check installer and a good documentation are very need changes for a new year!

**Comment by daN4cat** [comment]
error_log under opensourcepos/public folder. It's a PHP thing, please make sure you have not disabled it at PHP configuration level.

**Comment by SteveIreland** [comment]
Really?  Let me be very clear.  Bad attitude gets zip, zero, nada free support from me.

**Comment by daN4cat** [comment]
@SteveIreland what did I say?

**Comment by daN4cat** [comment]
BTW .htaccess (that useless thing full of stuff...) protects error_log:

```
  # prevent access to PHP error log
  <Files error_log>
    Require all denied
  </Files>
```

and this even prevents somebody to see if it's there:

```
# prevent folder listing
IndexIgnore *
```

haaaa useless stuff all hardcoded

**Comment by mckaygerhard** [comment]
well some of the situations can be due that reasons:

1. maybe the codeigniter or the application directory set the error log to 0, may need to chage to 4?
2. its not necesary to see the error log in web browser, can be opened with a editor from application/log their names are wiht the date format.
3. we need a php script that checks the need extensions, not so dificult (at least againts hardcoded rules)
4. a single html.index file its better rather a apache2 specific file, 

a special note, htaccess are ignored by the php-fpm

**Comment by aamiritsu** [comment]
Hi Guys,
     First of all thank you very much for keeping this product as opensource.
 However, like always, opensource comes with a price. _(Which i am paying everyday since last 3 days, in terms of time)_. 

i am trying hard to install it in XAMPP on my local machine but every time i get same creepy error. i.e. 
_"The installation is not correct, please check your php.ini"_

When i dig deep further, i've realised that it requires some php extension, which apparently i've installed all but not "**mcrypt**". Since my php version is 7.2 and PHP has removed this extension decade ago :(

I expect this is the only reason i am not able to log-in. _(fingers crossed)_.  My concern is if this extension is dead long ago, why are we still using it in this application? 

in last, i would humbly request, if **one of the moderators be kind enough to write step by step guide for development**. So that upcoming guys do not suffer from this nasty error. 

i apologize for my harsh language,if it hurt anybody out there!

Looking forward hearing from you soon!
BR,
Amir

**Comment by mckaygerhard** [comment]
i agree that well made documentation must be made as i posteed before, now  the Mcrypt library has been declared DEPRECATED since PHP 7.1, to use in its OpenSSL, and a  php script that checks the need extensions, and not hardoced preferd rules for specific webserver.

**Comment by aamiritsu** [comment]
@mckaygerhard : Thank you for your prompt response. i am still concerned is there any compatible xampp version using which i can be able to run it locally?

**Comment by mckaygerhard** [comment]
not so hard, just only download a more older version that performs php 5.6, that's all

**Comment by daN4cat** [comment]
@aamiritsu Yes, probably PHP 7.2 is not supported due to that issue.
The replacement of **mcrypt** is something that needs to be investigated, I cannot remember now from the top of my head if it's CodeIgniter that requires it, but I will open an issue.
So for the time being please fallback to PHP 7.1 which works fine.

**Comment by daN4cat** [comment]
WRT  XAMPP that has been discussed again and again, but the point is that I don't use windows and use a Ubuntu for development and CentOS for deployment.
My time is limited and I cannot test (nor I'm willing to) all the platform combinations of this world. OpenSource is about community that takes share in the work and contributes in a form or another solving issue not creating one after another....

**Comment by daN4cat** [comment]
OK, I read the following: https://www.codeigniter.com/user_guide/libraries/encryption.html
Please make sure OpenSSL is installed and I will remove now the check for mcrypt that is causing the check php.ini since is deprecated.

**Comment by aamiritsu** [comment]
@daN4cat: I appreciate your feedback. I did not mean to hurt you / any of contributors.
Thanks!

**Comment by daN4cat** [comment]
@aamiritsu no it's not you, don't worry. And actually thank you for the hint because I missed this point in PHP7.2. So it's now fixed and in master as 3.2.0.

**Comment by daN4cat** [comment]
BTW...

@mckaygerhard you must clarify this statement now `PLEASE BICHT! be clear!` What did you mean with that part in capital letters?

**Comment by mckaygerhard** [comment]
@daN4cat its a "HARDCODED" popular expresion.. if there not allowed i dont see any rules about it but if you hardcoded expressed i not use it anymore

BTW If I had not helped the client quickly, how much of your limited time would you need to find the problem?

we must understand that this issue its a common problem ahd if there's a check inside ospos, the check also must said was the problem!

**Comment by daN4cat** [comment]
@mckaygerhard to be clear the "hardcoded" expression didn't go down well, so please refrain from expressing similar things and control your language and manners!

**Comment by SteveIreland** [comment]
@odiea  You are probably already aware of these, but I thought I'd mention it here since it seems relevant to me.  

In my php.ini file there is a directive setting shown below that establishes where the php error log will be found.  I think this is the error log being referred to in issue.  This explains why this particular error log isn't found in the public folder (in my environment).
```
error_log ="c:/wamp64/logs/php_error.log"
```
Under httpd.config I can find the directives for two more logs which is less useful to me but was helpful in debugging my url rewrite changes.
```
ErrorLog "${INSTALL_DIR}/logs/apache_error.log"
CustomLog "${INSTALL_DIR}/logs/access.log" common
```
In config.php we can also set where database logging takes place. Leaving it blank will default the location to .../application/logs.  It also needs to be enabled before any logging actually takes place.
```
$config['log_path'] = ''; 
```

**Comment by daN4cat** [comment]
Thanks @SteveIreland I'll copy and paste it in the FAQ so we have a clear explanation. Or maybe create a wiki page and I reference it from FAQ. That would be even better.

**Comment by SteveIreland** [comment]
I'l create a wiki page on the subject of logging (I've been wanting to explore this further anyway) and flesh it out a bit further.

**Comment by mckaygerhard** [comment]
@SteveIreland @odiea great efforts but un-organized, wiki has many link (too much) but not property organized, in consequense, theres too much similar issue and then comes the "limited time" response to users..

too much wiki pages without organization are unuseless..

**Comment by daN4cat** [comment]
I had enough of that guy....

**Comment by mckaygerhard** [comment]
@daN4cat could delete my comment but the email was raised, why? i just suggested a more organized index in the wiki, was not and bad comment! was a true!

**Comment by odiea** [comment]
@mckaygerhard I do not know if this is a language issue or if you just do not like OSPOS? All you have done so far appears is complain.

**Comment by mckaygerhard** [comment]
hi @odiea the las "removed" comment was a need , the wiki has grow up so much now in so many links we need a organized information so we can said "do you read the documentation before"? but its hard for end users, It is difficult to find the information among so many links and pages besides the amount of closed issues. do you read the comment? was deleted!

ospos its very great, i not are a developer but i'll try to find a solution to use it with a connected fiscal printer implementing a hardware repeater..

**Comment by odiea** [comment]
You may be complaining about Github issues and not OSPOS issues. We try our hardest(when we have the time.) to add items to the wiki for the benefit of new users(who apparently do not read the issues or the wiki).
