### ISSUE TITLE
Can't Print receipt from client computer

### ISSUE THREAD

**Issue by jewelosman** [opensourcepos/opensourcepos#1840]
Hi, I am using OSPOS for my shop. I have two windows 10 laptop with LAN connected. I made one laptop as server using XAMPP and OSPOS. And another laptop just accessing the ospos from server. One USB POS printer directly connected to the server and shared for other LAN pc.  I can print receipt from the server. But when I am trying to print receipt from the other PC through LAN. It's not printing. Can you guys pls give me some tips to solve this issue? Thanks in advance.

Regards,

**Comment by mckaygerhard** [comment]
the printing send the pdf to the printer service, so use linux, due the other computer has no real printer.. its a OS problem..

**Comment by jewelosman** [comment]
Hi mckaygerhard, Thank you for the reply. Did you mean the server PC should be a Linux pc or both server and client should be linux PC?

Regards,

**Comment by mckaygerhard** [comment]
@jewelosman i mean that print over network need more component missing on your .. "thing" and that's why doe snot print, its not a OSPOS problem, its a stupid guinwdows problem as always happened.

and i recomended use linux de in bad or good way, linux forced the user to think about the problem before just solved, including if just solved next time user will have an idea of..

**Comment by jekkos** [comment]
Not really ospos issue here.. I close
