### ISSUE TITLE
Invoice Item return 

### ISSUE THREAD

**Issue by dvidic** [opensourcepos/opensourcepos#1920]
- OSPOS version is: 3.2.0
- OSPOS git commit hash is: 
- PHP version is:     7.1
- MySQL or MariaDB version is:      (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2)
- OS and version is:       Windows 10
- WebServer is:     Apache 2.4

### Issue / Bug  / Question / New Feature

Customer makes a purchase, I issue an invoice. After day or two customer want to return one of the items. How to make a return of that particular item from that invoice and then issue changed invoice (invoice must have same number, of course). If I make simple return, I just add quantity back to stock. This is common situation

**Comment by SteveIreland** [comment]
An invoice in most situations is legally binding and immutable once issued.  You can issue a credit against an invoice for items returned but the original invoice cannot be changed.  Now you have a sales invoice and any subsequent credit invoices that accurately reflect the changes made by the customer.   The amount owed by the customer is normally reported in a balance due statement listing the original sales, the credits issued, and the payments received.  OSPOS does not do that. It is either done manually or handed off to a third party financials package.

**Comment by daN4cat** [comment]
Indeed a credit note invoice is the standard procedure to follow.
But this an accounting matter not an OSPOS one I'm afraid.

**Comment by dvidic** [comment]
Hm, I'm not sure. POS should have ability to cancel/delete/change item(s) from an invoice and issue a changed one for the customer. That happens often in sales.

**Comment by daN4cat** [comment]
@dvidic once an invoice is issued it's issued, you don't change it. The normal way is to issue a credit note and another invoice to track the change.
I bet that if you get a fiscal control and they see you amend invoices like that and on the customer side they registered the bigger invoice you will get in trouble for tax evasion due to he fact that your customer deducted a bigger VAT amount and you paid a smaller one.

Therefore I would not implement such feature....

**Comment by dvidic** [comment]
@daN4cat tnx for reply. 
I understand what you're sayin' but when customer makes an item return, invoice is a proof of purchase and there must be a possibility to document that return with that particular invoice. I saw many times invoice which has that. 
Invoice cancellation is done when the change is no longer possible (for example after three days) and it indicates a cancellation of the status that was supposed to be (or was) charged. In a nutshell, it's the creation of a new invoice that has the same look as an original but with a negative amount.

That kind of invoice is totally legal and customer must have ability to have item purchase cancellation.

**Comment by daN4cat** [comment]
You normally issue a credit for the returned item as another invoice.
All the suppliers we use from EU / UK area use that approach, not sure Croatia has a different approach but this is what you can do with OSPOS at the moment: issue an invoice with the return if I got right how it works from @SteveIreland.

Again, I don't use invoice support in OSPOS, so that's the best I can help you here.

**Comment by SteveIreland** [comment]
Here in the U.S. most people cringe at the idea of an invoice being changeable.  In fact, it usually results in the software not being selected for use - especially if a certified public accountant is involved in the decision making.

**Comment by dvidic** [comment]
@daN4cat How to do this in OSPOS 

> You normally issue a credit for the returned item as another invoice.

**Comment by daN4cat** [comment]
You'd better ask @SteveIreland because I don't use invoicing with OSPOS.

**Comment by dvidic** [comment]
@SteveIreland can You please give me a hint on this one? 
TNX
