### ISSUE TITLE
Discounted item info on invoice / quote

### ISSUE THREAD

**Issue by jekkos** [opensourcepos/opensourcepos#1924]
Issue linked to #1824. Yesterday I made an invoice using ospos and found a new column showing discount / item in the item table. This column also shows when there is no discount. I think it should not be the case as it confused me as it seemed that there was a discount.

**Comment by jekkos** [comment]
@SteveIreland as per your request

**Comment by SteveIreland** [comment]
Merci beaucoup

**Comment by SteveIreland** [comment]
Wow.  I'm trying to recall why we added that extra column.  Someone must have asked for the discounted unit price to be displayed.    It cannot be easily conditioned to not display because it messes up the tables (which is what @odiea was warning me about).  So for the moment, so that I can continue with testing I've simply removed the discounted unit price column.   

Does anyone need the discounted unit price column on the invoice?  I'm out of time for the evening so I'll check issue history to see if there was a specific request for it.  If not then I'll just leave it deleted.  If someone tells me that they must have it then I'll added it back  and will figure out a way to properly hide it if there are no discounts on the column.

**Comment by daN4cat** [comment]
I remember somebody asked for it. If you check the history of the specific file you should spot the commit that introduced the change and the # of the issue.

**Comment by WebShells** [comment]
I guess it's a good option to keep...

**Comment by jekkos** [comment]
Well from a business perspective I think it's bettter to show a customer the total discount he got on the whole receipt instead. Next to that we can keep showing discount percentages, but showing the discounted amount per item kind of clutters up the receipt imho.
