### ISSUE TITLE
Support for QR code

### ISSUE THREAD

**Issue by rizwanali034758** [opensourcepos/opensourcepos#1935]
I just want to ask that is ospos support for qr code and in future are you working on this feature?

**Comment by SteveIreland** [comment]
I doubt if there are any plans for it.  How would you expect it to be used in OSPOS if there were?  We need more information to determine the cost/benefit.

**Comment by rizwanali034758** [comment]
Today most of products comes with QR code instead of barcode. Products with qr code have to manually add in sale and receiving. Can you enhance ospos to add item in sale and receiving by scanning QR code instead of barcode. In future you can work on generating QR code.

**Comment by daN4cat** [comment]
Which products are you talking about? I don't see QR codes on grocery products and fashion garments for instance.

**Comment by rizwanali034758** [comment]
Most of the food companies for example nestle and lays uses qr code on their products. Electronic products also comes with qr code including mobile phone etc.

**Comment by mckaygerhard** [comment]
maybe there's any php lib that not implicts load many thnigs,  that can be includen in thirth party directory like  https://sourceforge.net/p/phpqrcode/git/ci/master/tree/lib/merged/phpqrcode.php seems does not need many php files and are easy to use, compatible with php 5 nd 7 and not need others depends..

**Comment by daN4cat** [comment]
Maybe you are missing the point guys, OSPOS receives a numeric code from a scanner.
The scanner needs to read the QR code and produce a string that is then matched with the one stored in the item barcode, the matching is done by OSPOS in the sale register function.

If it is a matter to printing QR codes instead of current barcode formats there is https://github.com/dwisetiyadi/CodeIgniter-PHP-QR-Code

That can be added to the current barcode support and produce a QR code image as we do with the barcodes.

Good for a contribution by some of you guys.

**Comment by SteveIreland** [comment]
When scanned does the QR code simply render another UPC (or EAN) code?

**Comment by daN4cat** [comment]
@SteveIreland any string is fine, unless it's longer than 255 chars.

**Comment by nerv55** [comment]
@rizwanali034758  QR code has more than only product's code, when you scanned and see the output in notepad or another text editor, what did you see?, anyway you can input the  QR code data into the barcode field in product form, that way you can use pre-printed product QR code, I assume you have QR code reader in your store.

**Comment by nerv55** [comment]
@rizwanali034758  check the string inside those pre-printed QR codes that you have in your products if is less 255 character you can use it in the system without make any modification

**Comment by mckaygerhard** [comment]
why 255 its the limit?

**Comment by nerv55** [comment]
@mckaygerhard  because in the table definition the max size is 255 for barcode if you put more your data will be truncated.

**Comment by SteveIreland** [comment]
For these items that printed with QR Codes do they not also have the usual barcode printed?  If not where can I find the documentation for how the product code is encoded?  So far everything I've read about it suggests that its use is proprietary to a particular company.  There may be an industry standard for shipping but I haven't had to work with it yet.  I've used my iPhone to scan QR codes to join reward programs but that's the extent of my experience with it.  Obviously UPS, FedEx, and other shippers using it to track shipment but OSPOS isn't a shipping system ... yet  :wink:

**Comment by mckaygerhard** [comment]
umm the  current formats there is https://github.com/dwisetiyadi/CodeIgniter-PHP-QR-Code does not are enought? as i read said "to create QR codes" @SteveIreland and seems easy for codeigniter

**Comment by SteveIreland** [comment]
The question is about business requirements ... not technical.  As @daN4cat tried to point out, so far I haven't read where anyone was asking about generating QR codes, so at this point we don't need to create one and we don't need a third party component.

The secret to avoiding unnecessary work is in asking the right questions and someone providing the right answers.

**Comment by nerv55** [comment]
@SteveIreland but in this case @rizwanali034758 is asking to read pre-printed QR code, no generate new ones, and as I write if he see information that is inside this codes and the string is less than 255, he can use the program as is, without modification. He already has the reader to decoded the QR code. just need to check the returned string.

**Comment by SteveIreland** [comment]
Right, he is asking to read ... not generate ...  which is what I posted.  

A QR Code is used to store a ton of information.  He is saying that there is a QR Code on the product packaging.  What I would need in order to do anything with it is to know where the UPC code (or equivalent) is stored within the QR Code data stream which can be over 7000 characters of data.  A proper solution for the purpose of OSPOS would be to extract the UPC code out of that data.  We only need 13 or less characters out of that 7000 characters of data to identify the item.   For example, if the mandated government or industry standard is that the UPC code is the first piece of data in the QR code then I would want to know what the delimiter is (what tells us where the UPC code ends) or if it is fixed position then I would want to know what start and start character positions are.

Surely, if in his country there is some government mandate to move to QR codes then there must be a standard for the format of the QR Code.  In the U.S. QR codes are not yet used for that purpose.  The uses are proprietary ... not standard.

My assumption at this point is that there is some confusion as to what the QR code represents and that there is also a bar code on the package.  That's the only thing that makes sense to me.  But my world-view is admittedly limited.

**Comment by daN4cat** [comment]
@SteveIreland we can just hash the long string to a smaller value to fit the 256. We can automatically hash the string if bigger than 256 as I doubt anybody wants to read a long string in any report or items view. Also fitting 256 in Items view will be fun, probably we would need to add the ellipsis to avoid any issue.

**Comment by SteveIreland** [comment]
That would definitely work if we can safely assume that the first 255 characters are the same for all packages of the same item ... but what if it includes a packaging lot number or date stamp?

**Comment by daN4cat** [comment]
@SteveIreland not sure I get, I suggested to hash whatever value you read from the QRCode. md5 hashing should be secure enough to avoid any collision.

**Comment by SteveIreland** [comment]
I did a bit more research on the QR codes that are being included on some products and essentially they contain a URL to a page on the producer's Web site that contains more information about the product.  This"standard" is actually part of a licensing agreement with a company known as SmartLabel.  All of the products continue to have the  barcode for the UPC/EAN item number included on the package.  This is the retail use in the U.S.

In Japan there is an emerging standard to include both the GTIN (Global Trade Identification Number) as well as the producer's URL to the product information page in the QR code. 

I don't know if GTIN has any correlation to UPC or EAN codes.  I hadn't heard of GTIN codes until today.

**Comment by mckaygerhard** [comment]
i also research and there's no standart in QR codes.. they can contain any thing, but mayority of use are for urls and short info, so they can use to crypt/encode codes or id's .. if this are the behaviour seems integrate into ospos will need a detection if are url, only string info or a product code identification, that's makes no sense, unless we put as optional filed/feature of the product

**Comment by daN4cat** [comment]
I close, this does not make sense.
