### ISSUE TITLE
Multiple client support

### ISSUE THREAD

**Issue by StanlySimon** [opensourcepos/opensourcepos#1937]
Is OSPOS can be configured for multiple client support.

**Comment by StanlySimon** [comment]
Yes I meant multi tenancy.
Thanks

**Comment by StanlySimon** [comment]
Can I expect Expense module added in future release.
It will be great if this module is available as I can deploy for one of my client who really needs.
It will become a small ERP

**Comment by mckaygerhard** [comment]
maybe can be done with those changes @daN4cat, i was thinking before that :

1. each table must have a second column parto of the PK, and then those values will be each client company
2. a table of each client company, and this must be selectable in the login screen as 3rth field (selector)

**Comment by mckaygerhard** [comment]
@StanlySimon  respect of you, an ERP implicts accounting.. and OSPOS its a POS system, this must be clear..  for sure

**Comment by StanlySimon** [comment]
Thanks @mckaygerhard

**Comment by marcellusmontilla** [comment]
@daN4cat have you done something like this before (in other projects)? I have no idea how it's done and the online literature is kind of confusing or maybe I'm looking in the wrong places. Can you point me to a good resource or maybe an open-source solution? I'm hoping to implement something like this to a different project (not OSPOS).

**Comment by daN4cat** [comment]
@StanlySimon, as said already multi tenancy implemented in a professional way is not there and I'm not sure we will ever get there. If you want to setup a SaaS business around OSPOS selling multi tenancy services well, I'm sorry pay the bill to get there :-) I'm not going to work for free for enterprise type of solutions.

WRT Expenses, yes it's in 3.2.0 but for the sake of keeping a shop journal and get the petty cash in your cash drawer right when the cashup part will be implemented. OSPOS is not an accountancy tool.

@mckaygerhard as already said, there are amateur approaches and professional ones. I work with the latter in mind, free to do your job with the former. For sure I would not run my business with your solution because I'm afraid you have a way to go to understand the implications of running SaaS multi tenant solutions.

@marcellusmontilla yes, I've done multitenancy SaaS solutions. My real job is Lead Architect, what I do here is just for "fun" and for my wife's business.
And making multi tenant a SaaS solution is just one part of the puzzle, there is even the scalability and availability part to consider. Not to mention all the security aspects, which we (@jekkos and I) have implemented but does not complete the picture as you need to consider many other factors.

**Comment by marcellusmontilla** [comment]
@daN4cat What's the best paid alternative based on your experience? And is there an open-source solution we can try, i.e., not enterprise-level, may be used for development and testing purposes.

**Comment by mckaygerhard** [comment]
umm as some of the @daN4cat points, of course as i already said, this can implicts accounting and make the OSPOS a software that others will use for SaaS, and them finally, all benefit will NOT end in the project, but in those who "copied" will have it!
in those cases, management must be done, to make a software project more realitable, and can survive to their consumers (that are not the real users of).. the documentation it's a started point that i try to improved now..

of course @daN4cat i have that in mind too professional way, in my side, the mayor two problems it's the time and the coding experience (due i'm not developer), i not have problems in make it for free, in fact i have some experience in Sybase, due its powered replication feature (It IS an invaluable and incomparable unti8l today), i remenber that the proposition that i point its easy to do: 
1. only important tables must have a second column parto of the PK, and then those values will be each client company
2. a table of each client company, and this must be selectable in the login screen as 3rth field (selector) and maybe some extras of those tables

those changes not make it professional but makes a featured start point

**Comment by jekkos** [comment]
I do have some kind of multi tenancy in an old branch.. I rerbased it up until 3.0 or 3.1, not sure. However depends on what you want exactly

* have multiple stores operating next to each other (using same db / webserver) but not sharing data in any way
* have multiple stores operating next to each other, sharing all the same data for sales and receivings, items etc

**Comment by mckaygerhard** [comment]
the easy solution its _have multiple stores operating next to each other (using same db / webserver) but not sharing data in any way_ se second need more code and work as danacat said

**Comment by jekkos** [comment]
I think there's even a working version tagged on docker hub :+1:

**Comment by daN4cat** [comment]
Multi store same client is simpler than multi client/tenant. It's just an extra dimension on shared data mapped to different stock locations. But the central admin of multiple stores and access permission management is another aspect that needs to be solved I guess.

**Comment by jekkos** [comment]
Yes indeed I revamped the employee permission section so that admins could grant users access each module in a store specifically,so I guess I tackled that one.

**Comment by SteveIreland** [comment]
If the requirement is to provide OSPOS hosting services for businesses then the single database solution is very bad solution.  Practical solutions such as when a company wants to move their business to someone else then you'd be obligated to provide a way for them to migrate away.  Easy when each company has their own database, but a real pain in the rear when the multiple companies are embedded in the data. 

If you are in reality supporting a single umbrella company (such as @jekkos running several of his businesses with the same software) then a single database is the better solution but will require some non-trivial changes.

**Comment by daN4cat** [comment]
Indeed, proper multi tenancy requires database schema separation even for security purposes.

**Comment by JvalantThakrar** [comment]
> I think there's even a working version tagged on docker hub  . Will try to spin it up later today. Dates back to a year ago, so no idea on what version it is based.

Hi @jekkos , great work. I have been following this since I was in my graduation. I have worked on a parallel system that serves the purpose for customer referral based rewards (Direct Referrals as well as MLM way). I can provide the source code to be merged here if you like it. 

Between, I was just wondering which of the previous branch had the multi-tenancy feasible. I have done this before on top of 3.0.1 but that source code is no more working for me and I don't have any notes/documentation available anymore.

If we still have the multi-tenancy feature in one of the branches, that will be great for me to take references from.

Best regards,
J.
