### ISSUE TITLE
Scale weight   

### ISSUE THREAD

**Issue by mazenalaghbari** [opensourcepos/opensourcepos#1948]
Is it possible to connect scale weight to OSPOS ?

**Comment by WebShells** [comment]
Please do a simple search in order to discover whats available and whats not... We cant reply without you filling in the Issues Template... Its a duplicate issue... Closed.

**Comment by mckaygerhard** [comment]
always, always this kind of isues will happened due the "faboulus" README are very vage! and the spectacular TEMPLATE are not-user-friendly

**Comment by nerv55** [comment]
@mazenalaghbari  this feature is not implemented in OSPOS yet.

**Comment by WebShells** [comment]
@nerv this was implemented a few months ago.
@mckaygerhard I guess it'll stay until we find another thing to fill its place, as you see we can't even tell which version the user installed, thus we can't help...

**Comment by mckaygerhard** [comment]
@WebShells that's not true, as i posted previously there's many ways to do this in this github interface.. many other projects where i have involucrated do better that! obviously.. and its impossible due my prevously effors make sarcastic!

**Comment by WebShells** [comment]
This was assigned to be done by 3.1.0 milestone and was pushed to repo that time. 
When I said implemented i didnt mean at all that Qty should be inserted as decimals. There is no connectivity between OSPOS and the scale itself. 
The Qty. encoded barcode can be read through OSPOS depending on barcode parameters configured in barcode section in admin panel. 
@mckaygerhard please let's keep our topics under 1 discussion without any diversion, the issue here is "Weighted products".

**Comment by WebShells** [comment]
@daN4cat, i dont think the interaction between OSPOS and scale over socket is done yet... Maybe @jekkos released it over a private installation. But to what am up to already weighted products can be sold by specifying specific barcode parameters through the admin panel depending on exact weight of product ( Qty.) ...

**Comment by daN4cat** [comment]
Yes, @jekkos did the sokect.io feature for a private project.
Yes, the barcode solution works for scales that print a barcode with the weight in it and can be decoded with what @jekkos implemented.
