### ISSUE TITLE
Employee Login password Expiry Date

### ISSUE THREAD

**Issue by engehab87** [opensourcepos/opensourcepos#2051]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.3
- OSPOS git commit hash is: 
- PHP version is: Latest
- MySQL or MariaDB version is: MySQL
- OS and version is: Windows 7
- WebServer is: Localhost
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

i need to implement a feature that would notify the user that his password will expire soon and then expire when it reaches a certain date.

need this for more security reasons, is there a chance that anyone would assist me in it or do it for me.

**Comment by mckaygerhard** [comment]
ospos developeers seems are busy but for a couple of bucks i can doit

**Comment by engehab87** [comment]
i can't afford any payments for now, but if you would help this will be really appreciated

**Comment by mckaygerhard** [comment]
documentation are very xplicit, so must be enought (due has by casuality explained that you need, the employee) but in any case the developer needs are very close to LINUX os tools, and as i noted your os are guindows so i dont expect that can doit by yourselft  (due event review the code you ask for  and guindows users are click click click)

**OPTION A)** for starting development read here: https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-development-index#code-and-api-documentation, of course you will need a complete development environment for that read here first https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-Environment-Development specifically the "Basic Tool installation" section, of course must search those tools for mac event for linux, due are UNIX related OS's will work as spected (not like the stpudi guindows does) maybe will not be fast a good reading are https://treehouse.github.io/installation-guides/mac/node-mac.html (its a github repo too) take care of howbrew path..

**OPTION B)** download a venenux os iso  at https://sourceforge.net/projects/vegnuli/files/VenenuX-1.0/venenux-1.0-osposweb/debian-venenux-8-osposweb-i386.hybrid.iso/download and install, it comes with all need installed and a ospos old version to start to develop, but this option are for linux users due comes with geany (for coding adn see preview in embebed web), meld (for diff code changes), giggle (for graphical git viewer), git (of course), mysql-workbecnh (complet mysql development environment), and the apache2, php5, mysql server and underneed tools

**OPTION C)** in other hand if you dont want to mess with all the very unnecesary complicated development environment, download a lasted bintray version of ospos and then start from that decompresed code! more easy and faster ... of course..


**once understand the starting point the only need by you its a trigger for you "expiration notification" and there's two ways to do that, once it's by each user request, other it's by cron task, of course the only option to you are the first, on each request check the date and send notification to fronend**

**Comment by mckaygerhard** [comment]
documentation are very xplicit, so must be enought (due has by casuality explained that you need, the employee) but in any case the developer needs are very close to LINUX os tools, and as i noted your os are guindows so i dont expect that can doit by yourselft (due event review the code you ask for and guindows users are click click click)

for employee api read here: https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-development-index#code-and-api-documentation,

OPTION A) you will need a complete development environment for that read here first https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-Environment-Development specifically the "Basic Tool installation" section, of course must search those tools for mac event for linux, due are UNIX related OS's will work as spected (not like the stpudi guindows does) maybe will not be fast a good reading are https://treehouse.github.io/installation-guides/mac/node-mac.html (its a github repo too) take care of howbrew path..

OPTION B) download a venenux os iso at https://sourceforge.net/projects/vegnuli/files/VenenuX-1.0/venenux-1.0-osposweb/debian-venenux-8-osposweb-i386.hybrid.iso/download and install, it comes with all need installed and a ospos old version to start to develop, but this option are for linux users due comes with geany (for coding adn see preview in embebed web), meld (for diff code changes), giggle (for graphical git viewer), git (of course), mysql-workbecnh (complet mysql development environment), and the apache2, php5, mysql server and underneed tools

OPTION C) in other hand if you dont want to mess with all the very unnecesary complicated development environment, download a lasted bintray version of ospos and then start from that decompresed code! more easy and faster ... of course..

once understand the starting point the only need by you its a trigger for you "expiration notification" and there's two ways to do that, once it's by each user request, other it's by cron task, of course the only option to you are the first, on each request check the date and send notification to fronend

**Comment by SteveIreland** [comment]
I was thinking that $2 dollars was an awfully good deal.  A shot of whiskey is at least $6 dollars.  :-)

**Comment by mckaygerhard** [comment]
well @SteveIreland some people maybe not have "sustantial economic" je je by example here in Venezuela 1,8 $ its a complete "minimal salary of a month" ...

**Comment by SteveIreland** [comment]
Understood, but regardless $2 is STILL an awfully good deal on any software change or support request..  The only better deal is free ... which is what we're doing here.

**Comment by mckaygerhard** [comment]
yeha i understood too, umm noted wee need more api documentation, i started to make a async api as i plans to integrate a specific androit app. if i have lucky i upload more documentation but still are experimental in the osposweb code

**Comment by mckaygerhard** [comment]
yeah i understood too, i hate guindows but loved guindows users, just due are only click click click thanks to that many linux users got much money XD XD XD 

umm noted wee need more api documentation, i started to make a async api as i plans to integrate a specific androit app. if i have lucky i upload more documentation but still are experimental in the osposweb code

**Comment by engehab87** [comment]
i'm sorry but i still didn't get an answer, is there a way to have this done ?

**Comment by mckaygerhard** [comment]
ahh emm, @engehab87 please, please do you read the previous answer by me! where i put to you the links of documentation? I want you understand that what I am going to answer is not rude, it is a rather hard and true reality:

**in first place:** I have explained how to do it, obviously if you still ask is because for sure you use or are a user of guindows M$ OS and do you think that with two clicks it will be done, there is no IDE or development interface, you must use git, editor like geany and preview changes in the browser with F12, for all this this this the wiki page I put you...

**and secondly** the amount of 4$ or inclusivelly 2$ or 1$ are miserable if you do not know how to do it, please men!

documentation are very xplicit, so must be enought (due has by casuality explained that you need, the employee) but in any case the developer needs are very close to LINUX os tools, and as i noted your os are guindows so i dont expect that can doit by yourselft (due event review the code you ask for and guindows users are click click click)

for employee api read here: https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-development-index#code-and-api-documentation,

OPTION A) you will need a complete development environment for that read here first https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-Environment-Development specifically the "Basic Tool installation" section, of course must search those tools for mac event for linux, due are UNIX related OS's will work as spected (not like the stpudi guindows does) maybe will not be fast a good reading are https://treehouse.github.io/installation-guides/mac/node-mac.html (its a github repo too) take care of howbrew path..

OPTION B) download a venenux os iso at https://sourceforge.net/projects/vegnuli/files/VenenuX-1.0/venenux-1.0-osposweb/debian-venenux-8-osposweb-i386.hybrid.iso/download and install, it comes with all need installed and a ospos old version to start to develop, but this option are for linux users due comes with geany (for coding adn see preview in embebed web), meld (for diff code changes), giggle (for graphical git viewer), git (of course), mysql-workbecnh (complet mysql development environment), and the apache2, php5, mysql server and underneed tools

OPTION C) in other hand if you dont want to mess with all the very unnecesary complicated development environment, download a lasted bintray version of ospos and then start from that decompresed code! more easy and faster ... of course..

once understand the starting point the only need by you its a trigger for you "expiration notification" and there's two ways to do that, once it's by each user request, other it's by cron task, of course the only option to you are the first, on each request check the date and send notification to fronend
