### ISSUE TITLE
Add a database query in the summary report

### ISSUE THREAD

**Issue by mpr92** [opensourcepos/opensourcepos#2084]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.2
- OSPOS git commit hash is: 
- PHP version is: 7.1.7
- MySQL or MariaDB version is: 10.1.25-MariaDB
- OS and version is: 
- WebServer is: Apache/2.4.26 (Win32) OpenSSL/1.0.2l PHP/7.1.7
- Selected language is: German / English

### Issue / Bug  / Question / New Feature

I have the following problem. I would like to add another column in a report (tableExport, for example Summary_items.php). For our accounting, it is important that the VAT rate of the article is also expressed in percent. The field is stored in the database, but how can I read it out in the table? As an example here is the report after my attempt or how it should look like.
I hope someone can help me with a snippet of code that I can insert.
![screen_tableexport_summary_items](https://user-images.githubusercontent.com/25674011/44143394-d34eb3b2-a083-11e8-812e-fe52ac8a2412.png)

**Comment by SteveIreland** [comment]
There can be multiple tax rates for a single item, so I'm assuming that in your scenario you are only using the first tax rate on the item?  Still, this will be a complex change because the tax isn't actually stored on the items table and for the Summary Items report the taxes are summarized and the specific tax rates are lost. I don't think a snippet of code will do the job for you.

If you can form an SQL statement over the database that provides the table of data that works for you then you would be better  off creating a new report. I would personally try an SQL reporting tool (Reportico or something else) before attempting changing the existing system.

Having said that, if if works for your site, it might be possible to rework the tax summary logic and the join to your new tax summary temp table but that will be quite a challenge. 

Good luck.

**Comment by mpr92** [comment]
Stevelreland, thanks very much for the detailed answer and your explanation.

Oh, that sounds complicated indeed. So all my products have only one tax rate. I'm not quite as fit in PHP and SQL, I can do a little, but I thought you could just read the database tax of each article. Just like the name of the article simply the tax rate or the ID of the tax rate. Is not this solvable?

The problem is that we have to pay taxes for the tax office and the bookkeeping and that it is output in the report would make the work enormously easier for us.

Anyone else has an idea, please?
