### ISSUE TITLE
username and password is not working

### ISSUE THREAD

**Issue by Waqas-Ali-Azhar** [opensourcepos/opensourcepos#2110]
Hi, I am trying to login to the demo link but it is not allowing me to login saying username or password is not correct

**Comment by jekkos** [comment]
Just checked and indeed, someone was able to change password again. I reset it now.

**Comment by jekkos** [comment]
OK I see the problem was that the environment mode was not set in the container, adapted the script a little bit now (so it waits for the container to start before doing the find/replace)

**Comment by mckaygerhard** [comment]
hi @jekkos i'm glad to see that in this case you find a little misctake, lest see:

> Just checked and indeed, someone was able to change password again. I reset it now.

and later you find the real reason:

> was that the environment mode was not set in the container

many other of course are that king of mistakes.. 

we need to take many many care to assume "if someone are made crap" due i'm pretty sure it's not! 

ospos need many fixeds to property work in each environment and that's why i setup the wiki, but whenantime developers dont take part and dont make more flexible about their each position.. will be impossible!

rthat's the reason i have a fork! so @jekkos my note it's just for claryfy.. i always contribute as possible to me!

**Comment by jekkos** [comment]
just tried now and password change has no effect neither through employees nor logged in user dialog.

**Comment by odiea** [comment]
I assume you must be working on it. This is what I got when trying to loggon.
502 Bad Gateway
nginx/1.10.3 (Ubuntu)

**Comment by odiea** [comment]
Does not accept user name or password.

**Comment by jekkos** [comment]
Should be fixed now
