### ISSUE TITLE
How to pay half in due payment

### ISSUE THREAD

**Issue by kalanapiumal** [opensourcepos/opensourcepos#2112]
- OSPOS version is: Newest version

hi i want to know how to add half cash in due payment

**Comment by SteveIreland** [comment]
I reopened this issue a bit just to be able to clarify a few points.

First: A partial cash payment can be combined with a partial credit cart payment or gift card to "complete" the sale,

Secondly: A partial cash payment can be entered but in order to complete the sale you will need to change the register mode to invoice because now it becomes something that needs to be processed as a receivable.

And Final Point:  If  you are going to allow people to walk out the door without paying the complete order (and not following up for payment) then you shouldn't you be adding an additional item to the order to adjust the order down to what was actually paid so that you can track he loss?  I haven't tried this myself but it should be doable,

**Comment by kalanapiumal** [comment]
CAN I KNOW YOU GUYS ARE RELEASING A NEW VERSION WITH FIXING THIS BUG AND WHEN PLS

**Comment by SteveIreland** [comment]
Everyone who wants some assistance should expect to participate in a dialogue about the issue. I took the time to offer you three alternatives which you ignored.

Nor have you explained n the scenario which justifies a partial payment so I suggest we flag this as “not a problem” and close it.

**Comment by SteveIreland** [comment]
Oh duh. @webshells already had it closed and then was foolish enough to reopen it

**Comment by daN4cat** [comment]
@kalanapiumal it's not supported and to support that it will require some work. Nothing I want to commit too, I added the due payment at the time as the ability to change the payment type but not to manage payments in instalments.
What you can do is return the sale and issue a new one, same items, with a new due payment and the rest is cash. Then you give back the new receipt for the old one to your customer.
