### ISSUE TITLE
Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php

### ISSUE THREAD

**Issue by Elhy** [opensourcepos/opensourcepos#2118]
Please please, someone  can tell me the steps to resolve this issue (step by step because I'm beginner in php)

Thanks for advance

**Comment by mckaygerhard** [comment]
download the bintray files, stable file or download the ready to use iso pointed in the wiki install and follow the instructions.

@Elhy  this happened due you dont read the property related documentation, and also if you download from github directly or do not set property the isntallation directory.

so this issue can be closed

**Comment by odiea** [comment]
to many other issues like this. People do not read the open or closed issues

**Comment by mckaygerhard** [comment]
@odiea do you try changing that template and a more flexible approach? 

thoses users are not linux zealots, are only common users that try to use the ospos system, of course thei dont read the template!

maybe if we ask for less information and only ussefully thnigs...

**Comment by mckaygerhard** [comment]
ok @odiea Let's take some cards on the issue, you say it's not the os, but the trends are clear:

if a person is like he is because of the way he has been brought and their customs defined by what he has lived... then a user is defined by the way he is used to handle his devices... 

I mean, a mechanic knows how to drive a car... a linuxer obviously knows how to fill in an issue.

**@odiea  We can't demand to someone be more clear about what they are taught to be, or go any further than their forehead can go... so we either dock with the users or treat them badly?**

**Comment by SteveIreland** [comment]
The installation instructions are found at  https://github.com/opensourcepos/opensourcepos/wiki

I'm in the process, as time allows, of testing the instructions and cleaning them up.  Since I'm not a Linux person but reasonably good at following instructions I think it's a good test if I can follow all of the instructions and get it going.  It also gives me a good excuse to purchase a Rasberry Pi
