### ISSUE TITLE
Item Count Total

### ISSUE THREAD

**Issue by leominojr** [opensourcepos/opensourcepos#2160]
https://i.postimg.cc/GmDSZn3M/received_1925422640877925.png

I would like to ask maybe this is an existing issue. I want to display the total of each in and out in item inventory count.

**Comment by izeblood** [comment]
The purpose of this feature (individual data tracking) is to trace the individual event of a certain item and this will be the last defense of the administrator(business owner) in order to validate and check the work of his/her employeess. Talking about the In and Out, the OSPOS is capable of the Receiving (In of products) and Customized SAles (Out) which is sold.
