### ISSUE TITLE
Tax Decimals

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#2172]
I was testing the master branch this morning in order to compare the results of master vs the results of the India GST branch and stumbled across something that caused me a bit of concern.

We seem to have a difference of opinion on the use of the tax decimals fields so before I go any further we need to come to a consensus.  The following are the rules that I've been working with for the last couple of years.  I BELIEVE the following rules were in place at one point in time but subsequent changes have resulted in something else happening.  It might not have been in place for all tax configurations because I was originally hesitant to touch the Included Tax scenario - but now that I'm touching which is why I need to raise the issue.  I'm adaptable, so if the following rules don't work I'd like to understand why so that I can make the necessary changes for India GST that won't break the rules that others need.

1. Tax amounts (not tax rate) displayed to the user the calculated amounts should always be in currency_decimals ... not tax_decimals.

2. The tax rate stored internally will always be the max of four decimal positions (as defined by the database).

3. The internal tax calculation that derives the tax amount uses the tax decimals to determine the tax amount.  This rounded amount is stored in the sales_item_taxes table.

4. The total taxes accumulate the amounts that were rounded to the tax decimals and then rounds those to the currency decimals so that the customer knows how much they are paying in taxes.  The tax amount rounded to currency decimals is what is stored in the sales_taxes table.

**Comment by SteveIreland** [comment]
**Question 1**

With "tax included" in the price then I can see where it really doesn't matter how the taxes are represented on the sales page because we're not asking the customer to pay it. (Actually I'm not sure why it's displayed at all.)  So if the system is configured for tax included then I'll make sure that the taxes are displayed and saved rounded to the tax decimals.  Otherwise the taxes need to be displayed and saved to the currency_decimals.

If the receipt is configured to display taxes then it will be displayed in the tax_decimals if the system is tax included and it will be displayed in currency decimals if not.
 
Does anyone disagree or have any questions?

**Comment by daN4cat** [comment]
I feel the pain coming.... this is swamp. Getting the rounding rights with taxes is an awful job.
However you went through that already and the cent/penny mistake won't come as a surprise to you.

**Comment by SteveIreland** [comment]
Absolutely ... that one has been has already been included at the top of the test scenarios.

I don't think anyone is going to look at this until after it's been merged ... but I'm not ready for it to be merged.  I will be giving it a thorough test over the next two weeks and making any necessary corrections.

**Comment by jekkos** [comment]
@SteveIreland thanks for looking into this. There are indeed issues with the tax included calculations pre 3.0 and I don't think it was deeply touched afterwards. i heard from my accountant that basic VAT calculation is always off a couple of euros (possibly due to rounding issus, so might want to try with the precision to see if it helps).
Anyway the user does really pay that VAT to the seller who has to pay then part of it back to fiscal authority. It was me that introduced this VAT included concept back in the days. In Belgium you are obliged to always advertise your price with VAT included, so it was a necessary one (as we enter all product prices like that)

**Comment by jekkos** [comment]
I don't really know  how or remember how the preicision story was worked out here but might want to take a closer look first

**Comment by SteveIreland** [comment]
Thank you for the info. 

On the `sales_items_taxes` table the sales tax amount for each item is rounded (half up) to the nearest tax_decimal.   Once the tax amount is identified at the item level then the goal is to accumulate this amount by tax group and then round that amount to currency decimals.  This amount is what is stored to the `sales_taxes` table.  In a non-VAT scenario this is the tax amount collected from the customer.

I believe that is the amount that is currently being used to report taxes in the tax summary report. 
 It's been awhile so I'll need to confirm that.  In a "tax included" scenario that could certainly be a contributor to the rounding errors that your accountant is reporting.  We might be able to reduce that if I make sure that the `sales_taxes` table continues to track taxes at the tax decimal level in a "tax included" configuration.

**Comment by objecttothis** [comment]
@SteveIreland our usage falls into the "taxes calculated into the price" category, so I don't often pay attention to the tax, but what could be done in that scenario is to show the portion on the price that is tax.  For example, in our case, there is a 4% simplified tax built into the price of each of our items.  If the item was 3,00AZN, then the receipt would show the total as 3,00AZN, the tax as 0,12AZN and the item price as 2,88AZN.  

There would need to be a "tax included" flag in the configuration to trigger this form of calculation.  This is really not important for us, so no need to jump on it unless it's really easy.  I may implement it in the future but I wanted to state it here so that this scenario has a voice.

**Comment by daN4cat** [comment]
@SteveIreland, is this solved with your GST rework?

**Comment by daN4cat** [comment]
@SteveIreland any update?

**Comment by daN4cat** [comment]
@SteveIreland same question: status?

**Comment by SteveIreland** [comment]
I'm pretty sure it's resolved.  I made the changes I thought were necessary and it seemed to be working as needed during my testing at the time.  But it's been a couple of months.  No one has reported any issue with it so I think it can be closed.
