### ISSUE TITLE
ospos does not start

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#2187]
There is a problem loading a new OpenSourcePOS 3.2.3 release database. OSPOS remains at the start of the session. I think the problem is that Revert original tables.sql to 3.0 (# 68)

**Comment by SteveIreland** [comment]
I would assume that there were no changes to the 3.2.3 release.   It doesn't look like it has changed since June.   Did you actually mean the 3.3.0 development branch?  #68 was merged into the development master branch.

I haven't had a chance to try it out yet but will do so tonight if I can't make any progress on my rebase effort.

**Comment by SteveIreland** [comment]
Hmmmm.  I couldn't resist giving it a try immediately and had a similar issue.

My issue is that the first page displayed shows "The application environment is not set correctly."

I double checked it and I'm 90% sure that I did everything I normally do, but I definitely need more coffee before checking it again so that I can be 100% sure.

**Comment by andriux1990** [comment]
Thank you @SteveIreland. At night I will do some tests.
