### ISSUE TITLE
Weblate down for maintenance

### ISSUE THREAD

**Issue by jekkos** [opensourcepos/opensourcepos#2217]
I thought I'd announce it here. Was trying to upgrade to the latest master yesterday.
Also it seems that new users can't register. But currently it got stuck running a database migration.

**Comment by objecttothis** [comment]
any ETA on weblate?  currently weblate is giving a blank screen with a simple "Internal Server Error" message

**Comment by jekkos** [comment]
I'll try to have a look this weekend.

**Comment by objecttothis** [comment]
Anything new on this?  I tried logging in again, but get the same message.

**Comment by jekkos** [comment]
Quite busy this week and didn't find the time yet to look at it. Will try again soon.

**Comment by objecttothis** [comment]
No worries, just curious.  This is off topic, but would it be helpful to create a room in gitter for active developers?  This might make collaboration easier and due to gitter being more "live chat"... only for some conversations that is.

**Comment by jekkos** [comment]
Up to now I never used gitter but this could be interesting indeed? I upgraded to the latest weblate version now, and started over again from a fresh database as the old one failed to upgrade again at a certain point.

This meeans that all login data is gone. But now the github oAuth seems to work so you can just create a login coupled to your github account. @objecttothis can you give this a try and see if it works?

**Comment by SteveIreland** [comment]
@objecttothis Interesting.  I haven't heard of gitter before but I see that you've been participating in an OSPOS chatroom on gitter for quite some time.

https://gitter.im/jekkos/opensourcepos

I hope you don't mind me listening in periodically. :-)

**Comment by objecttothis** [comment]
@jekkos yes, it's working now.  I was able to login with oauth. It's funny that you hadn't used it because I just assumed that you had set it up.  Gitter is Github's version of Slack.  Think of it as a successor to IRC. Right now there is just a general room for the repository.  My suggestion is two-fold:
1. Change the URL from /jekkos/opensourcepos to /opensourcepos/opensourcepos to better match our current repository naming.
2. Create a contributors-only room to make it easier to dialog about things like roadmap decisions, whether or not to implement an issue, collaboration, etc.

@SteveIreland I don't go in there every day but when there is something that is quick and easy to answer, I usually will put my two cents in.

**Comment by jekkos** [comment]
Ok I managed to import all 142 users again, but not their preferences. That would be a last useful thing as some won't be notified if there's something new to translate now.

**Comment by arteiro** [comment]
I am unable to access my account in the Weblate

**Comment by jekkos** [comment]
can't you reset your password then?

**Comment by arteiro** [comment]
Solved, Thanks
