### ISSUE TITLE
Timeout Encountered in Attributes Migration

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#2241]
I encountered the following error in the step where it was migrating attributes.

```PHP Fatal error:  Maximum execution time of 120 seconds exceeded in C:\vroots\ospos0\vendor\codeigniter\framework\system\database\drivers\mysqli\mysqli_driver.php on line 305```

To work around this issue I added the following statement.

```set_time_limit(1200);```

... as in ...

```<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

class Migration_Attributes extends CI_Migration
{
	public function __construct()
	{
		parent::__construct();
	}

	public function up()
	{
		set_time_limit(1200);
		execute_script(APPPATH . 'migrations/sqlscripts/attributes.sql');
	}

	public function down()
	{

	}
}
?>
```

Which seemed to resolve the issue.  I migrated 3 custom attributes for over 12,000 records.

Obviously this is an environmental issue so I'm reporting this as a possible solution for specific scenarios.  There is also an alternative solution if you can change your php.ini if you encounter this issue.

**Comment by daN4cat** [comment]
Maybe you meant @SteveIreland ?

**Comment by jekkos** [comment]
Correct @daN4cat, otherwise Ill add this change tonight.

**Comment by objecttothis** [comment]
Yeah, you want @SteveIreland to do it since I wouldn't be able to get to it until tomorrow.

**Comment by SteveIreland** [comment]
It doesn't look like I will be able to make anything happen today but if my plans change and some time is freed up then I'll certainly give it a try.

**Comment by jekkos** [comment]
Ok I have extended the migration class as it didn't have any way of figuring out hether we are on the latest version or not.  So now the request limeout limit is set in case a migration is about to happen.

Also I have put in place a method now to check whether an install needs to upgrade. This situation can eg occur if a user upgrades all is files but is still logged in. The migration will only start once he logs out but he could be blocked doing that as we don't give any guarantee as we will have code running without the needed underlying db chnages.

So I could add a simple hook that uses this check to see if we need to logout to start migration. However I was thinking that then we'd be querying the db version table on every request, which isn't nice either.

So I left it as it was, maybe if I find a way to cache this version string then I might consider adding this simple logout hook.

**Comment by daN4cat** [comment]
I sense that we are overcomplicating the matter.

**Comment by daN4cat** [comment]
This is not a full SaaS solution which needs 99.99% high availability and upgrading while in motion.
There is a concept of log out and log in.
Probably what we should is force a logout on a pending upgrade.
Also you would upgrade during out of office hours to contain any impact.

**Comment by daN4cat** [comment]
The upgrade script is run based on the script date.
When you touch the db upgrade script make sure it has a new date so the script is Re-run.
Any error should be ignored as this is just a development experience.

Again I would keep it simple.

**Comment by objecttothis** [comment]
I agree with @daN4cat on keeping it simple.  My recommendation is to give the software administrator control over when the upgrade happens which (s)he should be doing after hours anyway.  I also agree that a forced logout/login is a good idea.

**Comment by objecttothis** [comment]
I just downloaded the latest bintray and I re-copied my latest production database over to dev and I'm noticing on the first login that the paget is taking a long time loading.  I'm guessing this is due to the attribute migration script running in the background.  This might be worthy of a different issue, but it could be helpful to give some sort of indicator that the database is being upgraded, so that users don't think that their installation is broken.  At it's simplest form it could just be a brief message that says that the database is being updated and instructions to wait until it's completed.  It could be more than that too with more detailed progress indication, but I don't know that it is necessary.

**Comment by jekkos** [comment]
@daN4cat indeed we should improve on exactly what you say, it's not more complicated as you both describe here, if a user starts an upgrade he will first copy the newer files and overwrite the old ones. From that point we should detect that an upgrade is pending, log the user out, and show a message that on next login an upgrade will happen.

If we don't logout the user he will run into issues (like I did), certainly if the leap is a couple of major versions. There's no guarantee things will keep working with a non migrated database. He will have to destroy the cookies manually or open a new private mode window. It might be a bad experience as not everyone know when the db is migrated (at least I didn't when I got to it).

the current db schema version is kept in the migrations table. In fact we need a check to see that the version of the source code is not in line with the db schema version.

**Comment by daN4cat** [comment]
What should we do with this? 3.3.0 will have lengthy database upgrades and probably just a signalling of an upgrade in progress at login would do.

**Comment by jekkos** [comment]
I'll try to wrap this up this week somewhere

**Comment by daN4cat** [comment]
Any update?

**Comment by jekkos** [comment]
This is done and merged in master

**Comment by dtomlins** [comment]
Lengthy?  That's severely understated from my view.
I'm upgrading from 2.1 - ok, the SQL migration to 3.0 wasn't terrible as I knew what was happening and could watch it, running 1 at a time.
The  sales_tax_data "update" however failed after 9 hours, and left me unable to login.  It completed almost 1/4 of it in that time.   This is something that a properly written query should summarize in minutes!
I guess I now have to write that query, as it will no longer continue to do it by itself.

This handles the 450,000 lines in 65,000 sales in 20 seconds.  What am I missing?

insert into ospos_sales_taxes SELECT sale_id, tax_type, ospos_sales_items_taxes.name, sum(quantity_purchased * item_unit_price * (100-discount_percent)/100) as sales_tax_basis, sum(item_tax_amount) as sale_tax_amount, 0 as print_sequence, ospos_sales_items_taxes.name, percent, '' as sales_tax_code, 1 as rounding FROM `ospos_sales_items` join ospos_sales_items_taxes using (sale_id, item_id, line) group by sale_id, ospos_sales_items_taxes.name, percent

Dan

**Comment by objecttothis** [comment]
Dan, your experience is real and your contribution is welcome. With that said, you are using this software for free and it's developers primarily work on this project on a voluntary basis, so please cut people some slack. @jekkos or @steveireland will need to take a look at this at their convenience and see about your proposal with the tax data migration. If it increases the speed of the migration, I don't see any reason why it wouldn't be implemented.  You can speed the process by creating a pull request with your suggested changes, then requesting reviews on the pull request by @jekkos and @steveireland, please, thank you, and all that jazz.

**Comment by dtomlins** [comment]
Thanks for your note, @objecttothis  and I certainly do understand with sincere thanks all the work done as volunteers, All of you.  
I'm attempting to do a "huge" upgrade step - from an ancient version (2.1_B) - and it has been very slow with breakage at many steps, and very slow.  Slow on large tables, yes, I know it is only done once or a few times, and for small "test" datasets it works, so performance isn't optimized there.  Modifying the structure on a million record table takes some time.  Modifying 6 fields takes slightly longer.  Doing it as 6 individual changes takes 6x as long.   Again, on a test database it's nothing.

I know that many of the changes that have happened since 2.1 are going to break much of my interfacing code also (my suppliers, purchasing, receiving and inventory reporting is separate code working with the OSPOS database tables, as well as information sharing to oscommerce/zen-cart on a periodic basis), but that can be handled.
I'll certainly share performance improvements when possible, but pull requests etc are "huh? I don't want to create a new version - just submit a bug fix!"

This is a very good piece of code, and I do applaud the authors and maintainers.  
Being able to scale to larger data does unfortunately break some of the ideals that work well with small datasets.   (8,000 customers, 50,000 active products, 1m inventory transactions)
I'll certainly submit bug/enhancement requests with suggested changes (and code) that will hopefully enhance the project.  And I'm sure some will be questions to try and figure why some changes were made too.

Dan

**Comment by objecttothis** [comment]
> I'm attempting to do a "huge" upgrade step - from an ancient version (2.1_B) - and it has been very slow with breakage at many steps, and very slow. Slow on large tables, yes, I know it is only done once or a few times, and for small "test" datasets it works, so performance isn't optimized there. Modifying the structure on a million record table takes some time. Modifying 6 fields takes slightly longer. Doing it as 6 individual changes takes 6x as long. Again, on a test database it's nothing.

I did this same upgrade a while back and with some coding changes that I had made which made it more complicated.  I completely understand your position.  From my experience, I'm glad for the results once it is done.

> I know that many of the changes that have happened since 2.1 are going to break much of my interfacing code also (my suppliers, purchasing, receiving and inventory reporting is separate code working with the OSPOS database tables, as well as information sharing to oscommerce/zen-cart on a periodic basis), but that can be handled.

The approach I take to this project is that I try to do as many of my code changes as possible inside the project so that I don't have to try to maintain updates to the code without breaking my own changes.  It has saved me a lot of time.  The only downside is that means writing code in such a way that the whole community can benefit from it.  I don't mean to say that all of your changes need to be that way, but you benefit more when more of your changes are already in the code base.

> I'll certainly share performance improvements when possible, but pull requests etc are "huh? I don't want to create a new version - just submit a bug fix!"

A pull request in Github is just submitting the bug fix or change.  It isn't creating a new version.  I only suggested it as a way to speed up the bug fix.  @jekkos or @SteveIreland will get to it, but it will go faster if you submit the code change.  All that's needed is for you to create a branch, go to the <code> tab in that branch, find the file that needs fixing, modify it (make sure you test the changes in your own environment) by clicking the pencil in the top right of the site and at the bottom clicking the "commit and create pull request" button.  In the pull request window you can request reviewers at the top right.
> 
> This is a very good piece of code, and I do applaud the authors and maintainers.
> Being able to scale to larger data does unfortunately break some of the ideals that work well with small datasets. (8,000 customers, 50,000 active products, 1m inventory transactions)
I think we should be able to get the best of both worlds in optimizing the code/migration scripts/database
> I'll certainly submit bug/enhancement requests with suggested changes (and code) that will hopefully enhance the project. And I'm sure some will be questions to try and figure why some changes were made too.
Super, that will be helpful to everyone.  Questions are welcome.
