### ISSUE TITLE
Error when change stock location permission can't open the item tap

### ISSUE THREAD

**Issue by ahmed616** [opensourcepos/opensourcepos#2251]
when add new stock location and change the items permissions and unchecked some of new stock location 
this massage appeared "You do not have permission to access the module named Items "   and can't open tap of items.

**Comment by jekkos** [comment]
This bug report is really vague. Please be more specific about the series of actions you did, what result you expect, and what behavior you encounter. Maybe add a screencast to show us what you are doing.

**Comment by jekkos** [comment]
Might be time to consider merging in this permission datamodel refactor I did a while ago.. Problem here is that permission name is sort of used as a pk. I guess there are a couple of scenarios that can cause trouble because of this.

**Comment by ahmed616** [comment]
The problem is if i unchecked **only** one stock location in item permission the i can't open the item tap although there are two other stock location selected , when open employee permission tap again i find all stock location unchecked 
![capture](https://user-images.githubusercontent.com/44599622/49214285-ff7d1480-f3ce-11e8-956c-de2503d3485e.PNG)
![capture1](https://user-images.githubusercontent.com/44599622/49214286-0015ab00-f3cf-11e8-8c7c-f3b607f5628e.PNG)

Thank you..

**Comment by SteveIreland** [comment]
I will address the issue of deselecting a stock location this weekend

**Comment by SteveIreland** [comment]
I ran through various tests of selecting and unselecting permissions to stock locations and was not able to recreate the problem.  Unselecting a location only unselected that one location..  I was even unable to  unselect all locations because of the requirement of needing to have at least one grant per module.

I tested with latest commit level of OSPOS 3.3, with version 7.2 of PHP. I saw from another issue that those were the versions you were using.

Are you using an older commit level of master branch?  If so, can you upgrade to the latest commit level of master or india-gst that is available from bintray and retest?

**Comment by SteveIreland** [comment]
Also. At this time only the India-get branch has support for mult-branch stock location names

**Comment by wesleywilian** [comment]
Hello, try to test the stock name without spaces.

**Comment by jekkos** [comment]
Isnt there a validation check to prevent you from entering stock names with underscores?
