### ISSUE TITLE
add support for brand in items

### ISSUE THREAD

**Issue by erastus** [opensourcepos/opensourcepos#2274]
### New Feature

It would be nice to add a field called a mark in the ospos_items table;
The objective would be to know what brand the article is.

**Comment by erastus** [comment]
The reports would be done by brand, as is done with the categories.

**Comment by WebShells** [comment]
@erastus isnt it somehow achievable by attributes feature? Adding new attribute named brand. Except for the report thing...

**Comment by erastus** [comment]
@WebShells  Exactly you can not by attributes, because you have to make reports. The only way would be to add a field to the database. that's why I ask for approval

**Comment by jekkos** [comment]
well you can make generic report for attributes, that would be way more flexible no?

**Comment by erastus** [comment]
@jekkos  then it would be good to delete all ospos_items fields and pass them as attributes

**Comment by erastus** [comment]
I see the field of the brand as the category.

**Comment by erastus** [comment]
@jekkos  The field for the brand is not a flexible field

**Comment by SteveIreland** [comment]
I believe that attributes works perfectly fine for reporting.  The purpose of attributes is to provide flexibility to the software so that each site can add their own little nuances for reporting and item classification.

Elements that remain as properties of the item table either control program logic or are legacy attributes that will generally be used by the vast majority of sites.

If you are able to develop your own reports then you can easily join to an attribute of brand to get the grouping and sorting by Brand.

If we're taking a vote then Item brand is NOT a feature I have a need for.

**Comment by erastus** [comment]
> well you can make generic report for attributes, that would be way more flexible no?

This would be the right thing!.

issue closed
