### ISSUE TITLE
India GST migration fails to migrate customer tax code

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#2302]
I continuously get this after upgrading a database.
A Database Error Occurred
Error Number: 1054

Unknown column 'fa.sales_tax_code' in 'where clause'

UPDATE ospos_customers AS fa SET fa.sales_tax_code_id = ( SELECT tax_code_id FROM ospos_tax_codes AS fb where fa.sales_tax_code = fb.tax_code)

Filename: C:/wamp64/www/my-master/vendor/codeigniter/framework/system/database/DB_driver.php

Line Number: 691

**Comment by jekkos** [comment]
Correct, had this issue while upgrading my master install.

**Comment by jekkos** [comment]
Maybe some parts of the migration have to be ran after 3.3 script, but others might already have been executed (a couple of table drops eg). Might have been better to split it up.

**Comment by odiea** [comment]
@jekkos did you upgrade with the current master?

**Comment by jekkos** [comment]
well yes only thing I did is pull in the latest changes, then the problem occured. Might have to take a closer look tomorrow to see why it happened.

**Comment by jekkos** [comment]
Ok had a further look into this issue as it occurs on every install I try to upgrade. I see following error
The migration script is first copying three tax tables by renaming them.

Then it is trying to set the customers sales_tax_code_id based on it's sales_tax_code, but in my database this column is gone, which then fails the query. It probably already ran the migration and is now trying to do so again because the filename was changed. I'll add a check to see if the column is still there so it that it knows it does not need to run again.

```
**Error Number: 1054

Unknown column 'fa.sales_tax_code' in 'where clause'

UPDATE ospos_customers AS fa SET fa.sales_tax_code_id = ( SELECT tax_code_id FROM ospos_tax_codes AS fb where fa.sales_tax_code = fb.tax_code)

Filename: migrations/20190129212600_indiagst.php

Line Number: 95**
```

**Comment by jekkos** [comment]
Bumping the script filename seems to have left my database in an inconsistent state. Currently I see two backup tables present, I'll move the drop statements to the down() clause so cleanup is forced in case the script failed to run properly

**Comment by jekkos** [comment]
@SteveIreland can you check if I didn't miss anything missing here?

**Comment by jekkos** [comment]
Closing this one. The fix resolved my issues.
