### ISSUE TITLE
Stock type not visible when adding item if user doesnt have access to item kits

### ISSUE THREAD

**Issue by jamrogers** [opensourcepos/opensourcepos#2349]
### Installation information

- OSPOS version is:  3.2.3
- OSPOS git commit hash is:  
- PHP version is: 7.0
- MySQL or MariaDB version is:  10.1.37-MariaDB-0+deb9u1
- OS and version is:  Raspbian 9.0 (raspberry pi)
- WebServer is: Apache/2.4.25 (Raspbian)
- Selected language is: system language
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

Issue:

In the items module when adding an item (click new item)  stock type option (stocked or non stocked) is not shown if the user doesn't have access to the item kits module.

if i add the item kits module to the users profile in the employees module then it becomes visible as does the item type option (standard or kit)

surely removing the items module from a users profile should only remove the item type option and not the stock type option when adding (or updating) items, or am i missing something?
![capture](https://user-images.githubusercontent.com/47417453/52409073-4ae92880-2acc-11e9-90f5-0e73d9cd73a7.PNG)

**Comment by SteveIreland** [comment]
Nope ... you are not missing anything.

When stock type was first introduced it was in conjunction with improvements to item_kits.

Later changes added support for a couple of other features but apparently no one noticed that the fields were still conditioned by the item kit flag.  (Certainly I didn't.)  I haven't tested in a non-kit environment in a long time.

Does anyone have a problem with me conditioning only the item kit item type option with the flag?

Should be a simple fix. (I say that tongue in cheek now because my last two "simple" fixes have been struggling for various reasons.)

**Comment by jamrogers** [comment]
Sounds good to me, I am only three days into using ospos mind :-)

**Comment by SteveIreland** [comment]
The resolution that was applied is that if the user isn't authorized to item_kits then the item type is disabled.

If the user is not authorized to item_kits then they also will not be able to assign an item type of "Amount Entry".   Hopefully that isn't an issue for anyone since "Amount Entry" is hopefully a rare configuration of the system.
