### ISSUE TITLE
Round with out Decimals

### ISSUE THREAD

**Issue by truchosky** [opensourcepos/opensourcepos#2355]
hi guys, i use ospos 3.2.3, this is not a bug, is more like a feature

I checked Rounding_mode.php but I couldn't accomplish what I am looking for.

my currency has not decimals, there are int numbers only, but i want to round anyways.

for example: 131 should be 130, 134 should be 130 too and 135 should be 140.

this can be accomplish using -1 on round function, like this: 

round( 136, -1) = 140
round (134,-1) = 130

any advise or guidance on how to procced?

greetings

**Comment by SteveIreland** [comment]
Are you asking to add -1 to the currency decimal options?

That is simple enough to add, but the big question is whether or not it is handled properly by the NumberFormatter PHP class.  I cannot find any documentation where it is supported.  Maybe someone else knows for sure.

```
function to_decimals($number, $decimals, $type=\NumberFormatter::DECIMAL)
{
	// ignore empty strings and return
	// NOTE: do not change it to empty otherwise tables will show a 0 with no decimal nor currency symbol
	if(!isset($number))
	{
		return $number;
	}

	$config = get_instance()->config;
	$fmt = new \NumberFormatter($config->item('number_locale'), $type);
	$fmt->setAttribute(\NumberFormatter::MIN_FRACTION_DIGITS, $config->item($decimals));
	$fmt->setAttribute(\NumberFormatter::MAX_FRACTION_DIGITS, $config->item($decimals));
	if(empty($config->item('thousands_separator')))
	{
		$fmt->setAttribute(\NumberFormatter::GROUPING_SEPARATOR_SYMBOL, '');
	}
	$fmt->setSymbol(\NumberFormatter::CURRENCY_SYMBOL, $config->item('currency_symbol'));

	return $fmt->format($number);
}
```

 Just out of curiosity what country requires this or is it a regional thing?

**Comment by truchosky** [comment]
this is mandatory in chile, https://www.legalchile.cl/como-funciona-la-regla-del-redondeo/

where I add that function?, on Rounding_mode.php ?

**Comment by SteveIreland** [comment]
Thanks for the link which clarified that this is a "cash rounding" application.  I'll see what it takes.

**Comment by SteveIreland** [comment]
I explored the option where I added -1 as a cash decimals option and it seems to work just fine.  Any change I make will only go to version 3.3.   Can you locate `local_config.php` and make the following change and let us know how it works out for you?  If it works for you then I'll go ahead and make the corresponding change in version 3.3.

```
            <div class="form-group form-group-sm">
				<?php echo form_label($this->lang->line('config_cash_decimals'), 'cash_decimals', array('class' => 'control-label col-xs-2')); ?>
                <div class='col-xs-2'>
					<?php echo form_dropdown('cash_decimals', array(
						'-1' => '-1',
						'0' => '0',
						'1' => '1',
						'2' => '2'
					),
						$this->config->item('cash_decimals'), array('class' => 'form-control input-sm'));
					?>
                </div>
```

**Comment by truchosky** [comment]
it worked perfect, thx you

**Comment by SteveIreland** [comment]
It appears to be working reasonably well in 3.3.  The cash rounding was primarily targeting receipts and not invoices since invoices are generally assumed to be paid at a later time.  However I know that's not always the case in all countries.

It's probably a good time to revisit cash rounding.  I'm not sure what laws are applicable if a cash deposit is applied against an invoice and the remainder of the payment is by credit but I would assume that the cash payment requirements no longer apply.

That doesn't appear to be how it was implemented a couple of years ago.  And it still doesn't look right to me, but no one has provided any feedback on this until now.  If you're interesting in working with me to iron out any problems then I'm happy to invest the time.

**Comment by daN4cat** [comment]
Fix in merged into master and it will be available in release 3.3.0 (when we manage to close it....)

**Comment by SteveIreland** [comment]
Closing this since the addition of the -1 appears to be working in the 3.3 release for cash rounding and @daN4cat has already merged it.  @truchosky if you find that there are still issues with the cash rounding please open a new issue and provide more details as to how your particular environment is configured for cash rounding.  I spent a couple of hours on this trying to look at possible holes in the logic and there are numerous possibilities (it's actually a bit complex), but the original development worked for the original requester.  Obviously something could have broken it in the 3.2 release but it seems to have been fixed in the current 3.2 master.

**Comment by jekkos** [comment]
The fact that it does not work in invoices sounds rather odd. All the calculations are done in the sale_lib functions and so just wonder why we would show anything different than in the invoice view.

**Comment by truchosky** [comment]
Tested a sale for a product sold on cash for 301.

![sale record](https://user-images.githubusercontent.com/9977546/52538098-3c5d7400-2d4d-11e9-80e3-0e481610d454.jpg)

![sale view](https://user-images.githubusercontent.com/9977546/52538099-41222800-2d4d-11e9-8428-e142914e4535.jpg)
