### ISSUE TITLE
This is only a test to show new system info

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#2382]
OSPOS Installation Info: 3.3.0 - dev
Language Code: en-US

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Settings:
.Browser: .Chrome
.Server Software: Apache/2.4.33 (Win64) OpenSSL/1.1.0g PHP/7.1.16
.PHP Version: 7.1.16 
.Server Port: 80
.DB Version: mysqlnd 5.0.12-dev - 20150407 - $Id: 38fea24f2847fa7519001be390c98ae0acafe387 $
.OS: Windows NT PAVILION23 10.0 build 17134 (Windows 10) AMD64

File Permissions:
» [application/logs:] - 0777 | Writable ✓ 
» [public/uploads:] - 0777 | Writable ✓ 
» [public/uploads/item_pics:] - 0777 | Writable ✓ 
» [import_items.csv:] - 0666 | Writable ✓ 
» [import_customers.csv:] - 0666 | Writable ✓

**Comment by WebShells** [comment]
Ill fix the view 🤦‍♂️😂

**Comment by WebShells** [comment]
@odeia it looks fine from here... No? 
![img_20190228_013330](https://user-images.githubusercontent.com/26513147/53530570-ea607080-3af8-11e9-8828-f0d1f61c925d.jpg)

**Comment by odiea** [comment]
Yes it looks great in the system info tab

**Comment by odiea** [comment]
Below is the screen shot of what I copied and pasted.
![2019-02-27 16_40_57-odies test _ powered by ospos 3 3 0](https://user-images.githubusercontent.com/10962177/53530874-a0529d00-3aae-11e9-8e54-078380391abd.png)

**Comment by odiea** [comment]
Could it be just github formatting?

**Comment by WebShells** [comment]
Will check it out... Still few changes and fixes to be done here (Y)

**Comment by objecttothis** [comment]
Just a few thoughts:
In the File's Permissions section- 
- File's Permissions should probably be "File Permissions" in English
- Application/logs should be "application/logs" to follow the capitalization of the actual folders.
- Public/uploads should be "public/uploads" for the same reason.
- I believe you want to add a check for public/uploads/item_pics as well since that should be either 644 or 664 depending on who needs write access to them.
- I don't believe we should change the permissions of the CSV files or any other file but instead just report them as writeable if they need to be or NOT writeable if they aren't but should be.
- I like the formatting you used for the page, but it's also not the formatting of the issue template.  I think we should do one of a couple different things.  One is that we could potentially have a link to copy the data to the clipboard in the format we want it in for the issue reporting but leave it on the screen as is.  Another option is that we could change the format of our template to match this formatting.  A third option is that we could change the formatting of this page to match the formatting of our issue template. 
- Whichever we choose we need to keep in mind easy of copying.  Does a pasted page like this appear correctly in the issue template or does it mess up the formatting and make it unreadable?  The second is with whatever we do we should figure out a way to either be consistent between the issue reporting and this page in the formatting or allow the option of copying (via link) the data we want in the format we want for the issue template.

**Comment by objecttothis** [comment]
Also, I haven't tested it, but both 664 and 644 should be considered writeable.

**Comment by WebShells** [comment]
@objecttothis the check i did above is based on is_writable built-in php function, so here am not checking specific permissions...
For the template i agree with you about the format, but i guess the way they are listed are the best to categorize based on user settings, installation settings, and server info... 
Maybe we should re arrange our issue template on git?
As for the names of folders you're totally right... 
Will update the code at night and we see if more things should be done 👍
Thanks for your time!

**Comment by objecttothis** [comment]
OK, I see.  I was interpreting the line "CSV permissions were set to 0664" to mean that the code was changing the permissions.  Perhaps then we could change that line to be consistent with the lines above it or if it's redundant than get rid of it altogether.  I would recommend two things regarding formatting and content.  In the File Permission section I would include the actual permission value in response.  So instead of "Writeable (check)" or "NOT writeable (x)" I would place the permission, so it read something like "[File]: 0644 Writeable (check)" or something to that effect.  The second change I would recommend, but not at the expense of ability to copy is separating the Item: and result using DIV to have all the results vertically aligned.   I think that would make it easier to read, although, not mandatory.

Regarding the issue template, I don't feel strongly about the current one, so I'm all for changing it as well to match the end product of this change.  I think I'll defer to @jekkos and @daN4cat though.

**Comment by jekkos** [comment]
Ok still quite a couple of remarks / thoughts here we should align on. I'll try to make a checklist to see what remains to be done.

**Comment by mhanis88** [comment]
When version 3.3.0 will be release?

**Comment by daN4cat** [comment]
Hopefully soon!

**Comment by mhanis88** [comment]
Please make it fast. This surely will be my life saver! Thanks

**Comment by WebShells** [comment]
Sorry for the delay team, will check this out tonight...

**Comment by WebShells** [comment]
Most of the points are solved now in #2404, will submit a final update today for copying table...

**Comment by WebShells** [comment]
OSPOS Installation Info: 3.3.0 - $Id $
Language Code: en-US

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Settings:
.Browser: Chrome
.Server Software: Apache/2.4.23 (Win64) PHP/5.6.25
.PHP Version: 5.6.25 
.Server Port: 8080
.DB Version: mysqlnd 5.0.11-dev - 20120503 - $Id: 76b08b24596e12d4553bd41fc93cccd5bac2fe7a $
.OS: Windows NT 

File Permissions:
» [application/logs:] - 0777 | Writable ✓ 
» [public/uploads:] - 0777 | Writable ✓ 
» [public/uploads/item_pics:] - 0777 | Writable ✓ 
» [import_items.csv:] - 0444 | Not Writable ✗ 
» [import_customers.csv:] - 0444 | Not Writable ✗ 

That's how it looks like now...

**Comment by WebShells** [comment]
Merged into master.
