### ISSUE TITLE
Multiple Packages per Item - characteristic

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#2421]
I do not know if this is a problem or I'm using it incorrectly

This feature, Multiple Packages per Item
![Screenshot_2019-04-09 Open Source Point of Sale Powered by OSPOS 3 3 0](https://user-images.githubusercontent.com/29256343/55830232-bf8d1300-5acd-11e9-841a-ce3e76391469.png)

Allows you to add another item and save it successfully.
![Screenshot_2019-04-09 Open Source Point of Sale Powered by OSPOS 3 3 0(2)](https://user-images.githubusercontent.com/29256343/55830429-20b4e680-5ace-11e9-85db-9f78aa59ae8d.png)
but after what? What is the purpose.?

**Comment by odiea** [comment]
https://github.com/opensourcepos/opensourcepos/wiki/Items

**Comment by andriux1990** [comment]
So this feature does not work at the moment, I understand.
Thank you

**Comment by SteveIreland** [comment]
Since you didn't point out a particular problem with this feature I will assume it is working as designed.

However, if you can be more specific about what you think is not working then I'll be happy to look into addressing the issue.

In summary, the feature is designed to provide a way to track and sell stock  based on how an item is packaged.  If that's not what you need then don't arbitrarily declare that the feature isn't working ... it simply doesn't fit your requirements.
