### ISSUE TITLE
Taxes configurability

### ISSUE THREAD

**Issue by daN4cat** [opensourcepos/opensourcepos#2465]
@SteveIreland ,

I've checked the configurability of the Taxes (the feature you added) and I'm not sure it's working as expected:
 - [x] if you rename a code it adds it as a new entry
 - [x] if you try to remove the old entry it comes back
 - [ ] you can delete the first row, and if you do there is no intuitive means to add it again.

I'm not a user of this feature, but maybe it's worth checking the type of user experience is currently implemented and see if something can be improved.

**Comment by jekkos** [comment]
Hmm I feel we should have had a more solid and consistent approach on all this CRUD stuff. But ok moved to 3.4 so I hope someone will find the courage to tackle this at one point in the future.

**Comment by SteveIreland** [comment]
I'll take a look at this issue this weekend to see if I can replicate them.  If so I'll go ahead and fix them and you can decide what release it should go in.

**Comment by SteveIreland** [comment]
"if you rename a code it adds it as a new entry"

I could not recreate that this issue.  Renaming a code consistently works as expected in my tests.  I'll need to know exactly what sequence of events led to this issue.

**Comment by SteveIreland** [comment]
"if you try to remove the old entry it comes back"

Again, I could not recreate this issue.  Now the behavior does "appear" to be there if you don't click on the Submit button before navigating away from the panel.  Deleting a row doesn't actually delete the row until the Submit button is pressed.

**Comment by SteveIreland** [comment]
"you can delete the first row, and if you do there is no intuitive means to add it again."

I remember this oddity.  Since the submit button doesn't reload the page the user is definitely at a stand still until they navigate away and return back to the panel where a new line is available for entry.

I think I rationalized not resolving this issue because it makes absolutely no sense for anyone to delete the last record unless they are NOT planning to add another.

Either way, I do not believe this is an issue that needs to be addressed for the 3.3 release.

The better solution is as @jekkos suggested is to change the way all reference tables are maintained.  I'm not a big fan of the +/- approach but since that was the way other tables were maintained I thought it was going to be expected that I maintain the same approach for reference tax tables.

**Comment by daN4cat** [comment]
@SteveIreland counterchecked and the two first problems where in the end due to a duplication of tax code in my database. One visible and other deleted, which caused all the behaviour I noticed.

The third one stays, the simple is like in configuration / stock, just remove the - on the first line and that will do.

**Comment by SteveIreland** [comment]
I don't think the last stock code should ever be deleted which would be why the minus sign is not on the first row.  But if someone accidentally (or intentionally adds a tax code) then wants to delete it I do want them to be able to delete it and empty the table.

How did the duplicate tax code end up in your database?  Is there a problem in the migration?

**Comment by daN4cat** [comment]
I can't remember, it might be that they were preexisting some migration and got like that? I can't say for sure and it's fine.

I close this issue.
