### ISSUE TITLE
Apache serving blank page, no login, no nothing

### ISSUE THREAD

**Issue by Saiuke** [opensourcepos/opensourcepos#2469]
- [X] Reporting an issue of an unmodified OSPOS installation
- [X] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [X] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [X] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [X] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [X] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.1
- OSPOS git commit hash is:
- PHP version is: 5.6
- MySQL or MariaDB version is: 
- OS and version is: Ubuntu 18.04
- WebServer is: Apache
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

Question

So, I'm not very familiarized with the Ubuntu enviroment, normally I can handle it until some point. 

I've installed Apache, MySQL, PHP 5.6 and all required mods. I can run an usual PHP page in the server and can run queries and all. But, after getting some trouble to make the server read the .htaccess file and redirect to /public I came to a stall. I have a blank page. No errors, no login, no nothing. I use OSPOS on Windows under Wamp and have installed it more than 10 times. Had have some errors and stuff before. But, in this case is a old machine that cannot run a more recent version of Windows so... I'm pretty sure that the problem ins't with OSPOS. I just need some clue about what I've overlooked. Thank's for your time and congrats for the amazing job done so far.

PS - I've not included some informations about the versions I'm working with because I don't have the computer here. As far as I know, everything is running up to date except for PHP, I'm running PHP 5.6.

**Comment by daN4cat** [comment]
Have you searched past issues around this topic?

**Comment by andriux1990** [comment]
It may be that you have not installed all the php modules required by ospos.
Try with this
sudo apt install php libapache2-mod-php php-mysql
When this happens to me with this command I solve it

**Comment by Saiuke** [comment]
I'll check the modules again and post here.

**Comment by Tbwan** [comment]
I had issues getting started as well. Here are my condensed noted of everything I ran/did in Ubuntu 18.04.2 (desktop version)

LAMP installation:
-in terminal:
sudo apt install apache2
sudo apt install mysql-server
sudo apt install php7.2 libapache2-mod-php7.2 php-mysql
sudo apt install php-curl php-json php-cgi

-Tested “localhost” in firefox to ensure web page opened properly

-phpmyadmin install:
-in terminal:
-sudo apt update
-sudo apt install phpmyadmin php-mbstring php-gettext
-follow the prompts
-sudo phpenmod mb string

-add the following to /etc/apache2/apache2.conf:
Include /etc/phpmyadmin/apache.conf

-in terminal:
-sudo systemctl restart apache2

-In terminal (Enable connectivity between mysql and phpmyadmin users):

-sudo mysql
-ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password'; -FLUSH PRIVILEGES;

-Install ospos using internet guides: https://github.com/opensourcepos/opensourcepos/wiki/Getting-Started-installations#local-install
-At this point I was still getting a blank page, and installed current versions of php-bcmath, and php-intl.
-restarted apache2 server

Login page appeared, but gave a 404 error on logging in. fixed with the following:
-in terminal:
-sudo a2enmod rewrite
-edit /etc/apache2/apache2.conf and change “AllowOverride None” to “AllowOverride All” as seen below:
<Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
</Directory>
-in terminal:
-restart apache2 server

Login worked after this.

**Comment by odiea** [comment]
Thank you for the thorough explanation. Hope it will help others out.

**Comment by Saiuke** [comment]
I've done pretty much all of it. But I must have done something wrong. I'll uninstall everything and try again.
And, yeah, I've searched about it in the past issues. The only one that has a similar problem was told to search past issued and the topic was closed.

**Comment by Saiuke** [comment]
I want to kiss you all! I was feeling quite stupid not being able to do it. I'm not an expert as you but this is not rocket science and I've done things like this before.

Anyway, @Tbwan thanks for the step-by-step instructions, it was pretty much what I gathered before but it helped somehow. For future reference, this is basic, hut, who knows who might read it. It's important to make sure you have write and read privileges on the var/www/html folder.

**Comment by daN4cat** [comment]
@Saiuke good news and yes read and write privileges are required but not for all the folders. The write should be only for the upload part and folder containing the config.php because an encryption key is generated the first time.

This is something we need to bear in mind and add it to the FAQ because other issues reported in the past might have been due to this point.

**Comment by daN4cat** [comment]
@Saiuke good news and yes read and write privileges are required but not for all the folders. The write should be only for the upload part and folder containing the config.php because an encryption key is generated the first time.

This is something we need to bear in mind and add it to the FAQ because other issues reported in the past might have been due to this point.

**Comment by daN4cat** [comment]
And now there is a case talking about this issue :-)

**Comment by Saiuke** [comment]
I did a system upgrade and got a blank page again. The best part is that I just noticed it after handing back the computer to the client. So, here we go again... Maybe one of the mods is off? What could have happened? I mean, it was just a apt-get upgrade. Any clues? I'll take the computer back soon and I plan to just uninstall and install everything again, to make sure.

**Comment by dyhe83** [comment]
Same problem occurred in Ubuntu 16.04.
After install **php-bcmath** module, it solved.
```sh
sudo apt install php-bcmath
```
![image](https://user-images.githubusercontent.com/32974708/63221033-5b8a0200-c1c5-11e9-8114-1ea18d5f949d.png)
