### ISSUE TITLE
Is this footer acceptable?

### ISSUE THREAD

**Issue by asakpke** [opensourcepos/opensourcepos#2474]
### Question

I'm going to install OSPOS (v3) on some of my clients system. I'm thinking to use this modified footer as suggested in [licence file](https://github.com/opensourcepos/opensourcepos/blob/master/LICENSE)
`Open Source Point Of Sale 3.2.3 - <a href="https://github.com/jekkos/opensourcepos">4f5ad57</a> Powered by CompanyName`
Open Source Point Of Sale 3.2.3 - <a href="https://github.com/jekkos/opensourcepos">4f5ad57</a> Powered by CompanyName

This all seems OK to me but I want to be sure & I don't want to violate license. So I have few questions. Please guide me.
 
Should I use website URL on following text instead of just hash?

- Open Source Point Of Sale
- 3.2.3
- Open Source Point Of Sale 3.2.3 - 4f5ad57

Or maybe add the word website after hash and link up?

Also please suggest is this wording acceptable along with the footer? Or I should use some other wording to include my company name?

- Powered by CompanyName
- Installed by CompanyName

**Comment by daN4cat** [comment]
I'm afraid it's not allowed by the license but let's collect a bit of different views here since many more contributed substantially and might have a different view.

And thank you for asking this question, a sign of respect. Well done!

**Comment by objecttothis** [comment]
Per the license
> Footer signatures "You are using Open Source Point Of Sale" and/or "Open Source Point Of Sale"
with version, hash and URL link to the original distribution of the code MUST BE RETAINED, 
MUST BE VISIBLE IN EVERY PAGE and CANNOT BE MODIFIED.

With the above you need to have the "Open Source Point of Sale", version number, hash and link to the original distribution.

The term Powered by indicates who the developers of the software are which would need to be "opensourcepos" and that itself should be a link to www.opensourcepos.org or the github page directly.  If you are trying to indicate your company who installed it, then you can put installed by and then your company name, but you would still need a link to the original distribution in the footer.

These are my opinions and they may be overridden by @jekkos or @daN4cat since they are senior me here.

**Comment by objecttothis** [comment]
Sorry, I just looked at the OP.  You do have the link in there, but it's on the hash.  I think the link should be on "Open Source Point of Sale" because being on the hash is too obscure.  The only thing I have a problem with is that Powered by, if included, cannot by your company name because it implies you are the developer.  But if you put installed by and your company name and the link around Open Source Point of Sale then I have no problems.

**Comment by asakpke** [comment]
@daN4cat @objecttothis Thank you for the replies.

It seems that following footer is more suitable
`<a href="https://github.com/jekkos/opensourcepos">Open Source Point Of Sale</a> 3.2.3 - 4f5ad57 Installed by <a href="CompanyURL">CompanyName</a>`
<a href="https://github.com/jekkos/opensourcepos">Open Source Point Of Sale</a> 3.2.3 - 4f5ad57 Installed by <a href="CompanyURL">CompanyName</a>

I'm going to use this footer on [OSPOS demo](http://pos.esite.pk/public/) at my website [eSite.pk](http://esite.pk/).
