### ISSUE TITLE
indicate which items are taxable/taxed on the receipt

### ISSUE THREAD

**Issue by klisle** [opensourcepos/opensourcepos#2523]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.2.0

### Issue / Bug  / Question / New Feature

A client asked me about indicating the taxed items on the receipt. I hadn't considered that before but looking at other receipts, some have a 'T' beside taxed items, others have an additional column for indicating the percentage tax to be applied to the item beside it eg. 16.5% or 0% or whatever depending on the specific item. Any ideas would be appreciated.

**Comment by SteveIreland** [comment]
I would typically follow the normal convention used in your client’s country so that the customers aren’t always questioning it

**Comment by klisle** [comment]
> I would typically follow the normal convention used in your client’s country so that the customers aren’t always questioning it

There is no requirement to specifically indicate taxed/taxable items in my country but many merchants here, especially supermarkets (because they sometimes don't tax meats) indicate the items that attract a tax. I know some software have that feature, I wanted to know if that was something that was ever imagined or if there was any way to achieve it.

**Comment by andriux1990** [comment]
I did the tests again and the same thing happened to me
![Screenshot_2019-08-30 Open Source Point of Sale Powered by OSPOS 3 3 0](https://user-images.githubusercontent.com/29256343/64037224-5193c780-cb12-11e9-8c86-01e663536f86.png)
in the versions before this one, if you show me the detailed reports.
we would have to compare the code and see what the changes were

And I have no attributes

**Comment by SteveIreland** [comment]
It is certainly doable by tweaking the views and if necessary the controller.  

Also, I was looking at an up-scale grocery store receipt here (something my daughter goes to since I do low-scale) and saw that they were flagging taxable items with a "T" and non-taxable items with an "F";  That's not the case with all receipts so it must be "seller's choice" here too.

**Comment by klisle** [comment]
> It is certainly doable by tweaking the views and if necessary the controller.
> 
> Also, I was looking at an up-scale grocery store receipt here (something my daughter goes to since I do low-scale) and saw that they were flagging taxable items with a "T" and non-taxable items with an "F"; That's not the case with all receipts so it must be "seller's choice" here too.

I see. It seems to depend on the software and how customizable it is. I am not a programmer, just a lowly sys eng. As such I am not familiar with how to tweak the views. It is important to our client so I am exploring what the options are and how easy they would be to implement.

**Comment by SteveIreland** [comment]
When you make a decision as to how you want it rendered on the receipt just let me know and I'll  free up some time to mock up the changes to the view.   Since all of the tax info is available in the controller I expect that what you want can be accomplished with a simple change to the view and I will provide a code snippet that will show you what needs to be changed.

**Comment by klisle** [comment]
> When you make a decision as to how you want it rendered on the receipt just let me know and I'll free up some time to mock up the changes to the view. Since all of the tax info is available in the controller I expect that what you want can be accomplished with a simple change to the view and I will provide a code snippet that will show you what needs to be changed.

Thanks for the response. What will be required is just to indicate the taxable item with a 'T'. Indicating non-taxable items id not in the client's requirements, nor have I ever seen it done. Let me know what will need to be done.

**Comment by SteveIreland** [comment]
The code for 3.2.0 related to calculating taxes is significantly different than the current 3.3 work.

So I wanted to confirm that the release you need to change is actually 3.2.0 and not some other version.

Also, the view does NOT have direct access to the info needed to accomplish the desired task, so it will be necessary to modify the controller to provide that info.  The exact change to be made is determined by the version of the software.

**Comment by klisle** [comment]
> The code for 3.2.0 related to calculating taxes is significantly different than the current 3.3 work.
> 
> So I wanted to confirm that the release you need to change is actually 3.2.0 and not some other version.
> 
> Also, the view does NOT have direct access to the info needed to accomplish the desired task, so it will be necessary to modify the controller to provide that info. The exact change to be made is determined by the version of the software.

I see, this complicates things a bit because I want to upgrade to 3.3.0 when it is released officially but there is an existing issue I have regarding duplicates in 3.2.0 https://github.com/opensourcepos/opensourcepos/issues/2521 . Since the fix is not the same from version to version, I will need to make the database changes to "delete" the duplicates as discussed in the aforementioned issue and upgrade to 3.3.0. so I can apply your code changes.

**Comment by SteveIreland** [comment]
Okay, then I'll try to put together an example for 3.3.0 this weekend and then you can decide when to apply the changes.  I think I can be a bit more efficient with the 3.3.0 version.

**Comment by SteveIreland** [comment]
Here it is ... I've tested it so I know it works for 3.3.0

The line numbers are approximations since as you add lines the line numbers change.

I've tried to identify lines to be commented out, changed, or added with the character text `// <==` so look for those. 

The first change is to `receipt_default.php` (the section of code starts around line 54).  You are going to add a new column on the far right that has an empty header cell.  The column will display the contents of a new field named `taxed_flag` that is populated with a `T` if there is a tax amount greater than zero that is attributed to that item. You will just be adding two lines of code to this file.

```
	<table id="receipt_items">
		<tr>
			<th style="width:40%;"><?php echo $this->lang->line('sales_description_abbrv'); ?></th>
			<th style="width:20%;"><?php echo $this->lang->line('sales_price'); ?></th>
			<th style="width:20%;"><?php echo $this->lang->line('sales_quantity'); ?></th>
			<th style="width:20%;" class="total-value"><?php echo $this->lang->line('sales_total'); ?></th>
			<th style="width:20%;"></th>    //  <== ADD THIS
		</tr>
		<?php
		foreach($cart as $line=>$item)
		{
			if($item['print_option'] == PRINT_YES)
			{
			?>
				<tr>
					<td><?php echo ucfirst($item['name'] . ' ' . $item['attribute_values']); ?></td>
					<td><?php echo to_currency($item['price']); ?></td>
					<td><?php echo to_quantity_decimals($item['quantity']); ?></td>
					<td class="total-value"><?php echo to_currency($item[($this->config->item('receipt_show_total_discount') ? 'total' : 'discounted_total')]); ?></td>
					<td><?php echo $item['taxed_flag'] ?></td>   //  <== ADD THIS
				</tr>
```

The next change is to the Sales.php controller.  This actually surprised me because I thought I had cleaned up this issue a long time ago.  But there is actually a piece of code in `Sales.php` that I believe to be unnecessary and if you leave it in then the `taxed_flag` will be dropped from the `$cart` array. You will need to comment it out or delete it.  It is line 807 in `Sales.php`.
The line of code a few lines up that includes the call to `sale_lib->sort_and_filter_cart` already performs what this function does.

```
			if($this->sale_lib->is_return_mode())
			{
				$sale_type = SALE_TYPE_RETURN;
			}
			else
			{
				$sale_type = SALE_TYPE_POS;
			}

			$data['sale_id_num'] = $this->Sale->save($sale_id, $data['sale_status'], $data['cart'], $customer_id, $employee_id, $data['comments'], $invoice_number, $work_order_number, $quote_number, $sale_type, $data['payments'], $data['dinner_table'], $tax_details);

			$data['sale_id'] = 'POS ' . $data['sale_id_num'];

			$data['cart'] = $this->sale_lib->sort_and_filter_cart($data['cart']);
			$data = $this->xss_clean($data);

			if($data['sale_id_num'] == -1)
			{
				$data['error_message'] = $this->lang->line('sales_transaction_failed');
			}
			else
			{
				$data['barcode'] = $this->barcode_lib->generate_receipt_barcode($data['sale_id']);

				// Reload (sorted) and filter the cart line items for printing purposes
//				$data['cart'] = $this->get_filtered($this->sale_lib->get_cart_reordered($data['sale_id_num']));   // <== COMMENT OUT THIS LINE OF CODE

				$this->load->view('sales/receipt', $data);
				$this->sale_lib->clear_all();
			}
```

The final changes are made to the `Tax_lib.php` library program.  This is where the value for the `taxed_flag` field is set.

At around line 58 we are going to change the `$cart` variable to be passed in as a reference.  This is accomplished by prefixing the variable with an ampersand.  This is needed in order to be able to make our changes to the `$cart` variable visible to the Sales controller.

```
public function get_taxes(&$cart)  // <== ADD AMPERSAND TO THIS LINE
```
At around line 71 we are going to insert a new line that initializes a new variable named `$taxed` to `FALSE`.  

```
		// Charge sales tax if customer is not selected (walk-in) or customer is flagged as taxable
		if($customer_id == -1 || $customer_info->taxable)
		{
			foreach($cart as $line => $item)
			{
				$taxed = FALSE;   // <== INSERT THIS LINE

				if(!($this->CI->config->item('use_destination_based_tax')))
				{
					// Start of current Base System tax calculations
```  
Around line 103 insert a line that sets the `$taxed` variable to `TRUE`.
```
						if($tax_amount <> 0)
						{
							$tax_group_sequence++;
							$this->update_taxes($taxes, $tax_type, $tax['name'], $tax['percent'], $tax_basis, $tax_amount, $tax_group_sequence, Rounding_mode::HALF_UP, -1, $tax['name']);
							$tax_group_sequence += 1;
							$taxed = TRUE;    // <==  INSERT THIS LINE
						}
```
Around line 135 locate the call to `apply_destination_tax.  You will modify that function later to return a value to `$taxed`, but here we simply want to grab it.  Also you will need to to add an "if then else" segment to set and add `taxed_flag` to either `T` or blank depending on the value of `$taxed` .

Both of the changes are shown in the example below.

```
				else
				{
					// Start of destination based tax calculations

					if ($item['tax_category_id'] == NULL)
					{
						$item['tax_category_id'] = $this->CI->config->config['default_tax_category'];
					}
					$tax_category = '';
					$tax_rate = '';
					$rounding_code = Rounding_mode::HALF_UP;
					$tax_group_sequence = 0;
					$tax_code = '';
// THE FOLLOWING LINE OF CODE WAS CHANGED TO POPULATE $taxed
					$taxed = $this->apply_destination_tax($item, $customer_info->city, $customer_info->state, $customer_info->sales_tax_code_id, $register_mode, 0, $taxes, $item_taxes, $item['line']);   // <== Change this line of code to prefix it with "$taxed = "
				}

// START OF ADDED LINES
				if($taxed)
				{
					$cart[$line]['taxed_flag'] = 'T';
				}
				else
				{
					$cart[$line]['taxed_flag'] = ' ';
				}
// END OF ADDED LINES
			}
			$this->round_taxes($taxes);
```
And the changes needed to `apply_destination_tax` are as follows.

First insert a line around line 306 as shown below to initialized a `$taxed` variable.

```
	public function apply_destination_tax(&$item, $city, $state, $sales_tax_code_id, $register_mode, $sale_id, &$taxes, &$item_taxes, $line)
	{
		$taxed = FALSE;  //<== ADD THIS LINE

		$tax_code_id = $this->get_applicable_tax_code($register_mode, $city, $state, $sales_tax_code_id);
```
Then around line 350 add a line to set the $taxed variable to TRUE.
```
				if($tax_amount != 0)
				{
					$taxed = TRUE;  // <== ADD THIS LINE
					$this->update_taxes($taxes, $tax_type, $tax['tax_group'], $tax_rate, $tax_basis, $tax_amount, $tax['tax_group_sequence'], $rounding_code, $sale_id, $tax['tax_group'], $tax_code_id, $tax['rate_jurisdiction_id'], $item['tax_category_id']);
				}
```
And finally we are going to return the value of `$taxed` to the calling program.  The following segment of code should be found around line 370 and you will need to change the `return` statement to return the `$taxed` variable.

```
				$item_taxes[] = $item_taxes_detail;
			}
			return $taxed;  //<== CHANGE THIS LINE
		}
		else
		{
			return $taxed;  //<== CHANGE THIS LINE
		}
```

Good luck applying these changes.

**Comment by SteveIreland** [comment]
To make this something I would submit as a pull request would require quite a bit more effort.  Since I didn't know your tax configuration I made it generic so that it would work for both destination based taxing as well as the standard taxing configuration - so that added a few more lines of code to add/change.

**Comment by odiea** [comment]
Looks good so far. Thanks

Desc. | Price | Quantity | Total |  
-- | -- | -- | -- | --
Coke \| Each Red, New, Sm, Blue dog | $0.83 | 1.0 | $0.83 | T
0 |  
Compaq Computer \| Each Red, New, Sm, description | $55.99 | 1.0 | $55.99 | T
0 |  
30000 Mile service \| Each | $375.00 | 1.0 | $375.00 |  
Replace needed parts as necess

**Comment by SteveIreland** [comment]
@odiea  Thank you for checking it out.  

I wasn't expecting that.   Is this something that you also would like to see in OSPOS?  

If there is some interest then there are some other changes I believe I would need to include:

1. Make it a configurable option. 
1. Make the "T" language dependent. 
1. Add the taxable flag to the following:
    1. receipt_email.php
    1. invoice.php
    1. invoice_email.php
    1. tax_invoice.php

**Comment by odiea** [comment]
I think it is something that would benefit other users. I am just a tester and this looked like a good addition to me.

**Comment by SteveIreland** [comment]
At my income producing job I essentially have my own QA person who I refer to as “The Decider” because I do whatever she tells me to do.

So if you think it would be a popular feature then I will add it to my “to do” list for 3.4

**Comment by mckaygerhard** [comment]
i really need this too! please make the pull request and merge it! some countries have special setting to sell things

**Comment by klisle** [comment]
@SteveIreland Hey, thanks a lot for your help with this. I really do not want you to have to duplicate your work but as you might have noticed I am having an issue deploying 3.3.0. Until it is officially released, can you possibly provide the necessary changes to get the same feature for 3.2.3? Since 3.2.3 is stable and already something I have gotten working.

**Comment by SteveIreland** [comment]
I took a quick glance at 3.2.3 and it looked like the changes would be much more complex.  I'm afraid that I don't have the free time to chase it down anytime soon.

**Comment by daN4cat** [comment]
Something to do with the database upgrade?

**Comment by odiea** [comment]
It has not been committed yet to the current version. It is something you will have to do yourself.

**Comment by SteveIreland** [comment]
I'll start it this week.

**Comment by klisle** [comment]
> It has not been committed yet to the current version. It is something you will have to do yourself.

what do you mean? I am saying that pointing the modified site to an existing 3.2.0 database with items ,yields different results from pointing the same modified site to a new database. The modified site shows the 'T' when it is a new installation but does not show the 'T' when using an existing database previously deployed in a 3.2.0 environment.

**Comment by odiea** [comment]
I misunderstood what this issue was. Thanks

**Comment by klisle** [comment]
even if I do the installation to a new db, dump the 3.2.0 database and then import it to the new db. The 'T' shows when I do the clean install but stops showing after I import the 3.2.0 database into that new database.

**Comment by SteveIreland** [comment]
Are you saying that new sales no longer reflect the "T" after an upgrade or just that when you go to reprint a sales receipt for a migrated sale that the "T" isn't appearing?

That sounds like there might be an issue with the sales migration but before we raise that flag I'll run through a migration of a database I have in order to see if I can replicate the issue.  It's not a pure 3.2 upgrade but pretty close.

I have the changes in place for this request and have been testing them.  So far it appears to be working as expected.

**Comment by klisle** [comment]
The "T" is no longer reflected after an upgrade. It is reflected on a fresh
install.

**Comment by SteveIreland** [comment]
I was able to replicate the issue you reported with my older database.  With my database I use destination based taxing and after the migration there is a final step that needs to be done in configuration which is set the default tax category, default tax code, and default tax jurisdiction.

What flavor of taxing are you using so that I can do a bit more targeted testing?

**Comment by SteveIreland** [comment]
Pull request #2579 addresses this issue (and has been merged).

**Comment by SteveIreland** [comment]
Now that it's been merged I'll redo the tests and run the suggested 3.2 extract, build some data, then upgrade to latest master.   I'll use the non-destination based tax configuration to see if I can replicate the failure.

**Comment by klisle** [comment]
Thanks for your assistance. The client is not using destination based tax.
They appear to add the tax to each item as they add them.

Regards,
Kanhai

**Comment by daN4cat** [comment]
@klisle are we here trying to fix a problem of your customer? If this is not a generic OSPOS issue we should not try to fix others people custom use and problems for free.

**Comment by klisle** [comment]
The issue is that when I made the code modifications suggested, the
expected result works on a clean deployment but does not work when
upgrading an existing deployment. I'm just trying to find out why, and how
we can get it to work as intended in an upgraded environment. I do
understand that everyone's time is valuable which is why it is frustrating
for us all when things we thought were fixed and out of the way do not work
the way we expect.

**Comment by odiea** [comment]
I just did an upgrade and it was not showing. I had to enable it in config receipt and it worked. Thanks @SteveIreland

**Comment by SteveIreland** [comment]
Yeah, I should have mentioned the requirement to enable it via receipt configuration.  :-)

Sorry.

**Comment by SteveIreland** [comment]
I just ran the test that @klisle suggested using the system's default tax configuration (but NOT tax included).

The steps followed are:

* Installed version 3.2, added some sales transactions (some taxable, some not).

* Upgraded to version 3.3 and set the receipt configuration to show the tax indicator.

* Reprinted the receipts from Daily Sales and the tax indicator was displayed.

* Added a new sale and the tax indicator was displayed.

So I'm going to close this as complete.
