### ISSUE TITLE
Question about the taxes section and first data entry row is missing "in box" labels for Cascade and Seq.

### ISSUE THREAD

**Issue by wd-code** [opensourcepos/opensourcepos#2566]
I might be dumb, but in taxes section I dont know what are these inputs means :

![image](https://user-images.githubusercontent.com/6681481/66148264-c45ff900-e610-11e9-9f8d-cb9d4130baa2.png)

There one input in the Tax Categories too.

Is that normal if I dont understand that here in France, is it only for the USA ? Or it missing an explanation ?

**Comment by SteveIreland** [comment]
No dumb about it.  You found a minor bug.

If you click on the plus symbol the next row contains a description for the two fields.  That's a bug I hadn't yet noticed and no one else has pointed out.  So I appreciate your help in identifying it.  I'll add it to my list of changes to make.

The first 0 is the Sequence field and the second is the Cascade field.

I'm not familiar with taxes in France so I don't know if there is an application there for destination based taxes.  The Tax module was original developed for USA, but then it was significantly rewritten to be usable for India taxes.

At this point it's pretty flexible so I'm not expecting a lot of future changes but I'm happy to work with someone if they identify some improvements or corrections that need to be made.  Not much feedback has been received so I don't even know if anyone is using it.

**Comment by SteveIreland** [comment]
I thought I should add a comment about the Cascade field.  There is a possibility that tax collected by a tax jurisdiction is based on the sales amount plus another jurisdictions taxes. The cascade field is intended to handle that scenario.  I definitely don't believe anyone is using this feature because I'm pretty sure that I would be asked to fix something about it.  

However, I should point out that I've only seen an implementation of cascaded taxes used in internal taxes in the USA, but I thought I'd add the capability to destination based sales taxes to provide a bit more flexibility even if no one ever uses it.

**Comment by wd-code** [comment]
Happy to help ^^
Actually I found it when I was translating the Taxes section in weblate. I always search in the demo to see in context the string to translate (espacially for tax where the translation is really tough in French).
I might found other minor bug here and there in the translation process.

**Comment by daN4cat** [comment]
Fix in master, @wd-code please test and confirm it's fixed.

**Comment by wd-code** [comment]
I use the last build from bintray (I dont know if it's the good place to take from) with [Laragon](https://laragon.org/) (a very good soft for dev on Windows for those who do not know about) on Windows. Everything work as expected now.
