### ISSUE TITLE
If the customer is removed in an "only due" sale the user can still complete the sale.

### ISSUE THREAD

**Issue by mckaygerhard** [opensourcepos/opensourcepos#2601]
this are since 3.2.2 and are still in 3.3.0 and master at git; if remove customer in only due sale. can able to complete, and that's are a problem

1) make a sale
2) adde all the amoutn as due
3) sale cannot be complete, ok but adde the cusstomer.. now can be completed.. 
4) but event complete, remove the customer.. 
5) sale now can be completed without customer in due only! oh great!

**Comment by mckaygerhard** [comment]
no necesary be a hacker to able to pay without a customer: see it at demo

![Captura de pantalla de 2019-11-10 14-02-28](https://user-images.githubusercontent.com/1571724/68548408-f6f4d280-03c2-11ea-8aaf-ffec2708a7f7.png)

**Comment by odiea** [comment]
And why would you remove the Customer when making a Due payment?

**Comment by odiea** [comment]
In application/controllers/sales In public function remove customer add the following line beneath 
$this->sale_lib->delete_payment($this->lang->line('sales_rewards')); and this will clear the due amount after the customer is removed.
```
$this->sale_lib->delete_payment($this->lang->line('sales_due'));

**Comment by mckaygerhard** [comment]
hey @odiea  i'm fine and get done.. this is for all of you.. as you noted! if i reported it's due need to be fixed in the main code to do not release buggy versions..

**Comment by izeblood** [comment]
hahaha only studpid man can allowed due transaction with no name listed whos having due?...oh comon...

**Comment by SteveIreland** [comment]
I do not believe this is a bug but is a feature.  If the clerk starts entering the sale in as a "due" but changes his/her mind and wants to change it to a POS then it seems reasonable to me that the software should allow the customer to be removed and the due transactions to be deleted.

If the user fails to change the payment type then that's a user error and not a system error.  The payment due transaction was added as a hack to avoid needing to use a proper invoicing and receivables system.    I never liked it and I don't see a a reason to burden the system with a lot of error checking for something that shouldn't be used in the first place.

Since the report claims "I'm fine" then I'm closing this issue since it is likely to never be addressed in my lifetime..
