### ISSUE TITLE
I just installed OSPOS, it's awesome, just love it, took me a while to import the items, now there's a question, how do I do a physical inventory count? How does everybody do it? 

### ISSUE THREAD

**Issue by smiledog89** [opensourcepos/opensourcepos#2613]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by objecttothis** [comment]
We are glad you like the software!  Your compliment is nice to hear.  Unless I missed it, I'm not aware that OSPOS currently has an inventory audit system.  It is something on my list to eventually add unless someone beats me to it.  Currently, when we conduct our audits, we manually scan barcodes into an excel with quantity and price amounts, then do a database dump of the data (using MySQL queries) and compare the two in excel.  

I would like to implement something that, when scanning barcodes, it allows you to select the item to "check it off".  Automatically checking an item off would only work if you have the option to allow duplicate barcodes disabled.

It would be doable to enter into Inventory Audit mode-->scan barcode-->select from a list which item is yours, enter the quantity, confirm retail price-->click submit which brings you back to the barcode scan and current inventoried item list.  Once finished, clicking "complete inventory" will generate a report showing discrepancies.

Things to factor:
- Inventories need to be able to be limited to locations within the store in some way so that no one has to inventory the entire store just to get an accurate list.
- Multiple people need to be able to perform inventory tasks on the same inventory at the same time.  For example, if 5 different workstations are scanning inventory items at the same time, the results need to be able to be collated.  This could potentially be done by creating an "inventory session" that can be clicked on by different instances and contributed to.

**Comment by waploaj** [comment]
@waploaj

**Comment by jekkos** [comment]
Also a final feature to add would be to reset the quantities of items in stock to what you have verified there is present

The concept of an inventory session sounds very useful. Currently we have created a separate user for this and add or subtract inventory quantities add items are scanned. In the end we just sum and find the discrepancies using an sql query.

**Comment by objecttothis** [comment]
@jekkos yes, having the ability to reset quantities to that which was physically inventoried would be valuable.  We would need to do this in such a way that allows the user to blanket accept the new inventory values or to select which ones to select.  The place that this could get messy is with situations where a section gets inventoried, but a couple items don't get scanned because they are on a display in a window, or somewhere else.  If they do a blanket accept, then this could create problems.

**Comment by mckaygerhard** [comment]
quite funny nobody cares the issue template right? why and what are that template for? so a year ago i said that template must be "minimized"
