### ISSUE TITLE
In UBUNTU Server the Add New Item Modal has no fields

### ISSUE THREAD

**Issue by wizz269** [opensourcepos/opensourcepos#2680]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.0
- OSPOS git commit hash is: 
- PHP version is: 7.2
- MySQL or MariaDB version is: 5.7.28
- OS and version is: Ubuntu 18.04.4
- WebServer is: Apache
- Selected language is: English
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Did the Installation using wamp on windows machine and is working fine.
when I moved the installation to UBUNTU Server the **Add New Item Modal** has no fields
please help if you have encountered this issue
![TTT](https://user-images.githubusercontent.com/17256716/72225023-a13ed100-3591-11ea-8ebc-14c90a084c66.PNG)

**Comment by odiea** [comment]
As per the README. If you see the item edit dialog box empty starting with version 3.3.0, please disable only_full_group_by option from MySQL/MariaDB. See issue #2538.

**Comment by wizz269** [comment]
**thank you this worked**

**Comment by wizz269** [comment]
> As per the README. If you see the item edit dialog box empty starting with version 3.3.0, please disable only_full_group_by option from MySQL/MariaDB. See issue #2538.

**thank you this worked**

**Comment by jfdesignnet** [comment]
hi @wizz269, may i ask how you do it on ubuntu server please ?

i've run `SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));` on mysql prompt and refresh the page, new item edit dialog box still blank.

also try the sql_mode setting as : `sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION`
on my.cnf, restart mysql service and then restart the page, but still have no luck.

thank you very much in advance.

**Comment by jekkos** [comment]
Can you try our latest unstable master build? I don't think there should be any issue there.

**Comment by jfdesignnet** [comment]
hi @jekkos, thanks for replying.
forgive my ignorance, do you mean the latest unstable version from bintray?
i've been tried the opensourcepos.20201217125820.master.7eb310.zip version, still have the same problem, blank new item dialog box. tried the only_full_group_by disabled too.

fyi, on 20.04 focal it works out of the box with default php and mysql, but with 16.04 xenial and 18.04 bionic the problem exist.
the problem is i want to run this ospos on 18.04.
I even tried connecting the php on host with latest mariadb on docker with the same result issue.

thanks again for trying to help me. appreciate it.

**Comment by jfdesignnet** [comment]
silly me, found the problem. 
because it's on vps, i cannot check the http output on localhost, and cloudflare always redirect them to https and brings out these issue. i didn't realize until i troubleshoot this on my local network which i did today. fix with this #1867

now it works good all on ubuntu version i tried 16, 18 and 20 with or without docker.
i'm sorry for the troubles, and thank you very much for your hard work.
