### ISSUE TITLE
get category search suggestions only in stock

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#2735]
I don't know how to do this.
in models / item.php 'public function get_search_suggestions'
i duplicate line 582 "$ this-> db-> like ('name', $ search);" and I made an or_like category "$ this-> db-> or_like ('category', $ search);" so that in register I also look for the items when I write their category.

This does very well, the problem is that also when I write a category it shows me results of items already deleted.
How can I do it in the same way as with name, that when I write a category it shows me only the items that are in stock and not deleted

`	

		$this->db->select($this->get_search_suggestion_format('item_id, name, pack_name'));
		$this->db->from('items');
		$this->db->where('deleted', $filters['is_deleted']);
		$this->db->where_in('item_type', $non_kit); // standard, exclude kit items since kits will be picked up later
		$this->db->like('name', $search);
		$this->db->or_like('category', $search);
		$this->db->order_by('name', 'asc');`

Thanks in advance

**Comment by daN4cat** [comment]
where('deleted', 0)

**Comment by daN4cat** [comment]
Hmmm ok, you have already a deleted there. What is passed in filters['is_deleted']

**Comment by andriux1990** [comment]
> Hmmm ok, you have already a deleted there. What is passed in filters['is_deleted']?

yes, but in or_like it shows me deleted items

**Comment by andriux1990** [comment]
> where('deleted', 0)

it doesn't work for me

**Comment by daN4cat** [comment]
Because the or_like probably makes the previous optional.

You need to build the query with open and close sub filters.

**Comment by daN4cat** [comment]
In config enable the sale query logging so in logs you can see which SQL queries are issued.

**Comment by andriux1990** [comment]
> In config enable the sale query logging so in logs you can see which SQL queries are issued.

I understand.
i will try. thanks

**Comment by daN4cat** [comment]
I meant sql logging. Mobile phone spell checker changed it.

**Comment by andriux1990** [comment]
> I meant sql logging. Mobile phone spell checker changed it.

@daN4cat where is that of sql logging that explains that I can't find anywhere ...

**Comment by daN4cat** [comment]
In logs folder

**Comment by mckaygerhard** [comment]
wow so explicite and clear as always: X-D

@andriux1990  here the documentation:  in the first place there's the application log (disabled by default) and the system components log (apache log that includes php error log, database error log), let see how to enabled/activate those:

### Application error log:

It's disabled by default, since 3.1 OSPOS, can be enabled in a directive in `application/config/config.php` named `$config['log_threshold']` that are set to `0` by default, set to `4` will default the location of the results logs at `application/logs/`, that can be also customized where logging takes place by the directive `$config['log_path']` permission must be 777 if you used `user_dir` stupid apache mod .. in any case set to 777 if are not in production.. may be be a security hole inclusive 775

#### Database SQL Logging

can be enabled in a directive in `application/config/config.php` named `$config['db_log_enabled']` that are set to `FALSE` by default, set to TRUE to enable. Will default the location of the results logs in the same log file of application at `application/logs/`.
  
### WebServer error log:

Debian only... Alpine linux only.. be use a right OS no stupid ones, that file will be under `/var/log/<WEBSERVERNAME>/error.log` by default are always enable in apache2, but not in lighttpd, so for hiawatta nd lighty you must enalbe the log and usertrack modules

```
ErrorLog "${INSTALL_DIR}/logs/apache_error.log"
CustomLog "${INSTALL_DIR}/logs/access.log" common
```

**Comment by odiea** [comment]
Try placing the $this->db->where('deleted', $filters['is_deleted']); above the order by. It worked for me.

**Comment by andriux1990** [comment]
> Try placing the $this->db->where('deleted', $filters['is_deleted']); above the order by. It worked for me.

I have done what you say here and it does not work for me, I still see the products deleted in register when I search by category.
How does it work for you?

**Comment by odiea** [comment]
It works fine for me. Before I relocated it I was seeing deleted Items afterwards the deleted Items did no show

**Comment by andriux1990** [comment]
Well, it worked for me. what happens is that I have more changes here, but with the teacher if it works well

I have some small changes on get_search_suggestions, I will see why it happens to me

**Comment by odiea** [comment]
If you are using 3.3.1 make sure full_group is disabled. Lots of bugs with this.

**Comment by andriux1990** [comment]
@odiea It is for this reason that it does not give me, when you already have more than one or_like.
I have three because I like to use description to put information that I do not want to be printed in the resivo and to also be able to search from there.

			$this->db->like('name', $search);
			$this->db->or_like('category', $search);
			$this->db->or_like('description', $search);

**Comment by daN4cat** [comment]
I don't believe full_group is the issue here.

@andriux1990 have you enabled the query log as I suggested? What do you see of your query in that log?

**Comment by odiea** [comment]
Neither do I. But why play around with it when this is a known issue.

**Comment by andriux1990** [comment]
this way if it works

		$this->db->like('name', $search);
		$this->db->or_like('category', $search);
            $this->db->where('deleted', $filters['is_deleted']);
		$this->db->or_like('description', $search);

**Comment by andriux1990** [comment]
> I don't believe full_group is the issue here.
> 
> @andriux1990 have you enabled the query log as I suggested? What do you see of your query in that log?
I already do it, I want to see what logs are causing

**Comment by andriux1990** [comment]
> > I don't believe full_group is the issue here.
> > @andriux1990 have you enabled the query log as I suggested? What do you see of your query in that log?
> > 

I already do it, I want to see what logs are causing

**Comment by odiea** [comment]
Yes that works better after adding the description filter.
