### ISSUE TITLE
Error between the barcode and the item id. by adding it for sale

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#2766]
I have an item that has the id with the same barcode number from another product.
The mistake is that when I select this product by barcode the same id as another product. then the wrong product is added to the sale. Instead of adding the product by its barcode, it adds it by its id.

**Comment by daN4cat** [comment]
What about the information in the template?

**Comment by andriux1990** [comment]
> What about the information in the template?

![DeepinScreenshot_20200316061406](https://user-images.githubusercontent.com/29256343/76757598-73bb0300-674d-11ea-8e28-315f3c82583f.png)
![DeepinScreenshot_20200316061422](https://user-images.githubusercontent.com/29256343/76757599-74ec3000-674d-11ea-869a-ac139ca643a1.png)

For example look here at the two selected products. one has an id number 22, and the other element has a barcode number 22. when i am going to make a sale and write code 22 and press enter instead of adding the product that has barcode number 22, add the product that has id 22.

and this is always.

**Comment by mckaygerhard** [comment]
i cannot understand what happened! two products has same barcode? in any case if this are possible! of course the difference will be the id of the product (id field at the database table)

can you elaborate it? please @andriux1990 ?

**Comment by andriux1990** [comment]
Perhaps this does not concern them. Because this tends to cause problems when you have products with id equal to the barcode

**Comment by odiea** [comment]
Can't you set that up to see the item with search suggestions.

**Comment by andriux1990** [comment]
> Can't you set that up to see the item with search suggestions.

if this could be done. the problem is that I pass the barcode reader over the product and add another product for sale

**Comment by izeblood** [comment]
@andriux1990 The problem you raised is based on the experienced you encounter but this problem is very impossible. why? because barcode is cannot be done by your own... it is based on the product itself once manufacturer registered their product. common barcode composed of 12 to 13 digits and it's has different parts and symbol in order to facilitate the thousands of different items around the globe.
![UPCdiag](https://user-images.githubusercontent.com/32444665/77501553-5bf12680-6e93-11ea-8362-db13896c9dcd.png)

**Comment by andriux1990** [comment]
you are right, thanks
