### ISSUE TITLE
item_pics - create_thumb

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#2785]
I take full advantage of the images that we can put on our products in ospos.

I don't just use it in the item module. I also use them in sales, as you can see here.
It is true that my ospos is fornicated, I do not deny it.

![CON ICONOS](https://user-images.githubusercontent.com/29256343/78847749-e6c23d00-79cc-11ea-8081-c032e4d43368.png)
![ICONOS](https://user-images.githubusercontent.com/29256343/78847750-e7f36a00-79cc-11ea-9573-7ae64f3bde74.png)

the problem is this:
When I search for the products, there is a delay of milliseconds to about 2 more seconds, to show the images.
i am surprise you was that if all the images with more size and resolution took longer to show.
If all the images are converted into the same resolution (because they are saved in thumb) this should not happen, since they all have the same resolution and should be displayed at the same time.

in controller / items
$config['width'] = 52;
$config['height'] = 32;
notice that they are stored in this resolution, in the item_pics directory.

the problem is that the browser when it is in items does not show these thumb images. but in real time it is converting the images with the high resolution to this type of image (thumb). and this it does every time one reloads the page.
and it happens in the items module. you can try it for yourselves.
If we enter the items module 100 times, 100 times will convert all these images in real time.
![Screenshot_20200408_194044](https://user-images.githubusercontent.com/29256343/78849168-ec218680-79d0-11ea-98c6-2f5c59ff89b1.png)

I think it would be easier if these thumb images were simply shown.
instead of telling the browser to convert every time the page is reloaded.

**Comment by mckaygerhard** [comment]
no updte on this?

that's what you called "thunbs" are just a resized image!.. and on each "request" are "requested" that "thumbs".. so it takes of course time to procesed!.. 

there's 3 only solutions:

1. alternate already cached images! that's are not so controlled and are not so recommended! if product changes a lot online!
2. alternate already resized cached (manually managed) apart of the main image! on eacho load.. the ospos wil make and extra file with resized image on each fisrt request.. and if sized are not changed (the size to show in the pictures that you posted) that process wil not be made again! so the request of the image to show will be minimum due a image of 52x32 are easy to show for the browser adn will be cached at the client side!
3. use server side request on each image! so that screen will load independiently of the images.. and images wil be downloaded in backgroud!

seems too much work.. and there's no real gain in that! sorry @andriux1990

**Comment by andriux1990** [comment]
Well, there are things that are often complicated, but there are simple ways to do it, ways that do not take as much effort.

Why not show thumb images already at once, instead of the browser converting them every time you go through them.

This is what i try to say

**Comment by mckaygerhard** [comment]
of course.. but that's as i xplained are not easy in never way! sorry

**Comment by mckaygerhard** [comment]
was xplained  are not easy in any way! ok! so dont xpected some one will doit quicklty. it will take some time!
