### ISSUE TITLE
Updating Footer Info 

### ISSUE THREAD

**Issue by WebShells** [opensourcepos/opensourcepos#2831]
@opensourcepos/org i'd like to change the current footer to something more simple and better formatted, also change the website link from github's project to our official website https://opensourcepos.org.

Will submit a PR with the changes, thoughts ?

Current footer: You are using Open Source Point Of Sale version 3.3.2 - 00020b. Please visit the website to learn the latest information about the project.

Suggestions: 

      · All rights reserved © 2010 - 2020 · 
 [OSPOS - Open Source Point of Sale](https://opensourcepos.org) v3.3.2 - 00020b

**Comment by objecttothis** [comment]
Simplifying the footer to contain the basic information is a good idea. Here are my thoughts:
- I'm not sure, but I don't think "all rights reserved" with the copyright mark is the correct way to put it.  That is correct for private Intellectual Property, but I think in our case we would replace it with the license that OSPOS falls under The MIT License (MIT).  You might see how other opensource projects do it, because I think all rights reserved implies that forking the project is not allowed.
- Name of the Project as a link to opensourcepos.org, the version and hash, and the project start year - Current year are all I would put in the footer.  I have typically separated sections of the footer with a pipe " | ", but I'm also not a web designer, so there may be more elegant ways of doing it.

**Comment by WebShells** [comment]
So let's make it something like:
      
    Running Version 3.3.2 - 00020b
 · [OpenSourcePOS.org](https://opensourcepos.org) © 2010 - 2020 · 
  
More simple and still have the same info

**Comment by objecttothis** [comment]
@WebShells I can't tell from your post because of the markup formatting that github is doing.  Do you mean this?

> 
> 
> So let's make it something like:
> 
> ```
> Running Version 3.3.2 - 00020b
> ```
> 
> · [OpenSourcePOS.org](https://opensourcepos.org) © 2010 - 2020 ·
> 
> More simple and still have the same info

@WebShells I can't tell from your post because of the markup formatting that github is doing.  Do you mean this?

````
Running Version 3.3.2 - 00020b · [OpenSourcePOS.org](https://opensourcepos.org) © 2010 - 2020 ·
````

If you meant it to go on two lines, I'd say we should keep it to one line.  Also, I understand why you did the camel case, but it looks funny to me.  As for the version, I would ditch "Running Version" and just put the version.  My vote would be this:

````
© 2010 - 2020 · [OpenSourcePOS.org](https://opensourcepos.org) · 3.3.2 - 00020b 
````

**Comment by objecttothis** [comment]
I'm ambivalent about the pipes, but I think the rest looks cleaner.

**Comment by objecttothis** [comment]
````
© 2010 - 2020 · opensourcepos.org · 3.3.2 - 00020b 
````

**Comment by jekkos** [comment]
This formatting feels best for now.

> ```
> © 2010 - 2020 · opensourcepos.org · 3.3.2 - 00020b 
> ```

**Comment by WebShells** [comment]
For the reason that all other info are numbers, i'd like to separate the link to get direct attention for the user to click, that's the only reason i would place it on 2 lines.

© 2010 - 2020 | 3.3.2 - 00020b 
       · opensourcepos.org ·       

I have no problem with the suggestions, just sharing thoughts.

**Comment by objecttothis** [comment]
> 
> 
> For the reason that all other info are numbers, i'd like to separate the link to get direct attention for the user to click, that's the only reason i would place it on 2 lines.
> 
> © 2010 - 2020 | 3.3.2 - 00020b
> · opensourcepos.org ·
> 
> I have no problem with the suggestions, just sharing thoughts.
> Should be centered, but not working on github :p

Understood.  having the link in the center and the fact that it's a link (therefore different color and hover behavior, IMO should make it stand out enough.  Two lines feels too bulky to me.

Here is Amazon's

````
© 1996-2020, Amazon.com, Inc. or its affiliates 
````

**Comment by andriux1990** [comment]
Hello organization. I hope everyone is in good health.
when we will have a PR on the "Updating Footer Info"

**Comment by WebShells** [comment]
Hello @andriux1990 i'll submit it today along with the system info updates.

**Comment by andriux1990** [comment]
> Hello @andriux1990 i'll submit it today along with the system info updates.

Thank you ..
