### ISSUE TITLE
ITEMS LOADING IS VERY SLOW ON 32 BIT (x86) SYSTEM AND FAST ON 64 BIT (x64)

### ISSUE THREAD

**Issue by MrLAL** [opensourcepos/opensourcepos#2855]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

OSPOS Installation Info: | 3.3.1 - c786d4
-- | --
en-US
» GD: Enabled ✓» BC Math: Enabled ✓» INTL: Enabled ✓» OpenSSL: Enabled ✓» MBString: Enabled ✓» Curl: Enabled ✓
.Browser:  			Firefox  				.Server Software: Apache/2.4.43 (Win64) OpenSSL/1.1.1g PHP/7.3.18 				.PHP Version: 7.3.18 				.DB Version: 5.5.5-10.4.11-MariaDB 				.Server Port: 80 				.OS: Windows NT UGASNETWORKLTD 6.1 build 7601 (Windows 7 Ultimate Edition Service Pack 1) AMD64
» [application/logs:] 				 -  0777 \|    Writable ✓  				» [public/uploads:] 				 -  0777 \|    Writable ✓  				» [public/uploads/item_pics:] 	 				 -  0777 \|   Writable ✓  				» [import_customers.csv:]  				 -  0666 \|    Writable ✓

### Issue / Bug  / Question / New Feature
Good day and well done on the incredible job being done continuously on OSPOS. I have been a huge fan of this project since 2015. Well done sirs. Now onto my issue:
1. I discovered  that items got very very slow to load when migrated from 2.3.4 to 2.4 to 3.0.0 then to 3.3.1 on 32 bit Windows 7 (Client System) but got relatively faster to load on Windows 7 (My System)

2. Could the reason be due to Client System (32 Bit) and My System (64 Bit)

3. Client System memory is 2GB Ram while my System is 4GB Ram

4. Could it be because of a failing hard drive on Client System 

5. I copied the exact files, database of OSPOS and Server ( I used XAMPP 7.3.18) for both systems and same configuration

6. I want to format the client system on Saturday (in 3days time)  to 64 Bit as a last resort but I want to hear from the experts before I proceed

7. Database SQL of imported table  is around 25MB (Almost 4 years of data)

8. It took like 60-180 seconds for the Items module  to load on Client System (VERY SLOWWWW) whereas it took like 4-5 seconds for the Items to load on My System  

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by objecttothis** [comment]
I will be submitting Pull Request #2821 as soon as it's finished testing.  This pull request will have many optimizations to the database that should speed up most of the queries being done that are causing your issue.  That said, your hardware may limit you if you have a large database.  

The problems with the database is that there are several columns that are not indexed which are used in JOIN statements and WHERE clauses.  This causes the queries to run slower and use significantly more memory.  There are also three fields in the attributes_values table (which gets quite large) that need to be set to UNIQUE and were not when the table was implemented.  I am just finishing a migration script that will find duplicate attribute_date and attribute_decimal values then merge them all together and make those columns (as well as attribute_id) UNIQUE.  The end result of this is that queries against those tables are significantly faster.

What you are likely running up against is that MySQL is caching on disk due to running out of memory. I am running a dedicated server with 16GB of ram and was running out of memory on large imports.  As soon as I made the optimizations I was able to import a 250 row CSV update file with full attributes in 3.7 seconds instead of the 12.5 seconds I started out with.  

If you can, install MySQL Tuner for Windows (https://github.com/pmachapman/mysqltuner) and run it.  It will recommend adjustments that you can make to your mysql configuration file.  Also it appears that you have an older version of MariaDB installed.  You may consider installing MariaDB 10.5 and PHP 7.4.6.  They may have optimizations that improve things.

**Comment by MrLAL** [comment]
Well, thank you for your prompt response. I deliberately removed 2GB off my RAM capacity to be the same with Client System but I still got the same faster speed when items are being loaded. So I guess I had to reformat the Client system to x64 architecture (I guess that's the only basic difference since everything is copied out from my system) since it is also equipped with 2GB of RAM.

However, I will also try to take advantage of the XAMPP (PHP 7.4.6 with MariaDB 10.4.11) and see the optimizations that could hopefully improve the speed.


Thank you.

**Comment by MrLAL** [comment]
For record purpose and for those who may be having same issue, I will want to state that the SQL tuner really did help. I could remember using the OPTIMIZE TABLE function on my System before this post was made and I did **not run** that on Client System before now. 

I finally had to reload client system with 64 Bit Windows 7 operating System, import 20mb of database (more than 3 years), then I run the OPTIMIZE function of the tables in PHPMYADMIN after import was made; and I noticed significant increase of ITEMS LOADING SPEED.

Thank you **Objecttothis** for pointing me in the right direction.

**Comment by objecttothis** [comment]
@MrLAL Super, I'm glad that helped.  in general running mysqltuner will tell you what about your configuration file you can change.  `mysqlcheck -u[username] -p -o --all-databases` will check your databases and tables then optimize them.

This will help in the short term, but long term we need to modify the code.  My changes should be ready for broad testing soon.
