### ISSUE TITLE
impossible to fill field in chrome and derivatives

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#2860]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

OSPOS Installation Info: 3.3.2 - d6df08

Language Code: en-US

Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Configuration:
.Browser: Chrome
.Server Software: Apache/2.4.38 (Debian)
.PHP Version: 7.3.14-1~deb10u1
.DB Version: 5.5.5-10.3.22-MariaDB-0+deb10u1
.Server Port: 80
.OS: Linux 4.19.0-9-amd64

File Permissions:
» [application/logs:] - 0777 | Writable ✓ | Vulnerable ✗
» [public/uploads:] - 0777 | Writable ✓ | Vulnerable ✗
» [public/uploads/item_pics:] - 0777 | Writable ✓ | Vulnerable ✗
» [import_customers.csv:] - 0777 | Readable ✓ | Vulnerable ✗

There are problems with file permissions please fix and reload this page.

Security Vulnerability Warning
Permissions higher than 750 leaves this software at risk.

» [application/logs:] is writable, but the permissions are higher than 750.
» [public/uploads:] is writable, but the permissions are higher than 750.
» [public/uploads/item_pics:] is writable, but the permissions are higher than 750.
» [import_customers.csv:] is writable, but the permissions are higher than 750.

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

Chrome and Opera browser error. and perhaps in browsers derived from chrome.
Office -> Configuration -> General, Localization, Info ...
Cannot fill in the fields. every time the pulsor is placed it is ejected.
![chrome](https://user-images.githubusercontent.com/29256343/84132747-799a4a80-aa03-11ea-9dc8-d856e3518fd7.png)

in demo ospos the same thing happens

Firefox works fine

**Comment by odiea** [comment]
IE 11 works but Edge does not. Anyone have any Ideas why this might be going on?

**Comment by odiea** [comment]
Chromium and Opera in Lubuntu also shows this issue.

**Comment by andriux1990** [comment]
I will review why this happens

**Comment by andriux1990** [comment]
views/configs/system_info.php line 168 to 173

> 			function clearSelection() {
>				window.getSelection().removeAllRanges();
>			}
>			document.onmouseup = function() {
>				window.setTimeout(clearSelection, 100);
>			};
This is what causes the compatibility error in the Chrome browser and its derivatives. so much so that it does not allow writing or making any other changes in the entire configuration module

**Comment by mckaygerhard** [comment]
the innecesary copy paste feature improvement in that commit e6dad3eb810b7f99b41716ace0a617071cf0e1b8#diff-f2c912b09e0fec1e35f0ceb4c7e89445 was the root cause..  check https://github.com/opensourcepos/opensourcepos/commit/e6dad3eb810b7f99b41716ace0a617071cf0e1b8#r40199757

**Comment by jekkos** [comment]
@WebShells as pointed out here, any idea why the clearSelectedRange is needed? You are periodically resetting all selection, this does not make a lot of sense to me.

Shouldn't this only be done after a very specific event?

**Comment by SteveIreland** [comment]
I'll add another tidbit to this puzzle.  I hadn't seen this ticket but today downloaded the latest master and created two test environments and this problem was found in both environments.

I also noted the following error in the console log.  Apparently the minimization on the clipboard script isn't being dropped in the correct spot.

![image](https://user-images.githubusercontent.com/23066623/85955531-37eb2880-b94d-11ea-9405-058fbccaab24.png)

**Comment by jekkos** [comment]
On demo server this does not seem to appear.

**Comment by odiea** [comment]
The inability to edit a field in Locale config is still apparent.

**Comment by jekkos** [comment]
Ok thanks for checking @odiea I'm waiting for feedback from @WebShells beforre reverting / changing this code .

**Comment by odiea** [comment]
Ok Could you check out the latest issue?

**Comment by jekkos** [comment]
ah no I'll check the issue you reported, this eve. Thanks for testing/validating already.

**Comment by andriux1990** [comment]
The only place where it is fixed in the general tab ... after all, they have the problem .. it doesn't allow to write

**Comment by jekkos** [comment]
this issue is indeed still present

**Comment by mckaygerhard** [comment]
that is the partial solution only.. removal of the https://github.com/opensourcepos/opensourcepos/pull/2885 .. but still some fields marsk as read only when first input was posted! @jekkos

**Comment by objecttothis** [comment]
> 
> 
> @WebShells as pointed out here, any idea why the clearSelectedRange is needed? You are periodically resetting all selection, this does not make a lot of sense to me.
> 
> Shouldn't this only be done after a very specific event?

@jekkos It appears that @Webshells isn't able to be around.  I haven't seen him respond to any messages in awhile.  I think I can shed some light on this.  I believe that set of code was designed to assist with the copy system info to clipboard command.  When @Webshells first implemented the code, it was highlighting the system info data and copying it, but then it left everything selected.  It's curious that it has had this sort of negative side effect on some browsers.  There are two ways that we can handle this issue, if I've assessed it correctly:  One is we can remove the block of code and just deal with it selecting and copying to the clipboard but not un-selecting the code.  The other is to augment it so that the block of code only runs in relation to just the system info copy feature but does not run.  A third option that may work but will likely be problematic is to test the browser and enable that block of code only when its a browser that doesn't exhibit the side effect.  It seems like IE and Firefox might be the only ones.  Thoughts?

**Comment by jekkos** [comment]
Well I think ideally we should only enable it for the system info field, if that is an option. I would not go into adding any browser specific workarounds / hacks. If we can't do it that way then I'd disable it completely as you say.

**Comment by objecttothis** [comment]
> 
> 
> Well I think ideally we should only enable it for the system info field, if that is an option. I would not go into adding any browser specific workarounds / hacks. If we can't do it that way then I'd disable it completely as you say.

Agreed.  Given that @WebShells hasn't been able to respond, he may not be available to implement this.  Do you want to do that?  I think it's probably doable, but I'd need to look up how to do it.  I'm guessing it's just a matter of associating the function with the System Info block so that it is activated when that's the tab people are on, then deactivated when on other tabs.

**Comment by SteveIreland** [comment]
Regarding the system_info page.  Is there a way to run it manually without OSPOS being operational?  If the system isn't operational it might be helpful to type in manual URL that would provide the info that sytem_info is intended to provide. (i.e. if PHP is running then it would still provide useful info)

And I agree that we can't publish the release until this is fixed.

**Comment by objecttothis** [comment]
> 
> 
> Regarding the system_info page. Is there a way to run it manually without OSPOS being operational? If the system isn't operational it might be helpful to type in manual URL that would provide the info that sytem_info is intended to provide. (i.e. if PHP is running then it would still provide useful info)
> 
> And I agree that we can't publish the release until this is fixed.

This is a feature that is good to have.  Given that the Config Controller (and therefore view) extends the Secure_Controller, I don't think there is a way to do this with just the code that exists as it is.  What we would likely need to do is to copy the code in the /views/configs/system_info.php relevant to the information needed and paste it into a simple php file that isn't an extension of the Secure Controller and just gets linked to directly.  There is nothing about the logic in the view that requires access to any models, but with the .htaccess files, it wouldn't be able to be stored in the views folder without some sort of modification to the .htaccess

**Comment by WebShells** [comment]
Will cover this during this wk, sorry for the delay tean. @SteveIreland you are right, it should be accessible from outside the setup. i got some comments from @daN4cat before if we wanted it accessible through public, will get back to them and see if i can do something about it.

**Comment by objecttothis** [comment]
> 
> 
> Will cover this during this wk, sorry for the delay tean. @SteveIreland you are right, it should be accessible from outside the setup. i got some comments from @daN4cat before if we wanted it accessible through public, will get back to them and see if i can do something about it.

@WebShells good to have you back.  Unless someone vetos, I think we should just fix the bug in this issue for 3.3.2 and then make the enhancement to have the system_info visible when not logged in a change for 3.4.0.  I suggest this because 3.3.2 is supposed to be a bugfix release rather than an enhancement release and the little detail that it's 7 months overdue.

**Comment by jekkos** [comment]
Indeed let's fix this bug and postpone the improvements for the next release.
