### ISSUE TITLE
How do I remove credit and debit card payment option? I just thought there a specific array for sales payment types but i dont see it

### ISSUE THREAD

**Issue by mwillis72** [opensourcepos/opensourcepos#2898]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by daN4cat** [comment]
Search past issues and you'll find your answer.
It looks like you are ignoring the issue template completely.

**Comment by mwillis72** [comment]
OK.... I think github should provide a better way of searching issues

**Comment by objecttothis** [comment]
Github doesn't do a lot of stemming in their search unfortunately.  I looked around and found an old issue but I don't have time to do more searching on this at the moment.  

@daN4cat I think that an enhancement that we could make here is to rework the payment option order feature of Office->Config->Locale so that instead of offering the three payment method orders it could be an ordered multi-select (See the allowed file types multi-select in Office->Config->General).  The only question is whether we can incorporate a way in that multi-select to change the order.  That would be the cleanest way to do it, but I'm not sure bootstrap has that functionality.  If not, perhaps one multi-select to choose which payment methods are allowed and a separate element to choose the order.
