### ISSUE TITLE
Stock Location

### ISSUE THREAD

**Issue by lanbonx** [opensourcepos/opensourcepos#2915]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is:  3.3.2
- OSPOS git commit hash is: cb67b5
- PHP version is: 7.4.8
- MySQL or MariaDB version is: MarisDB 10.0.38
- OS and version is: Debian 9
- WebServer is: Apache2
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature
Should stock location have at least one other detail (address maybe)? This is to differentiate the login user when he/she prints a receipt for the sale with only one address configured for THE store(HQ in NYC, 2nd store in LA, 3rd store in Chicago). All receipts will have the NYC address.
AND
when a user that is allowed to do/edit sales, receiving and items modules for the user's assign location but when the user click the DAILY SALES button, all sales for all locations/branches appear, it should filter only this location's daily sales.

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

**Comment by SteveIreland** [comment]
OSPOS is a single store application which is why location is really only useful for identifying where, within the domain of a single store, product should be found (i.e. a trailer out back, on the floor, or in the backroom).    You might find a multi-store branch of OSPOS somewhere on github.  There is a lot of work involved with making those changes.   I believe @jekkos started an effort a long time ago but I haven't heard an update on that in a long time. 

Maybe someone who has actually stretched OSPOS into a multi-store environment can share what they did and their experience.  I'd be interested to hear it.

**Comment by lanbonx** [comment]
I don' think it's for a single store location because there is a requisition function/mode on the receiving module...I don't think it's for moving stock for a single store (from ie backroom to store front). I could be wrong...Can @jekkos clarify on this store location function ?
![location_requisition](https://user-images.githubusercontent.com/25758264/89724414-645a9000-da35-11ea-8a3a-22b8e9235144.png)

**Comment by daN4cat** [comment]
It's one store, stock room, front room or other location but still one store.

**Comment by objecttothis** [comment]
If your installation is on a public-facing server, you can (sort of) use it as multi-location.  you would use stock locations to indicate your other shop locations rather than locations within a shop.  You could even do both by naming your locations with a prefix (store1-storage, store3-floor, etc).  Then use attributes to specify where with your location the item is found.  For example, create an attribute called "item location" that is either a TEXT or DROPDOWN type and then you can specify the multi-store location and the place within that shop location ("Aisle 1", "Hardware", etc).

What you lose by doing this is that your inventory is then stored by shop rather than by location within the shop.  You also don't have as fine-tuned reporting.

I'd eventually be interested in helping make OSPOS multi-location, but I think there are some organizational design changes that need to happen to make the changes not "hack".

**Comment by jekkos** [comment]
Adding the multistore means adding a new table for store definition + linking sales and receivings and stock locations to it. Also permissions are local to a store, so quite some impact on the datamodel.
