### ISSUE TITLE
Theme Darkly CSS Fix

### ISSUE THREAD

**Issue by minhazulOO7** [opensourcepos/opensourcepos#2949]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.2
- OSPOS git commit hash is: bb309c
- PHP version is: 7.2.24
- MySQL or MariaDB version is: 5.5.5-10.3.17-MariaDB
- OS and version is: Linux 4.18.0-193.14.2.el8_2.x86_64
- WebServer is: Apache/2.4.37 (centos)
- Selected language is: en-US
- (If applicable) Docker installation: N/A
- (If applicable) Installation package for the LAMP/LEMP stack is: N/A

### Issue

The issue is about CSS. If I chose theme darkly then there are some fixing to do. Firstly Receivings & Sales tab. It becomes white and hard to see anything on there. After that, Items. If I select any item it just turns to white, can't see anything. Lastly, Reports > Graphical Reports. In the graphical reports all of the text becomes black and impossible to see what is there. I have fixed it with my own CSS (**color** and **fill**), I am putting it here:

### Default CSS Values at `/public/dist/opensourcepos.min.css`

**Items (When Selected)**

`.fixed-table-container tbody .selected td{background-color:#f5f5f5}`

**Receivings & Sales**

`#register td{background-color:#EEE;padding:3px;text-align:center}`
`#add_item_form,#overall_sale{background-color:#BBB}`
`#mode_form,#payment_details{background-color:#DDD}`

**Reports > Graphical Reports**

`.ct-label{fill:rgba(0,0,0,1);color:rgba(0,0,0,1);font-size:1.2rem}`

### My Fixed CSS Values at `/public/dist/opensourcepos.min.css`

**Items (When Selected)**

`.fixed-table-container tbody .selected td{background-color:#757575}`

**Receivings & Sales**

`#register td{background-color:#757575;padding:3px;text-align:center}`
`#add_item_form,#overall_sale{background-color:#757575}`
`#mode_form,#payment_details{background-color:#757575}`

**Reports > Graphical Reports**

`.ct-label{fill:#eee;color:#eee;font-size:1.2rem}`
`text.ct-axis-title{fill:#eee;color:#eee;}` -> Added this CSS at the end (after `.ct-tooltip-point:hover{r:7;stroke-opacity:.2;stroke-width:20px}`) of the `/public/dist/opensourcepos.min.css` file to control the axis title color.

I hope this will be implemented/ have a workaround in future updates. I know it's only suitable for theme darkly, not others. Please point out any issues. I will be happy to help.

**Comment by SteveIreland** [comment]
CSS styling changes involving layers of css (i.e. themes) are black holes that suck the life out of anyone who gets too close.

Having said that it does need to be addressed, but I'm wondering if the problem is not with the darkly theme, but with css color overrides that only took into consideration the default theme. Those changes need to be moved to a theme specification, but I'm not yet familiar with the internals of the bootstrap theme.

**Comment by minhazulOO7** [comment]
@SteveIreland thanks for replying! Yes those CSS loads as global/ default option. We need theme specific CSS so that every theme can be really used, not like blocking/ shading the content so that the user never uses it. I personally like darkly because of it's dark base. Easy to eyes and also usable for long time period work.

**Comment by jekkos** [comment]
I agree this should be applied in a generic way, indeed as you say most of the overrides were done with the default theme in mind, so they should move to an ospos specific stylesheet that is only loaded if this base template is selected.
It should not be that hard to do and might render other themes more usable as well.

**Comment by minhazulOO7** [comment]
@jekkos thanks for replying! Yes that's what I want to say. Default/ base theme with it's default/ base CSS, and other themes with their respective CSS. This would be really helpful for any person to select any theme they like to use without any manual editing. Although I can add one more thing, that is, if the styling can be selected as a drop-down menu on an individual settings page that would be more appreciated. I am requesting too much from you guys, sorry in advance. If I can I will contribute.

**Comment by daN4cat** [comment]
Isn't theme selection a drop down menu in settings already?
If some styling need to go together with that it's a matter of expanding that feature.
Unless I'm missing the point here.

**Comment by minhazulOO7** [comment]
@daN4cat thanks for replying! Yes, talking about individual CSS style (text color, hover color, selected color, new item added highlight color, item updated highlight color, receive/ sales text color, text size, color, padding, Reports -> Graphical Reports text color, text size, padding etc. like this type of granular customization) as a drop-down menu in a individual (Office -> Configuration -> Theme & Style, like that) page on Office -> Configuration. I hope this will explain what I am trying to say.

**Comment by SteveIreland** [comment]
Only because I want to learn what's going on under the covers.  Sort of a "pandora's box" type of curiosity.

**Comment by SteveIreland** [comment]
I did a little precoding on this to see what kind of trouble I would encounter.  It actually shouldn't be too complicated.  My current idea is to include a css file that has the same name as the theme in the public/css folder that will contain settings/overrides for color and background color.  This seems conceptually simple enough.  If the file exists then it would be included immediately following the includes of the base bootswatch theme.

The only issue I encountered are css stylesheets that use the same class names  That's a bit of a challenge because they can be styled slightly different. However, if it's okay with the group then it can be handled by adding an id on the top level container that is unique to the view.  Then in the stylesheet the id can be used to better qualify the class.  That's a small change to existing practices and I don't believe, at this time, that there is a lot of that going on.  So far I've encountered it only in the document css and the equivalent document_email css.

I started work on a flatly.css and a darkly.css 

I was also entertaining the idea of involving scss and picking up the actual colors to be used from the collection of variables provided by bootswatch, but that might be a bit of over-engineering and would probably not be appreciated.  :-)

**Comment by jekkos** [comment]
@SteveIreland indeed what you describe is what I also had in mind. We should indeed try to avoid to have any ambiguity in the styles, as you say. MIght be better to be explicit in the CSS itself on which style should override which one (as you say by using id then in the ospos them specific file in this case).

Also I think the scss might be worth exploring, but it might be for another story? Otherwise if you think you can apply it to solve this specific problem then also fine, I'd love to see how it can be put to work in that case.

**Comment by SteveIreland** [comment]
This issue is resolved.

**For Developers:** The system is obviously designed around the flatly theme.  When developers work on their changes they are designing for the flatly theme.  The recommended approach to assign color attributes is to use the bootstrap theme classes wherever possible, if you use bootstrap theme classes then overrides are not needed and your work is more likely to be usable regardless of the theme.  Particularly avoid setting color attributes.  For changes made in the past that are causing theme issues, with this change, we now have the ability to do temporary corrections using this theme stylesheet override feature - but this shouldn't be your first choice.

**For OSPOS Users** If you choose to use a theme other than flatly and you find that the text isn't readable please open an issue for it, letting us know the theme you are trying to use and include a screenshot of the issue (or at least a very clear description of the problem.)

**Comment by jekkos** [comment]
Amen. thanks for the work here @SteveIreland.

**Comment by minhazulOO7** [comment]
Thank you very much! 😇 @SteveIreland
