### ISSUE TITLE
Rounding to the nearest 5 cents

### ISSUE THREAD

**Issue by chunter2** [opensourcepos/opensourcepos#2975]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [x] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

- OSPOS version is: 3.3.2
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

I can't seem to figure out how to get cash sales to round to the nearest 5 cents.  It's like I would need a 1.5 option in the Cash Decimals box on the Localization page in Configuration.  If I set it to 1 it rounds to the nearest 10 cents so I know the rounding code is doing something.  I found a couple github issues talking about it but I seem to be missing how to actually enable it.  

Thanks

**Comment by chunter2** [comment]
Just looking for any kind of help on this one.  Am I missing something or is it just currently not possible?

**Comment by odiea** [comment]
The current unstable master has a half five option in localization cash rounding that might work for you.

**Comment by chunter2** [comment]
Somehow I missed that commit.  It's this one for reference.  https://github.com/opensourcepos/opensourcepos/commit/bf88f8fdae2b85a1952354cd4360dc000dd4292f
I applied it manually and it works perfectly.  

Thanks for the help.

**Comment by chunter2** [comment]
I think I may have found a bug with the above commit.  It looks like the daily sales report is not updating the amount due column for a cash transaction where it's rounding the the nearest 5 cents.  When I click on the receipt the Total shows the rounded amount.  So the change due column shows a plus or minus 1 or 2 cents if the tendered amount is the Total amount on the receipt.  Hopefully that makes sense.  

Thanks
![rounding](https://user-images.githubusercontent.com/531129/97040909-abd4c080-153c-11eb-8024-23eb3db6298f.jpg)

**Comment by chunter2** [comment]
Looks like there's another issues with this.  The rounding works when I switch to Cash as the payment type but when I put the amount tendered in and add the payment it switches the display back to the non rounded value for Total and Amount Due.  The receipt looks correct though.  I've since noticed that I think it has to do with the Payment Options Order under Localization in the Configuration.  If Cash is first the display is ok but if Debit or Credit are first is switches back to the non rounded amounts.  Maybe this should be marked along with this ticket?  https://github.com/opensourcepos/opensourcepos/issues/2922

**Comment by jekkos** [comment]
Ok this one needs further investigation / veritfication.

**Comment by SteveIreland** [comment]
After spending a couple of hours on this I finally remembered that this is not a bug, but something that was intentionally not addressed.

During the development of the original change to support cash rounding was where I first realized this was happening, and I convinced myself that, at that time, for that particular change, it was acceptable.  Not being a user in the country, it seemed arguable that it might be useful to track the differences between what was actually due and what was paid due to cash rounding.  The original requestor did not complain.

I'm open to make the change, but this will not be a trivial correction because it will significantly complicate the select function in the Sale model, which is already complex.  There are now two factors that determine if cash rounding is triggered, and so far I've avoided changing the sales table to support cash rounding.  To resolve this issue without a database change seems like it will make the SQL more complex than would be approved because I'd need to search payment types for each sale to determine if one of them is a Cash payment.   My preferred option would to update sale table to flag it as a "cash rounding" transaction and then add a field to track the cash rounding difference.

@jekkos , @daN4cat Does anyone have other thoughts or do you want me to proceed with the change?

**Comment by SteveIreland** [comment]
@chunter2 Since you reported the issue what are your thoughts?  Can you work with the system without any changes or do you feel this is a show stopper that prevents you from taking advantage of cash rounding as implemented?  (And I do recognize the secondary bug and will hopefully resolve that either as part of this major change or as a minor fix.)

**Comment by chunter2** [comment]
@SteveIreland So I didn't end up turning rounding on because of the secondary issue. I think I would have left it on if it was just the daily sales report that was wrong. I'm now thinking the daily sales report issue may be the same as this one. https://github.com/opensourcepos/opensourcepos/issues/2995 Would that make sense?

**Comment by SteveIreland** [comment]
Yes, I'm sure that there are several down-line issues that should be corrected but I believe they can only be corrected with a minor database change so that the difference between cash rounding amount paid and the calculated sales amount due can be tracked and accounted for in subsequent reporting.

**Comment by chunter2** [comment]
So then in my use case it would be great to have two separate fixes.  One for switching between Cash, Debit and Credit in the sales module when rounding is on and one for what you're calling the minor database change to fix the different reports.  Does that seem logical?

**Comment by SteveIreland** [comment]
I'll take a closer look at the first issue, but the main issue may be a small database change but since it's to the sales table there are SQL reporting queries that will be impacted it is NOT a trivial change.  I'm going to need @jekkos to approve the change before proceeding.

**Comment by jekkos** [comment]
@SteveIreland I think it'd be best to save the data as not rounded and do the rounding in code, afterwards.. but as you say that might require

* extra complexity in SQL to apply this rounding to the amounts (like boolean logic in the select clause)?
* or apply the rounding afterwards in code, but that would mean that we need to apply this everywhere the sale data is used (which is probably a lot of places)?
* or apply the rounding by going through the resultset after the query.. however that does not sound very nice either..

**Comment by SteveIreland** [comment]
@jekkos How about instead of touching the sales table I just add an extension to the sales table that is only used when the system is configured for cash rounding?  That way there isn't any impact to existing implementations that don't use cash rounding, and that would simplify the changes to the SQL statements when I DO need to account for cash rounding.

**Comment by jekkos** [comment]
We need to store how it was rounded as if someone changes the rounding strategy, we do not want to touch sales done in the past. This means that we should least keep track of the rounding mode (as it can change over time). So for historical sales, this stored mode has precedence over what is configured globally.

Currently I don't really know how the global rounding setting works, but it feels like the cleanest solution would be to call that logic in case of a historical sale with the mode that was defined for that sale when it was done. Currently I don't see an advantage of storing it in the db if we can just call the rounding logic using the mode for a historical sale (instead of the one in config)? Or am I missing sth here?

**Comment by SteveIreland** [comment]
Currently, at the point of completion,  sales amount - amount tendered = change due.

With cash rounding triggered then we have sales amount - cash rounding adjustment - amount tendered = change due.

Cash rounding is triggered two ways.  If the cash decimals is greater than the cash decimals OR if the cash rounding code is HALF FIVE.  In both cases the payment type also has to be CASH.

Since these are configuration values that can change and we don't want changes to impact past sales it is far safer to simply capture the cash rounding adjustment at the time of the sale.    Then I would have something to easily factor into the SQL statements to fix sales reporting in cash rounding scenarios.

**Comment by jekkos** [comment]
> Cash rounding is triggered two ways. If the cash decimals is greater than the cash decimals OR if the cash rounding code is HALF FIVE. In both cases the payment type also has to be CASH.

indeed as discussed I think we can then just safe the outcome of this rule per line in the sales table?

> Since these are configuration values that can change and we don't want changes to impact past sales it is far safer to simply capture the cash rounding adjustment at the time of the sale. Then I would have something to easily factor into the SQL statements to fix sales reporting in cash rounding scenarios.

Ok I had a quick look in the code and indeed it might be better as you say, this strategy is already more or less in place.. (as said before). An idea here might be to save this rounding amount as a record in the sales_payments table? In that case it could even be explicitly shown on a receipt for completeness?

One last downside of doing the fix this way is that we will need a migration script to correct all historical sales and determine if they had rounding setup or not..

**Comment by SteveIreland** [comment]
Okay, that sounds like a reasonably negotiated settlement.  :-)  I'll sign.

**Comment by SteveIreland** [comment]
@chunter2 In Canada what are the rules when a sale has two payment transactions and only one is a cash payment?  Is the sale still eligible for cash rounding or does it fall into the category of "normal sale"?

**Comment by chunter2** [comment]
@SteveIreland I believe it falls back to "normal sale" since you can charge the pennies through debit or credit.

**Comment by jekkos** [comment]
@SteveIreland any idea on an ETA for this one? Should we hold back 3.3.3? (I'm only planning to include one more feature and no more open issues at this time #2958 ).

**Comment by SteveIreland** [comment]
I'm trying to finish up the changes today.  I expect to have it fully tested and in pull request form by next weekend.

**Comment by jekkos** [comment]
Ok take your time, thanks for the headsup

**Comment by SteveIreland** [comment]
Just about ready to publish ... I have a few more changes, but ran into an interesting issue.   At the detail level I have be able to adjust the total sales and cash due numbers by the cash adjustment.  But none of the summary reports account currently factor in payments.  I cannot adjust "total sales" by the cash adjustment amount unless I add the additional overhead of creating a temporary table for payments just like we do for the detail reports.

Is that something that will be approved or is that a bit too far?  I suppose I could build the temp file only for sites requiring cash rounding but that will still make the code more complicated.   

@jekkos  Any opinion on this?

**Comment by SteveIreland** [comment]
Here is what a receipt looks like in a cash rounding scenario. In this case the system rounded up to the nearest HALF-FIVE.  The cash adjustment is now being reflected as a payment type which is flagged as an adjustment so that it can be ignored in payment totals.

![image](https://user-images.githubusercontent.com/23066623/99911612-ab5a5180-2cc3-11eb-972d-8ed30b8703a8.png)

**Comment by SteveIreland** [comment]
And here is how it currently looks in the payment summary.  While it appears to balance under the transaction amount column, it doesn't under the payments column, but then because we randomly threw in an upcharge due to cash rounding it seems like it's got to be out of balance somewhere.   I recall this query is used for other purposes so I'm not sure what the effect down-line will be.

![image](https://user-images.githubusercontent.com/23066623/99913527-31779780-2cc6-11eb-990b-1471dc4dd2d7.png)

**Comment by odiea** [comment]
@SteveIreland The payment summary is also used in Cashups.

**Comment by SteveIreland** [comment]
Pull request #3026 has been submitted for testing.  But I suspect there are a couple of issues that will need to be addressed before it's ready.

**Comment by SteveIreland** [comment]
Also, identifying and migrating earlier "cash sales" hasn't been started yet.

**Comment by objecttothis** [comment]
@SteveIreland How close are we to merging this?

**Comment by jekkos** [comment]
@chunter2 could you perhaps test the latest build with fixes for this issue?

**Comment by chunter2** [comment]
@SteveIreland I finally had a chance to test this out.  I'm noticing a few display issues I think.  If you look at the image below I've circled three lines that I think should have two decimal places each.  I tried this on the dev server.  

Looks like the total payments and cash lines don't show the decimals whether HALF FIVE is selected or not.  I just checked on my 3.3.2 system and the two decimal places are there for those lines.  

The amount due line is only missing the trailing zero if it rounds to a zero.  It's there if it's a 5.  

Hopefully this all makes sense.  

Thanks
![half-five](https://user-images.githubusercontent.com/531129/115727788-f1d6d980-a351-11eb-9be0-685a9ac1a154.jpg)

**Comment by jekkos** [comment]
@chunter2 did you test on latest master?

**Comment by jekkos** [comment]
https://github.com/opensourcepos/opensourcepos/pull/3168

can you try this change to see if it resolves your issue @chunter2 ?

**Comment by chunter2** [comment]
@SteveIreland @jekkos Next issue I found.  If I go back and look at old receipts in my system where the cash rounding was set to the default and then change the cash rounding to HALF FIVE and refresh the receipt page the change due line changes.  What's interesting is the change due for that transaction in the daily sales report doesn't change when I switch the cash rounding value back and forth.

**Comment by jekkos** [comment]
Ok first fix merged to master.

**Comment by jekkos** [comment]
Ok so you say that changing this does not affect the totals cash, but does affect the receipt?

**Comment by chunter2** [comment]
@jekkos Correct, I just tried a 'new' sale with HALF FIVE enabled and when I switch back to the default the receipt changes as well. 

The following screenshot is an old sale created with the default rounding setting.   
![regular sale](https://user-images.githubusercontent.com/531129/115782765-0d5dd680-a38a-11eb-8bc6-713b52469dda.png)

The following screenshot is the same old sale with the HALF-FIVE rounding setting enabled.  
![regular sale with half-five](https://user-images.githubusercontent.com/531129/115782769-0df66d00-a38a-11eb-9b9e-9f42e96d2852.png)

The following screenshot is a new sale created with the HALF-FIVE rounding setting.  
![half-five sale](https://user-images.githubusercontent.com/531129/115782772-0e8f0380-a38a-11eb-87b7-06b41c712a1f.png)

The following screenshot is the same new sale with the rounding setting set back to the default.  
![half-five sale back to default](https://user-images.githubusercontent.com/531129/115782771-0df66d00-a38a-11eb-86e3-f9b8726ba8d5.png)
