### ISSUE TITLE
travic-ci.org shutting down

### ISSUE THREAD

**Issue by daN4cat** [opensourcepos/opensourcepos#3063]
Just read this message:

```
Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information.
```

**Comment by jekkos** [comment]
The build seems to fail occasionally with the following error

```
bower not-cached    https://github.com/101arrowz/fflate.git#^0.4.8

bower resolve       https://github.com/101arrowz/fflate.git#^0.4.8

bower resolved      https://github.com/thomaspark/bootswatch.git#3.4.1+1

bower ENORESTARGET  No tag found that was able to satisfy ^0.4.8

```

**Comment by daN4cat** [comment]
Not sure what's that fflate about...

**Comment by daN4cat** [comment]
However this issue is about moving out of Travis because the .org is closing down. No free meal anymore. Worth checking GitHub CI support.

**Comment by jekkos** [comment]
> Not sure what's that fflate about...

I think it's a transient dependency or something. I checked their repository and indeed that version is not tagged or downloadable.? 

It's a [dependency in jsPDF bower.json](https://github.com/MrRio/jsPDF/blob/master/bower.json)

**Comment by jekkos** [comment]
Also now master build is failing because of this
```docker: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.```

So no more free lunch

**Comment by daN4cat** [comment]
Gets complicated. I guess docker images should be cached in a container registry to reduce the risk of throttling.

**Comment by objecttothis** [comment]
@daN4cat could this get punted to 3.4.0 so that once other bugs are fixed, this can go in the minor release?  As is, I have several PR's waiting for 3.3.4 to be released so that we can merge them into the master.  It's OK if this change must go into 3.3.4, but it doesn't seem to be so much a bug and 3.3.4 is supposed to be a bugfix release.

**Comment by jekkos** [comment]
@objecttothis sure this one is not urgent, let's fix the travis-ci once it breaks. I moved it to 3.4. I'd like to get the cash rounding thing in. Maybe someone needs to go ahead and try to finish @SteveIreland pull request.
I think after we can basically go ahead and merge your work rather fast.

**Comment by objecttothis** [comment]
> @objecttothis sure this one is not urgent, let's fix the travis-ci once it breaks. I moved it to 3.4. I'd like to get the cash rounding thing in. Maybe someone needs to go ahead and try to finish @SteveIreland pull request.

I did a code review of his PR and I can make those changes, but I don't know what bugs are left to fix.  Do you know?

> I think after we can basically go ahead and merge your work rather fast.
Yeah... but like you mentioned earlier, it will be important to rebase again before doing that.  3.3.3 and 3.3.4 have had changes that will be important to reconcile between the two.

**Comment by jekkos** [comment]
No I'm not sure on what works and what not.. I guess it can only be known by testing the tickets that were linked to it.

**Comment by objecttothis** [comment]
> 
> 
> No I'm not sure on what works and what not.. I guess it can only be known by testing the tickets that were linked to it.

OK, I'll work on them on Tuesday when I am working on this project again.

**Comment by objecttothis** [comment]
@jekkos if there is anything else holding 3.3.4 up besides that PR, do you think you could take a look?

**Comment by jekkos** [comment]
this is the [issue list for 3.3.4](https://github.com/opensourcepos/opensourcepos/milestone/21). We only planned to have the cash rounding fixes in there. I hope @SteveIreland but suspect he might have some other things that came in between.

**Comment by daN4cat** [comment]
Hmmm @steveireland hasn't been active in the last 3 weeks. Hope he's fine.

**Comment by objecttothis** [comment]
> Hmmm @SteveIreland hasn't been active in the last 3 weeks. Hope he's fine.

Me too.

**Comment by SteveIreland** [comment]
Fighting against all odds, I'm still alive and kicking.  :-)  

Sorry for the hiatus - it was work related.  I made the mistake of taking a few days vacation and somehow ended up a month behind on work.  And in the middle of that, my work laptop started melting down so I had to deal with a replacement and the resulting migration issues.  But I'm caught up now.

I was hoping that someone would be able to spend some quality time on the PR, but I think it's far enough off the beaten trail that no one is going to look at it until it's merged. 

I don't know if I need to but I'll make sure that it is current with the latest commits and maybe we can merge it?

**Comment by objecttothis** [comment]
> Fighting against all odds, I'm still alive and kicking. :-)
> 
> Sorry for the hiatus - it was work related. I made the mistake of taking a few days vacation and somehow ended up a month behind on work. And in the middle of that, my work laptop started melting down so I had to deal with a replacement and the resulting migration issues. But I'm caught up now.
> 
> I was hoping that someone would be able to spend some quality time on the PR, but I think it's far enough off the beaten trail that no one is going to look at it until it's merged.
> 
> I don't know if I need to but I'll make sure that it is current with the latest commits and maybe we can merge it?

@SteveIreland I'm really glad to hear that you are OK. In the future if you're able to, please let everyone know that you will be out so that we don't waste time wondering if you're going to be able to finish a PR that others are waiting on. 

If you're able, please make the changes that I talked about in my code review of #3026 and then test that PR against the issues list for 3.3.4 so that we know what isn't working and what hugs still remain.

Then if you're stuck or don't have time to finish the PR I can help or take over.  Can you tell me if you'll be able to work on it or if you need to pass it on?

**Comment by SteveIreland** [comment]
@objecttothis  Wow.   After weeks of hoping someone would be interested in it, all of the sudden "others are waiting" on this.  

There are  a few things that bother me about your comments.  But after cooling off I'll just say that  I volunteer to support this project at no charge to anyone and I get no benefit out of it other than the fact that I simply enjoy coding.  I am a little surprised that you are annoyed by my rate of progress  (honestly I thought I was finished until you recently added your flavor of coding style requests).

Since I don't need the grief, I think I'll step aside and let you have at it.  Good luck testing "that PR against the issues list for 3.3.4".  I'm sorry I don't have the time to commit that you demand.

**Comment by objecttothis** [comment]
> @objecttothis Wow. After weeks of hoping someone would be interested in it, all of the sudden "others are waiting" on this.
> 
> There are a few things that bother me about your comments.

@steveireland. I'm sorry I've offended you. That was never my intent. I'm not sure how to respond, but I will say that I wish that we had a better medium to communicate because tone and meaning often get lost in text communication. That said, please accept my apologies.


> But after cooling off I'll just say that I volunteer to support this project at no charge to anyone and I get no benefit out of it other than the fact that I simply enjoy coding. 

I can relate with you.  I don't draw a salary from code contributions to this project, so I get annoyed when others are ungrateful over my work, or expect more than I can or want to give.  Again, this wasn't my intent, but I can see how you go there.


> I am a little surprised that you are annoyed by my rate of progress (honestly I thought I was finished until you recently added your flavor of coding style requests).


After 3.3.0 release we began the standard round of big fix releases. I have 3 pull requests backed up waiting to be merged for 3.4 but can't be and have been waiting since 3.3.2 in September.  Your work was not the only thing going into these Pull Requests, so please do not hear annoyance with you over that.  It just is.


> Since I don't need the grief, I think I'll step aside and let you have at it. Good luck testing "that PR against the issues list for 3.3.4". I'm sorry I don't have the time to commit that you demand.

Given that people get busy and things happen, I do understand that people are not always immediately available to finish a PR or do a commit.  What I did intend to communicate to you with my message was the request to let the other contributors know if you knew you wouldn't get to it for a bit, so that if the PR was a dependency for something else, that they could finish it. #3026 was opened November 22nd which more than 2 months.  We did talk about doing this in the org thread. 

Had you said "hey guys, taking some time off.  I intend to get to it in a week, but may be longer" I would have asked you if I could take it over then and finish it off so that I would be able to merge these other PR.

So, here we are.  Your contribution is valuable, and I hope that we can get this sorted out.  Volunteering together, like working together, is not easy with strife, so I hope you can accept my apology here.

**Comment by daN4cat** [comment]
Guys, we all know we can dedicate the little free time available now and then. There is no reason for bad feelings.
We stood to bigger challenges and criticism in the past, it would be a pity to go opposite directions for a little misunderstanding.

Thank you both for the good work and contributions, you made a massive positive impact on the project adding a lot of valuable piece of functionality.
There is still more we can do.

**Comment by SteveIreland** [comment]
Okay, my bad.  Having been a victim of many misinterpreted text messages myself I apologize for the over-reaction.  I'll start finishing up the pull request tonight.  I'll blame Covid and the local insurrection for my increased level of stress.  :-)

**Comment by objecttothis** [comment]
> 
> 
> Okay, my bad. Having been a victim of many misinterpreted text messages myself I apologize for the over-reaction. I'll start finishing up the pull request tonight. I'll blame Covid and the local insurrection for my increased level of stress. :-)

I'm glad we were able to clear everything up.  Let me know in the PR if you have any questions about my comments.  The comments related to formatting were based on the project best practices.  @jekkos and @daN4cat add those same ones when they review my Pull Requests, so it's not just you. The ones related to the global constants were ones that I think may have been agreed on after you began the PR.  The comments related to the === operators is more of bug prevention than style.

**Comment by daN4cat** [comment]
We are used to by code formatting comments :-)

**Comment by daN4cat** [comment]
@SteveIreland nothing about the snow?
My manager close to Philly is telling me he needs to deal with a lot of snow daily at the moment.

**Comment by SteveIreland** [comment]
I live only about 20 miles south of Philly, but I think the difference between here and there is about 4 inches.  I'm guessing that they've had a total so far of around 9-10 inches and I've only had to shovel about 5-6 inches off of the pathways here.  Some flurries still going on but I'm finally seeing sunlight.

**Comment by objecttothis** [comment]
> I live only about 20 miles south of Philly, but I think the difference between here and there is about 4 inches. I'm guessing that they've had a total so far of around 9-10 inches and I've only had to shovel about 5-6 inches off of the pathways here. Some flurries still going on but I'm finally seeing sunlight.

My in-laws, until recently, lived in Fort Washington. Next time we are in the States we should grab coffee or something.

**Comment by jekkos** [comment]
Glad to see you back @SteveIreland .I also appreciate all the work you have done for the project until now and agree, contributing should remain something voluntary.. time is precious thing.

On another note, it seems that JFrog is now also closing down the free Bintray services in May this year (have received a mail for that today). So beside replacing travis-ci we might also need to find an alternative for bintray.

**Comment by daN4cat** [comment]
There is no such thing as free meal.

**Comment by objecttothis** [comment]
https://www.theregister.com/2020/11/02/travis_ci_pricng/

Github Actions seems like it would be free for this project.

**Comment by jekkos** [comment]
I have migrated the build from travis-ci.org to travi-ci.com now. The former would be discontinued in 10 days so we should be fine until we have more time to go to github actions.

**Comment by jekkos** [comment]
Issue resolved, migration done to travis-ci.com. We're on the free plan now, so let's see whether this suffices for the repo activity. If not we can consider moving to github actions #2834

**Comment by BudsieBuds** [comment]
Don't know if you missed this, but Travis-CI.com says this:
> Free for Open Source
> 
> Free for open source. We love the Open Source Community, and to show how much we love it, upon validated request placed with our Support Team you may receive free OSS credits for your public builds.

So maybe a request should be placed with their support team?

**Comment by jekkos** [comment]
Thanks for the hint, I'll see if I can start a conversation to get these credits
