### ISSUE TITLE
Additional Reporting Discount Rounding Issues

### ISSUE THREAD

**Issue by SteveIreland** [opensourcepos/opensourcepos#3119]
As I was researching changes for credit tracking I stumbled across a couple of additional programs that needed to be modified to compute discount rounding correctly.  These changes will need to  be made to:
* Summary_payments.php:124
* Summary_taxes.php:46,47,51,52

I can just roll the corrections into the credit project which should be finished well before the end of March. However, if you are expecting to publish a release before the end of March then I can handle it as a separate commit.

**Comment by chunter2** [comment]
@SteveIreland Any chance you can post the code changes for these and I can test on my data?  I guess I missed these in my testing of the daily sales rounding issue.

**Comment by SteveIreland** [comment]
Okay,  I marked up the changes to Summary_payments and Summary_taxes and pushed it up as a branch.

If you go to the branch (https://github.com/opensourcepos/opensourcepos/tree/customer-due-tracking) and look for those two scripts then you'll seen an attempt to communicate what needs to be changed.  Please ignore everything else because everything else is work in progress.

I tested it for both internal tax and external tax to make sure it didn't break anything and didn't spot any breakage.

Good luck.

**Comment by chunter2** [comment]
@SteveIreland Thanks for the code.  I think I've got it into my system correct.  It seems like the payments due column is now correct.  I'm getting zero there now where I wasn't before.  For the taxes something doesn't seem correct.  I've copied in an example below.  It looks like the total is missing the taxes with your change but I'm not quite sure what's missing in the $sales_total variable.  

Before the change.  
13.00% | 293 | $1,043.87 | $136.03 | $1,179.58
5.00% | 53 | $144.28 | $7.27 | $151.49

After the change.  
13.00% | 293 | $1,043.85 | $136.03 | $1,043.90
5.00% | 53 | $144.28 | $7.27 | $144.28

Thanks for the help.

**Comment by SteveIreland** [comment]
I was afraid the taxes might not be correct.  Thanks for the feedback.  I'll take another shot at it as soon as I can.

**Comment by chunter2** [comment]
@SteveIreland No rush on this on my part.  :)  
Back to the payments report, I found 3 days in my data that have some inconsistencies but I'm pretty sure it's my data.  I can't seem to figure out what the issue is though.  In the example below the Transaction Amount in the Sales line is different than the Total in the page summary at the bottom.  I'm pretty sure those are supposed to be the same.  Do you know what the differences are in the calculations of those two values?  If I add up the Transaction Amount of the Cash, Credit and Debit lines plus the Refunded of the Sales line the total is the same as the Payments of the Sales line.  So it looks like the Transaction Amount of the Sales line is off by the $0.26 show in the Due column of the Sales line.  Hope that all makes sense.  

Transaction Group | Transaction Type | Transactions | Transaction Amount | Payments | Refunded | Due
-- | -- | -- | -- | -- | -- | --
Sales | POS | 117 | $2,140.80 | $2,373.34 | $232.80 | $0.26
-- | -- | -- | -- | -- | -- | --
Payments | Cash | 49 | $479.49 | $712.29 | $232.80 | $0.00
Payments | Credit Card | 28 | $623.19 | $623.19 | $0.00 | $0.00
Payments | Debit Card | 40 | $1,037.86 | $1,037.86 | $0.00 | $0.00

Subtotal: $1,905.10
Tax: $235.44
Total: $2,140.54
Wholesale: $1,915.82
Profit: -$10.72

Thanks

**Comment by SteveIreland** [comment]
I believe there may be a different SQL for totals than what's being used for the details.  Something else to check.  :-)

**Comment by jekkos** [comment]
Let's try to do the fix separately no? I think were quite near the next minor one (just one last issue in #3095)

**Comment by SteveIreland** [comment]
ok

**Comment by SteveIreland** [comment]
A pull request was submitted for this.
