### ISSUE TITLE
Due Payments for customers in ospos

### ISSUE THREAD

**Issue by TestReactNative** [opensourcepos/opensourcepos#3443]
i have customers with due payments and if those customers come back to pay the liable amount how can i give them a slit which i mean a chit paper from the system that they payed the due amount to me. for example:-
if a book price is 150 and the customer pays 100 and he has a due payment of 50. and he pays that 50 due in two days like 25 on the second day and 25 on the third day. so what i need is to give him a chit saying that he payed 25 on the second day and another 25 on the third day without making any changes to my stock quantity. so is there any way to do that. thanks in advance.

**Comment by bradl822** [comment]
I don't think what you are after is currently possible. I use invoice(s) rather then due payments. This is all setup for Accrual based accounting rather then cash based which it sounds like you're after.

I use invoice as I am able to add partial payments which I don't believe is possible with due payments. This then prints a new invoice with the total paid and total outstanding amount.

May be worth checking what's possible with due payment, since I don't use it I could be way off the mark.
