### ISSUE TITLE
report genreate not works

### ISSUE THREAD

**Issue by frog-waha** [opensourcepos/opensourcepos#3639]
OSPOS version is: 3.3.8 - [ffe492]
PHP version is: 7.4.8
Selected language is: English
 all report genreate not works at all
![Capture](https://user-images.githubusercontent.com/115638886/215471730-947f2f2c-fcd5-450c-bbf5-4fc23a83a40a.PNG)
when submit
![Capture1](https://user-images.githubusercontent.com/115638886/215471787-704a411e-546f-4158-9b7e-c7e6a790f77a.PNG)

**Comment by objecttothis** [comment]
Turn on the ospos error log and look in there as well as the php error log to see what errors it's reporting.

**Comment by frog-waha** [comment]
I made sure that the user has all permissions
![216287055-cafb0012-a072-44dc-b8a4-44c1799d5c2e](https://user-images.githubusercontent.com/115638886/216918604-d63a24e8-20e4-4418-860f-6d00cdfd0d28.png)

**Comment by frog-waha** [comment]
js error
![216286986-8d3b00c9-9f69-40f2-801c-27afef3f4291](https://user-images.githubusercontent.com/115638886/216918729-34b78333-6782-4eea-80e2-b7da15dee087.png)

**Comment by objecttothis** [comment]
You'll need to resolve the first access denied error before we can begin to troubleshoot anything with OSPOS.  Typically this is caused by a limit to the permissions in the database for the user.  Assuming you are able to login, that tells me that the user you've assigned for that database has access to at least some of the tables, but perhaps not all permissions or on all tables. I would specifically check to make sure that the user has access to create tables in that database.

**Comment by objecttothis** [comment]
Are you sure that "create temporary tables" is checked for the user logging into the ospos database in question?
![image](https://user-images.githubusercontent.com/17935339/217066437-9228089c-70a7-4f99-803c-0257053150ca.png)
