### ISSUE TITLE
CI4: Get Sales MVC working

### ISSUE THREAD

**Issue by objecttothis** [opensourcepos/opensourcepos#3698]
Right now there are various bugs and problems preventing the sales views from loading properly.

**Comment by SteveIreland** [comment]
I thought I would dive into this over the weekend and, time permitting, fix as many of the issues that I can find.  Hopefully I don't cause problems for you.  @objecttothis

**Comment by objecttothis** [comment]
> I thought I would dive into this over the weekend and, time permitting, fix as many of the issues that I can find.  Hopefully I don't cause problems for you.  @objecttothis 

No problem. Feel free to take ownership of any tickets that I am assigned. I'm still several weeks out from being able to dive back in due to this remodel.

**Comment by SteveIreland** [comment]
I made changes to the register that got me to the point where I could add, change, and remove items from the sale  I can also add and remove payments, and I can add and remove a customer.  A lot more remains to be debugged, but I'm out of time for this weekend.

One notable point.  The new CI4 method for getting config properties will fail if the property doesn't exist.  So, if for some reason the property doesn't exist, then I am creating the property and adding to the tables.sql so that the property will be added when a new database is created.  For existing databases they will need to be manually added.  Maybe this is an opportunity for a new CI3 to CI4 migration step?

I also noticed that the database was changed while I was working on this, so my test didn't include that database change.  I'll pick that up in the next iteration.

**Comment by objecttothis** [comment]
@SteveIreland tables.sql and constraints.sql is frozen, so we can't add those there. In the CI3 version of OSPOS I believe those rows were being added to ospos_app_config on first use. I may be mistaken but we may just need to check if the row exists and lazy load if not.

**Comment by objecttothis** [comment]
> Yep.  I forgot about that major annoyance.  Thanks for reminding me.

I believe thats the benefit of the save function. When working properly it does a check to see if the key exists and does an insert if no or an update if yes. The CI4 built in Model save function does this so eventually we should be able to get rid of our overridden save functions where we aren't doing something extra.

**Comment by SteveIreland** [comment]
I added a commit that will allow a simple order (item selected, customer selected, and cash amount applied for a POS sale) to be completed.
