### ISSUE TITLE
Question/( or New feature?) about "manual" SKU/PLU

### ISSUE THREAD

**Issue by conrado32g** [opensourcepos/opensourcepos#3714]
Hi folks, I'm a new user, and I like your work!
I used a PHP POS software in a hardware store for several years, and am now leaving to start a tech service in appliance repair and maintenance.

A bit of explanation first:

- In the hardware store, our POS system allowed for a "manual" alphanumeric SKU code, which was constrained to be unique on entry of a new stock item. This allowed us to use a relatively short code for a broad "key space": for example, 4-inch nails sold by weight could be sku "C004352". This way, a 7-position code allows for up to 7e10 distinct skus, far more than any hardware store that I know of uses. We reduced this key space to 6e7 by using "C000000" (a C followed by six digits), making our own sku more or less unique.
- An additional advantage of this was that we could manually write our sku on the box of nails, since it is not hard to memorize six digits. Also, the barcode on the box of nails corresponds to the bulk box, not the "sell by weight" item.

Now, the question I have is, how can I use a similar manual sku in OPOS? In my service area, I will have many parts that come without a barcode, so I cannot just scan them when creating an item in the stock module. But I don't want a 13-digit code anyhow, if I could use a shorter alpha-numeric code in stead. I could just use OPOS internal "item_id" primary key, ~~but it isn't visible in the stock table~~ (**EDIT**: Yes, it is! Sorry, I didn't see it before).
Is there an option to ~~make it visible, or perhaps~~ assign a manual alpha-numeric sku as a unique attribute to each item? (I would like to keep the barcode field reserved, for the cases where the item _does_ include a barcode.)
Cheers

**Comment by SteveIreland** [comment]
The auto-assigned item_id field is the only "unique" thing about items.   The item_code (normally the UPC code) is also checked for uniqueness but only if it's actually assigned, since it is an optional field.

Your only option, to get close to what you want to do, is to add an attribute for SKU that you can assign during item maintenance.

Any software support for insuring that it is unique, or that that it is required to be entered, would be something you'd need to add.  I'm doing some item import work today so I'll test to see if the SKU code is searchable.  We do something similar but it's been awhile since I've had to explore it in depth.

**Comment by SteveIreland** [comment]
Item Attributes are not searched by default.  On the items table you first need to select from the dropdown box the option to Search Attributes.

My test to search for an item using an attribute during sales entry was unsuccessful.  To my gut tells me it doesn't work.  However, it could be because I didn't set the attribute to be supported in Sales from the beginning and therefore the info wasn't there to be searched.  You'll need to experiment with it to see if that is an option.

However, if I were you I'd just add the SKU to the item table and make the necessary changes.   The attributes support isn't trivial and it does add a bit of overhead when searching a large database.

**Comment by conrado32g** [comment]
Steve, Thanks a lot for your effort in answering! I'm just a beginner level programmer (the PHP program that I mentioned wasn't our own), but I'll give a try at adding the SKU into the item table, and if it works well I'll report back. Cheers!
