### ISSUE TITLE
Low Sell Quantity Not working properly

### ISSUE THREAD

**Issue by isbullaml** [opensourcepos/opensourcepos#3727]
### Background information

__IMPORTANT: If you choose to ignore this issue report template, your issue will be closed as we cannot help without the requested information.__

Please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] Reporting an issue of an unmodified OSPOS installation
- [] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [] Aware the installation code that [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable.

### Installation information

- OSPOS version is: 
- OSPOS git commit hash is: 
- PHP version is: 
- MySQL or MariaDB version is: 
- OS and version is: 
- WebServer is: 
- Selected language is: 
- (If applicable) Docker installation: 
- (If applicable) Installation package for the LAMP/LEMP stack is: 

### Issue / Bug  / Question / New Feature

Please write your issue here. If a bug, please make sure to provide as much information as possible including configuration settings (e.g. Decimals set, Tax mode), language and steps to reproduce the bug.

First of all, I would like to thank all the contributors, Keep up the good work.

I have added Pepsi Carton and Pepsi Bottle Each Item.
![image](https://user-images.githubusercontent.com/35683733/227704113-b4653cc8-ac31-4c0a-af2b-1d4ffebe4c43.png)

Pepsi Carton = 5 ( 4 bottle per carton)
Quantity Per Pack  = 4
Low Sell Quantity = Pepsi | Each

![image](https://user-images.githubusercontent.com/35683733/227704249-b5ddf938-d3d3-4751-8ad7-a79c81465465.png)

Pepsi Bottle = 20
![image](https://user-images.githubusercontent.com/35683733/227704289-74ed61ee-475a-45e9-8477-4441eddfb68f.png)

I have made a sale with Pepsi 4 Bottle. Now the current quantity of Pepsi is 16 Bottles and 4 Carton, but the Pepsi carton quantity shows as 5, May I know why?

![image](https://user-images.githubusercontent.com/35683733/227704488-8c7ddc77-910e-4d8f-97b5-06683e0b0b13.png)

**Comment by ekardian** [comment]
try with kits articles

**Comment by SteveIreland** [comment]
My interpretation of your scenario is that you have two items in stock.  You started with 16 individual bottles of Pepsi in stock (probably on a shelf or in a vending machine - or both).   In addition, you also  started with 5 cartons  of Pepsi where each carton contains 4 bottles for a grand total of 20 bottles in those 5  cartons.   So in total, you started with 36 bottles of Pepsi in stock (packed two different ways).  So, you can sell by the bottle, or you can sell by the case (depending on which item is sold).

So it seems like the low sell quantity is working as designed.   If you sell 4 of "Each" then you are selling 4 bottles.  That has nothing to do with the cartons.

@ekardian suggested a different approach that might get you closer to what you want, if your goal is to maintain the inventory of Pepsi in bottles instead of cartons.  The "kit item" could be configured to deduct 4 bottle for each kit item sold.
