### ISSUE TITLE
Feature request: supporting three decimal places when handling currency

### ISSUE THREAD

**Issue by hahayusuf** [opensourcepos/opensourcepos#3757]
### New Feature

The vast majority of currencies need a maximum of two decimal places to represent a currency. However, for a small minority of currencies, three decimal places are needed. Unfortunately, the software only supports up to two.

Despite the amazing features, this makes the software unusable in those regions.

Happy to work on this. I have raised this because there is a client need.

Ref here: https://docs.adyen.com/development-resources/currency-codes

**Comment by nukerj** [comment]
@hahayusuf  Use javascript for best result .tofixed(number of decimal here);

**Comment by hahayusuf** [comment]
> @hahayusuf  Use javascript for best result .tofixed(number of decimal here);

Thanks for the suggestion! I was able to change how numbers are displayed, globally, by allowing 3 to be set in the Localization configuration. However, the database structure prevents storing more than 2 decimal places. 

Any ideas on the best approach for creating a database migration for this?

**Comment by nukerj** [comment]
This is an example for change the attribute format to more decimals

ALTER TABLE `ospos_items` CHANGE `unit_price` `unit_price` DECIMAL(15,3) NOT NULL;

**Comment by nukerj** [comment]
@hahayusuf You may be interested in this customer debt control module or sales due
Watching on you tube 

https://youtu.be/0-L9aNES2EM

**Comment by SteveIreland** [comment]
There are several database fields (beyond just unit_price) that you would want to change.

Since you didn't mention the version of OSPOS that you're on, I cannot accurately provide more info - but assuming that you are at least on version 3.3.0 and you want to upgrade to 3.3.8 then you should be safe since you aren't likely to be triggering ay migrations that revert the size of the cost/price fields back to 2 decimal places.

If you eventually upgrade to 3.4 then there might be an issue with the migration.  Maybe we should include support for 3 decimal positions in CI4?   I think the system should be able to absorb that change without any impact, but I'll let "the deciders" make that call

**Comment by hahayusuf** [comment]
Thanks for your insight @SteveIreland. I am currently on v3.3.8.

It would be fantastic if 3 decimal places can be supported officially. Since that would allow future updates with no issues.

Until then, I will have to look at the structure to figure out which fields need to be updated.
