### ISSUE TITLE
 CI4: Fresh install - saison 2

### ISSUE THREAD

**Issue by DEV-byoos** [opensourcepos/opensourcepos#3776]
good evening devs;
Well as promised I embarked on the Fresh install season 2 so
to test the latest adjustments from our friend @SteveIrland and @jekkos

Postive review ho, complete installation without error...
BUILD.md procedure

OSPOS version is: upgrade-ci4 based on OSPOS 4.0.0-dev  CI 4.3.5
OSPOS git commit hash is: b9af9df
PHP version is: php8.2
MySQL or MariaDB version is: 10.5
OS and version is: GNU/LINUX debian 11.7
WebServer is: apache 2.4
Selected language is: en-US
(If applicable) Docker installation: yes and bower
(If applicable) Installation package for the LAMP/LEMP stack is:LINUX

# Fresh install saison2 of 2023/06/13
 
 1) Error Call to a member function getResultArray() on bool search →

APPPATH/Database/Migrations/20210422000000_database_optimizations.php at line 95

 2) 
404 Controller method is not found: "summary_(.+)"
/root/reports/summary_customers/2023-06-13/2023-06-13/complete/all/0

# IN  /root/app/controllers/Sales.php
App\Models\Item_kit::is_valid_item_kit(): 
Argument #1 ($item_kit_id) must be of type int, string given, called 
in /var/www/html/ci4_opensourcepos_latest/app/Controllers/Sales.php on line 494 

FIX  line 484  (int)
$item_id_or_number_or_item_kit_or_receipt = (int)$this->request->getPost('item', FILTER_SANITIZE_FULL_SPECIAL_CHARS);

# IN  /root/app/controllers/Receivings.php
		$item_id_or_number_or_item_kit_or_receipt = (int)$this->request->getPost('item', FILTER_SANITIZE_FULL_SPECIAL_CHARS);

404 error Controller or its method is not found: \App\Controllers\# IN  /root/app/controllers/Sales.php::postAdd
# IN  /root/app/controllers/Receivings.php  replace  add   by  postAdd
#FIX	public function postAdd(): void
	{...
	
404 error Controller method is not found: "index"  IN  /root/app/controllers/Reports.php
# IN  /root/app/Helpers/report_helper.php

IN /root/app/Views/reports/date_input.php  regex no match  ([^/]+)
		window.location = [window.location, start_date, end_date, $("#input_type").val() || 0, $("#location_id").val() || 'all', $("#discount_type_id").val() || 0 ].join("/");
https://stackoverflow.com/questions/74223347/codeigniter-4-uri-routing-how-to-use-regular-expressions-in-routes-addplac

 "Regex debugger log" https://regex101.com/r/iB5dI0/1 and here
/summary_(.+)/  mach ok with summary_:any
courage bye

**Comment by objecttothis** [comment]
@owlbrudder are you still wanting to help look through @DEV-byoos 's changes and implement them?

**Comment by owlbrudder** [comment]
Good morning from the Philippines. I humbly apologise for the long absence. I won't bore you with the details, but a combination of weather, earthquakes, power blackouts and Internet outages have played havoc with my ability to communicate. I sincerely hope those headwinds are gone and I can resume normal transmission.

To answer the question, yes I am certainly very happy to pick up the threads of [@DEV-byoos ](https://github.com/DEV-byoos) 's changes, but I still have not resolved my problem with the missing subtree under public where the images directory should be found. It has never been created by the documented installation processes, unless I have missed something (entirely possible). How can I resolve this? I expect I need my entire ospos tree to match the expected model in order to avoid issues as I work through the code.

**Comment by objecttothis** [comment]
It won't be created by the build procedure.  Those folders should be part of the repo and checked out like other folders when you check out the branch.  You should be checking out ci4-branch.  Glad to have you back.

![image](https://github.com/opensourcepos/opensourcepos/assets/17935339/ef644c9e-e27e-4d03-856a-fe03d319cd1d)

**Comment by owlbrudder** [comment]
Tropical storm Jelawat is passing over us today, so there is no chance of
work. I sincerely hope to be back on the team tomorrow.

**Comment by owlbrudder** [comment]
I am back on board today, following more adventures than were faced by Bilbo Baggins. My system is on PHP 8.2 and I have a fresh copy of ci4-branch including the previously missing public/uploads subtree. I will now fire up my environment to ensure everything works, then get into working on the changes from https://github.com/DEV-byoos

**Comment by meierrom** [comment]
Why going for a shitty ci4 if you have stable ci3. No rocket science to
make ci3 work on php 8+. ;)

**Comment by objecttothis** [comment]
> Why going for a shitty ci4 if you have stable ci3. No rocket science to
> make ci3 work on php 8+. ;)

You're welcome to fork the project at 3.3.9 and use it with CI3 as much as you would like. There are numerous reasons we are migrating to CI4 and I'm not going to waste time enumerating them here. You're welcome.

**Comment by owlbrudder** [comment]
Now trying to get to grips with the very brief items listed above by [@DEV-byoos](https://github.com/DEV-byoos) , but I am not getting very far, possibly because the repo files have changed in the interim.

**Error reported on**
```APPPATH/Database/Migrations/20210422000000_database_optimizations.php at line 95```
but my copy of that file has a blank line 95.

**Error reported on**
```reports/summary_customers/2023-06-13/2023-06-13/complete/all/0```
but I don't have a file anything like that name

**Error reported on**
```App\Models\Item_kit::is_valid_item_kit():
Argument https://github.com/opensourcepos/opensourcepos/issues/1 ($item_kit_id) must be of type int, string given, called
in /var/www/html/ci4_opensourcepos_latest/app/Controllers/Sales.php on line 494```
but line 494 now appears to be line 525, as this matches his suggested patch to cast the POST data to (int):
```FIX line 484 (int)
$item_id_or_number_or_item_kit_or_receipt = (int)$this->request->getPost('item', FILTER_SANITIZE_FULL_SPECIAL_CHARS);```
I have added the cast to (int) as suggested.
The same patch applied to ```app/controllers/Receivings.php``` line 151 as he suggested.

**Error reported on**
```404 error Controller or its method is not found: \App\Controllers# IN /root/app/controllers/Sales.php::postAdd

IN /root/app/controllers/Receivings.php replace add by postAdd
#FIX public function postAdd(): void
{...```
This report is rather ambiguous, but I think it is saying the add() methods in each of the two mentioned files need to be renamed postAdd(). If this is correct, it indicates a change in behaviour of the methods used to extract data from a POST. Before I change anything here, I need to discover if there are other instances in the code base and I need to determine if other changed behaviour similar to this needs to be refactored into the code base. I will start work on that today 22 Dec 2023, but Christmas and my birthday celebrations may interfere a bit.

**Error reported on**
```404 error Controller method is not found: "index" IN /root/app/controllers/Reports.php```
My copy of that file has an index method
```public function index(): void``` on line 99.

**Error reported on**
```IN /root/app/Helpers/report_helper.php```
This heading appears above, but there does not seem to be any associated error report.

**Error reported on**
```IN /root/app/Views/reports/date_input.php regex no match ([^/]+)
window.location = [window.location, start_date, end_date,
You can't use 'macro parameter character #' in math mode
$("#input_type").val() || 0, $("#location_id").val() || 'all', $("#discount_type_id").val() || 0 ].join("/");```
I searched app/Views/reports/date_input.php for the regex  ([^/]+), without success, so I do not know what needs to be fixed.
The reference to window.location is in a piece of JavaScript and I am not clear as to why the error message says it is in math mode - can I get help on this on please? date_input.php starting at line 109 contains this script:
```<script type="text/javascript">
$(document).ready(function()
{
	<?= view('partial/daterangepicker') ?>

	$("#generate_report").click(function()
	{
		window.location = [window.location, start_date, end_date, $("#input_type").val() || 0, $("#location_id").val() || 'all', $("#discount_type_id").val() || 0 ].join("/");
	});
});
</script>```

**Comment by objecttothis** [comment]
This is why I didn't want to take on deciphering @DEV-byoos suggested changes and encouraged him to submit a pull request himself. I would change what you can figure out and then not waste time on the rest. If he wants to take the time to submit a PR then we can address them at that time.

**Comment by owlbrudder** [comment]
> I would change what you can figure out and then not waste time on the rest.

Thanks - that makes sense.

I have just realised the formatting tools are in a toolbar above the comment edit space. Doh! I will go back and edit my comment accordingly so it is more readable.

**Comment by owlbrudder** [comment]
Further to the reports by  [@DEV-byoos](https://github.com/DEV-byoos) above, I have searched the codebase and found only one instance of postAdd(), which is already in Sales.php and one instance of add() which is in Receivings.php. As I have no clear idea of why there is a suggestion to change add() to postAdd() and as Google failed to give any clues, I am not going to take any action on that part of the suggestion list.

**Comment by objecttothis** [comment]
Any function called via the view using the route will likely need to have the function name changed. This is because that is what CI4s auto router is expecting. So if it uses post then foo_bar() becomes postFooBar(). And getFooBar() if it uses get.

**Comment by owlbrudder** [comment]
Thank you. In that case I will change the function name in Receivings.php to postAdd(). That seems to be the only change needed from that item in his list.
