### ISSUE TITLE
Restrict with a permission sale delete links and buttons

### ISSUE THREAD

**Issue by daN4cat** [opensourcepos/opensourcepos#382]
To delete a sale is fiscally wise not a good idea as discussed in #370 and also leads to issues with invoice numbering as discussed in #163.

I would recommend to remove the delete button from sales form and any delete link from tabular views (e.g. Takings, Detail Sale reports).

**Comment by osworx** [comment]
Instead of deleting this whole button, I would replace it by a function to create instead a ```credit note```
because it can happen that a sale has to be 'deleted' which means in the **sence of fiscal creating a credit note referring to this particular invoice number**.

**Comment by daN4cat** [comment]
But that's another feature and valid only for who deals with invoices.
In general I don't think there is supported to generate credit notes. For instance if you return something with sale register is the credit note treated as a "negative" invoice?

**Comment by osworx** [comment]
Unfortunetaly I am involved in some big projects at the moment, otherwise I would have more time helping here.
Generally, when this (or any other) POS system is used, an Invoice has to be generated in any case (mandatory).
A few hours (or days) the customer comes back and want to return the product (he can do that always without an special reason within a defined timeframe).

Now (and mandatory from the point of fiscal rules) 2 scenarios are possible:

1. customer wants his money back: a credit note has to be created (referring to this invoice and invoicenumber) and money is given back
2. customer wants another product instead (same value or less/more): also here a credit note has to be generated (referring to the invoicenumber) and a new invoice has to be created

In both scenarios the product(s) have to be taken back to stock (otherwise your inventory will be not correct).
These are only a few rules of an ordinary bookkeeping otherwise every storeowner will have big troubles with his financial authority (I am speaking here about shops inside the European Community and not located in Timbuktu ..)

Maybe not a function for this release, but an absolutely must for stores (physical and virtual).

**Comment by daN4cat** [comment]
Forgetting about invoices that are a bit more complicated, for my wife's shop they take back the item with a return in the sales register, then add a credit voucher (it's an item) to it for the same amount as there is no return for cash back unless the item is faulty. The credit note receipt is given to the customer to be spent another time.
In case the item is faulty (UK laws change on 1st Oct 15) you do just a return and you indicate how you paid back. Print the receipt, done.

All the above is already supported by ospos with no issue outside creating a Voucher item.

What I don't think it's supported is a formal credit note with numbering that differs from invoices.
But I never properly tested this on a return case.

**Comment by osworx** [comment]
Invoices and credit notes have 2 completely different range of numbers and are not allowed to be mixed.
With the changes of the consumer rights (started June 2014) every customer inside the EU can give back the products without any reason within 14 days! 
The shopowner can extend this periode with his own TOS.
Not only when the product is defect (see Zalando for example). Maybe in the UK this is regulated otherwise (while the UK is still in the EU ...).

**Comment by jekkos** [comment]
I wouldn't just want to have the sale delete removed, as my users need it to do corrections for incorrect payments most of the time for the last completed sale. I agree that a more fiscal correct way would be making a credit note but for invoices this currently isn't foreseen.

**Comment by daN4cat** [comment]
@osworks, the online differs from the high street. Online you can return without a reason, if you physically bought from a shop you need to have a reason to expect a refund, that's only for a fault.
UK consumer act follows EU law in this case.

**Comment by daN4cat** [comment]
@jekkos I would make the delete of sales an option in config as the invoice support in general.
I've been thinking for a while about this invoice story and for my case it's better not to have it (make it optional and disable from config).

 I mark this more for 2.4.

**Comment by ais-one** [comment]
I think making it as an option in config sounds good, I do not use it myself at the moment and have hidden it from the view.

**Comment by osworx** [comment]
@daN4cat not really.
Here in Austria (and in Germany as well [for example]) even in a physical shop you can return any product in almost any shop without any reason (or you can say for example it does not fit - if you have bought shoes).
Made that experience by myself 2 weeks ago.

But anyway, I am thinking to use opensourcepos to use at some customers which have both types of store: physical and virtual.
A case therefore could be, a customer has bought a product over the virtual store.
But he brings it back by himself in the physical store (assuming the physical store is near by himself).
That case would also fit by the EU law.

So having that option when needed would be good.

**Comment by ais-one** [comment]
I had toyed with the thought of both online store using ospos as well. Also something very useful.

But rather than building an entire UI for it, would be better to create a set of APIs, and anyone can build around it without breaking rules...

**Comment by daN4cat** [comment]
@osworx don't confuse what is a goodwill of the shopkeeper with what are the consumer rights: http://www.which.co.uk/consumer-rights/problem/i-want-to-return-my-goods-what-are-my-rights

**Comment by daN4cat** [comment]
For the online shop of my wife business I have a web based on Drupal Commerce (we don't need to worry about 1Mil hits per hours... I would love to have that worry!!!).

What I have done is to keep in sync the eShop with a SQL feed reading OSPOS database.

I also fetch all the items from OSPOS and create Product Variations in Drupal every season, and of course have quantities and prices up to date (every 1h run).

**Comment by osworx** [comment]
I have to deal every day with rights since 12 years.
See also: http://www.which.co.uk/consumer-rights/regulation/consumer-contracts-regulations

**Comment by daN4cat** [comment]
Yes, shopping online as I said:

> The Consumer Contracts Regulations - which came into force on 13 June 2014 and implement the Consumer Rights Directive - give you rights when shopping online, so you’re covered if things go wrong

.

**Comment by daN4cat** [comment]
See this for the goodwill point: http://www.which.co.uk/consumer-rights/problem/i-want-to-return-my-goods-what-are-my-rights

**Comment by daN4cat** [comment]
I think it's better to restrict the delete with a permission (as it was suggested and discussed already elsewhere).

**Comment by daN4cat** [comment]
@SteveIreland and maybe this access control can be added too?

**Comment by SteveIreland** [comment]
I should be able to do that.  Securing it is a good idea.

**Comment by daN4cat** [comment]
@SteveIreland and what about this too?

**Comment by SteveIreland** [comment]
I think I've already added this feature.  I checked Employee permissions and there is an Allow Delete permission.  I'll test it today to confirm that it still works.

Sorry, but this weekend is a slow throughput for me.  I'm stuck on an island with limited bandwidth which is being sucked dry by thousands of rocket geeks.  I was so frustrated yesterday that I powered down my computer.  The rocket launched this morning so I'm hoping they will all go away sooner than later.  Yesterday I couldn't get to github, today it's slow and painful but I'm learning patience.  :wink:

**Comment by daN4cat** [comment]
Rocket?
Have you started bombing Mr Kim already? I thought Mr Donald was still in Asia, hope the rocket doesn't land in the wrong place....

yep, take it easy and enjoy your time. No rush... if this is done then let's close it, I cannot really remember what was

**Comment by SteveIreland** [comment]
I tested it.  What happens is that when an unauthorized user attempts to delete a sale then they are presented with an "Unauthorized to delete" error message.  It doesn't attempt to hide the delete button.

For my purposes this was adequate since I was in a rush to introduce this change.  So I think this is done, however, if you want it to be more elegant then we can leave this open and change this to 3.3 and hopefully I'll get to it before you close 3.3

**Comment by daN4cat** [comment]
It's fine like it is.
