### ISSUE TITLE
CI4: String interpolation fixes

### ISSUE THREAD

**Issue by jekkos** [opensourcepos/opensourcepos#3824]
Recently we did some string interpolation changes in 
* Bootstrap tables 
* Attributes

These need to be applied to all language files.

**Comment by owlbrudder** [comment]
We have previously started the conversion of interpolations in language files from the old style '%0' to the new style '{variable_name}'.


I have built and tested (in a scratch pad area on my machine) all the sed scripts required to convert our current language files to the CI4 interpolation standard. I have not yet created a branch of ci4-upgrade to cover this work until we resolve a couple of issues identified during the script building process - see below.


At time of writing, these are the statistics:


One language file (app/Language/sv/Common.php) has a curious entry I can find no references for:
"none_selected_text" => "{Inget valt}"
In the en-US version of this file, the string is:
"none_selected_text" => "[Select]"
It seems the person who last edited this string used curly braces where English uses square braces. As I understand it, the lang() function will discard the entry between curly brackets due to lack of a matching parameter. This would return an empty string in CI4. I have therefore built a script to change the sv version from curlies to squares.


36 files named Bootstrap_tables.php in every language except en-US contain entries for numbered parameters in the new style, '{0}', '{1}' and '{2}'. All these will be converted to the named parameters used in the en-US version, as the code is now sending named parameters in every case. I have written appropriate 'nix sed scripts to automate this conversion.


175 files across every language except en-US contain the old style positional parameters '%0' etc.


In every language, there are only ten strings spread over 7 files which need converting from '%0' style to '{variable_name}' style For each such string, I have written a series of 'nix sed scripts to automate the conversion.


In two R to L language files, the %2 parameter had been incorrectly entered as 2%. My scripts handle this inversion.


**More confusingly,** the %1 parameter had been entered R to L as %1 and this is how it rendered on the display, but it took me a long time to discover the parameter was being parsed (on my Linux box) as 1% and was therefore not being processed by the sed script. I have adapted that script to cope and the conversion is now working as intended, but it raises some subtle questions in my mind regarding how we parse i18n in general and parameter substitution in particular in certain languages, when text may render one way but parse the other way. I don't pretend to have answers to those questions at this time. 


The sed scripts should be submitted for review along with the converted language files, because they may be a useful tool for future use as templates if we have other conversions.

**Question**: How and where should I submit the scripts?


The following language files appear to have positional parameters entered with a space between the % and the digit: '% 1' etc.

**Question**: Can we assume these are typos and fix them now, or do we leave them for a language expert to remedy later?
app/Language/az-AZ/Giftcards.php
app/Language/bg/Sales.php
app/Language/hu-HU/Attributes.php
app/Language/sv/Attributes.php
app/Language/sv/Items.php
app/Language/sv/Taxes.php
app/Language/ta/Common.php
app/Language/ta/Login.php
app/Language/ta/Sales.php
app/Language/tr/Giftcards.php
app/Language/uk-UA/Sales.php
app/Language/uk-UA/Taxes.php


There may be other anomalies in the language files that have slipped through my net. I suggest we allow these to be captured in user bug reports, as I can't think how to check other than by eyeballing every line of every language file.

**Comment by jekkos** [comment]
> We have previously started the conversion of interpolations in language files from the old style '%0' to the new style '{variable_name}'.
> 
> I have built and tested (in a scratch pad area on my machine) all the sed scripts required to convert our current language files to the CI4 interpolation standard. I have not yet created a branch of ci4-upgrade to cover this work until we resolve a couple of issues identified during the script building process - see below.
> 
> At time of writing, these are the statistics:
> 
> One language file (app/Language/sv/Common.php) has a curious entry I can find no references for: "none_selected_text" => "{Inget valt}" In the en-US version of this file, the string is: "none_selected_text" => "[Select]" It seems the person who last edited this string used curly braces where English uses square braces. As I understand it, the lang() function will discard the entry between curly brackets due to lack of a matching parameter. This would return an empty string in CI4. I have therefore built a script to change the sv version from curlies to squares.

These kind of issues also occurred in the past, sometimes leading to a broken app once this language was selected. Perhaps weblate can be configured not to allow curly brackets, that would be the best way forward to prevent these kind of errors in the future.

> 
> 36 files named Bootstrap_tables.php in every language except en-US contain entries for numbered parameters in the new style, '{0}', '{1}' and '{2}'. All these will be converted to the named parameters used in the en-US version, as the code is now sending named parameters in every case. I have written appropriate 'nix sed scripts to automate this conversion.
> 
> 175 files across every language except en-US contain the old style positional parameters '%0' etc.
> 
> In every language, there are only ten strings spread over 7 files which need converting from '%0' style to '{variable_name}' style For each such string, I have written a series of 'nix sed scripts to automate the conversion.
> 
> In two R to L language files, the %2 parameter had been incorrectly entered as 2%. My scripts handle this inversion.
> 
> **More confusingly,** the %1 parameter had been entered R to L as %1 and this is how it rendered on the display, but it took me a long time to discover the parameter was being parsed (on my Linux box) as 1% and was therefore not being processed by the sed script. I have adapted that script to cope and the conversion is now working as intended, but it raises some subtle questions in my mind regarding how we parse i18n in general and parameter substitution in particular in certain languages, when text may render one way but parse the other way. I don't pretend to have answers to those questions at this time.

Good point, maybe this has never worked. I don't remember anyone creating a ticket for it.
> 
> The sed scripts should be submitted for review along with the converted language files, because they may be a useful tool for future use as templates if we have other conversions.
> 
> **Question**: How and where should I submit the scripts?
Mabye we can create a tools/language folder and then add some scripts there? I have recently added a convert.php script to parse current CI3 language files and print them in CI4 format. You can move it together with your newly developed ones.
> 
> The following language files appear to have positional parameters entered with a space between the % and the digit: '% 1' etc.
> 
> **Question**: Can we assume these are typos and fix them now, or do we leave them for a language expert to remedy later? app/Language/az-AZ/Giftcards.php app/Language/bg/Sales.php app/Language/hu-HU/Attributes.php app/Language/sv/Attributes.php app/Language/sv/Items.php app/Language/sv/Taxes.php app/Language/ta/Common.php app/Language/ta/Login.php app/Language/ta/Sales.php app/Language/tr/Giftcards.php app/Language/uk-UA/Sales.php app/Language/uk-UA/Taxes.php
> 
> There may be other anomalies in the language files that have slipped through my net. I suggest we allow these to be captured in user bug reports, as I can't think how to check other than by eyeballing every line of every language file.

I suppose these are errors, let's try to fix them now while we're at it. Users of the language itself can refine the translations later on.

**Comment by jekkos** [comment]
Now I found this in the [weblate documentation](https://docs.weblate.org/en/latest/user/checks.html#php-format), basically it allows to run some checks on the php format strings. It has a reference to `sprintf` in PHP.  but I don't think this is usable as CI4 deviates from this formatting.

**Comment by owlbrudder** [comment]
> > We have previously started the conversion of interpolations in language files from the old style '%0' to the new style '{variable_name}'.
> > I have built and tested (in a scratch pad area on my machine) all the sed scripts required to convert our current language files to the CI4 interpolation standard. I have not yet created a branch of ci4-upgrade to cover this work until we resolve a couple of issues identified during the script building process - see below.
> > At time of writing, these are the statistics:
> > One language file (app/Language/sv/Common.php) has a curious entry I can find no references for: "none_selected_text" => "{Inget valt}" In the en-US version of this file, the string is: "none_selected_text" => "[Select]" It seems the person who last edited this string used curly braces where English uses square braces. As I understand it, the lang() function will discard the entry between curly brackets due to lack of a matching parameter. This would return an empty string in CI4. I have therefore built a script to change the sv version from curlies to squares.
> 
> These kind of issues also occurred in the past, sometimes leading to a broken app once this language was selected. Perhaps weblate can be configured not to allow curly brackets, that would be the best way forward to prevent these kind of errors in the future.

Weblate would have to be aware of our legitimate use of curlies for our interpolation placeholders. The list of such placeholders is small enough (at present) for this to be manageable.

> 
> > 36 files named Bootstrap_tables.php in every language except en-US contain entries for numbered parameters in the new style, '{0}', '{1}' and '{2}'. All these will be converted to the named parameters used in the en-US version, as the code is now sending named parameters in every case. I have written appropriate 'nix sed scripts to automate this conversion.
> > 175 files across every language except en-US contain the old style positional parameters '%0' etc.
> > In every language, there are only ten strings spread over 7 files which need converting from '%0' style to '{variable_name}' style For each such string, I have written a series of 'nix sed scripts to automate the conversion.
> > In two R to L language files, the %2 parameter had been incorrectly entered as 2%. My scripts handle this inversion.
> > **More confusingly,** the %1 parameter had been entered R to L as %1 and this is how it rendered on the display, but it took me a long time to discover the parameter was being parsed (on my Linux box) as 1% and was therefore not being processed by the sed script. I have adapted that script to cope and the conversion is now working as intended, but it raises some subtle questions in my mind regarding how we parse i18n in general and parameter substitution in particular in certain languages, when text may render one way but parse the other way. I don't pretend to have answers to those questions at this time.
> 
> Good point, maybe this has never worked. I don't remember anyone creating a ticket for it.

Should we create a ticket now to look at the implications and work-arounds?

> 
> > The sed scripts should be submitted for review along with the converted language files, because they may be a useful tool for future use as templates if we have other conversions.
> > **Question**: How and where should I submit the scripts?
> > Mabye we can create a tools/language folder and then add some scripts there? I have recently added a convert.php script to parse current CI3 language files and print them in CI4 format. You can move it together with your newly developed ones.
> > The following language files appear to have positional parameters entered with a space between the % and the digit: '% 1' etc.
> > **Question**: Can we assume these are typos and fix them now, or do we leave them for a language expert to remedy later? app/Language/az-AZ/Giftcards.php app/Language/bg/Sales.php app/Language/hu-HU/Attributes.php app/Language/sv/Attributes.php app/Language/sv/Items.php app/Language/sv/Taxes.php app/Language/ta/Common.php app/Language/ta/Login.php app/Language/ta/Sales.php app/Language/tr/Giftcards.php app/Language/uk-UA/Sales.php app/Language/uk-UA/Taxes.php
> > There may be other anomalies in the language files that have slipped through my net. I suggest we allow these to be captured in user bug reports, as I can't think how to check other than by eyeballing every line of every language file.
> 
> I suppose these are errors, let's try to fix them now while we're at it. Users of the language itself can refine the translations later on.

It is a trivial addition to the scripts to deal with this. I will update them today.

How do I submit the scripts for review/archive withing the project?

**Comment by owlbrudder** [comment]
> Now I found this in the [weblate documentation](https://docs.weblate.org/en/latest/user/checks.html#php-format), basically it allows to run some checks on the php format strings. It has a reference to `sprintf` in PHP. but I don't think this is usable as CI4 deviates from this formatting.

If you scroll down that page a little to Vue I18n formatting you will see:

Named formatting:
There are {count} apple

This indicates that our CI4 formatting is understood in at least one context, but I have not yet briefed myself on weblate so I don't know if we can utilise this feature.

**Comment by owlbrudder** [comment]
My scripts are as finished as they will ever be I think. They are ready for review - how do I proceed? 

There are ten Linux Bash scripts altogether: nine doing the work and one controller. I have concentrated on making the scripts consistent as far as possible so they will make useful templates in future. Purists will note I have not concentrated on processing efficiency, but on legibility. This was a deliberate choice because they will be run very infrequently and shaving a few cycles off the execution time is not as important as giving the next person a fair chance of understanding them.

Out of interest, they took approximately 10 seconds to complete the job of parsing all targeted language files including gathering stats.

The process has resulted in 231 language files (including the original 8 in en-US) being amended. It will make a very big pull request - is that how we want to handle this change? I am happy to create a branch for the purpose, but did not want to dump so many files on my reviewers all at once if there is a better way.

**Comment by jekkos** [comment]
> > Now I found this in the [weblate documentation](https://docs.weblate.org/en/latest/user/checks.html#php-format), basically it allows to run some checks on the php format strings. It has a reference to `sprintf` in PHP. but I don't think this is usable as CI4 deviates from this formatting.
> 
> If you scroll down that page a little to Vue I18n formatting you will see:
> 
> Named formatting: There are {count} apple
> 
> This indicates that our CI4 formatting is understood in at least one context, but I have not yet briefed myself on weblate so I don't know if we can utilise this feature.

If we stick to basic usage of the formatting then we could also use the python checks, which has curly brackets as well. It does seem that Ci4 supports some custom formatting hints that might not be under any default weblate Check, eg, you can format numbers as follows
```
echo lang('{price, number, currency}', ['price' => 7.41], 'en-GB');
// Displays "$7.41"
```
but currently we do this from PHP itself using our own helper functions that read the application settings for the format.

**Comment by owlbrudder** [comment]
> > > Now I found this in the [weblate documentation](https://docs.weblate.org/en/latest/user/checks.html#php-format), basically it allows to run some checks on the php format strings. It has a reference to `sprintf` in PHP. but I don't think this is usable as CI4 deviates from this formatting.
> > 
> > 
> > If you scroll down that page a little to Vue I18n formatting you will see:
> > Named formatting: There are {count} apple
> > This indicates that our CI4 formatting is understood in at least one context, but I have not yet briefed myself on weblate so I don't know if we can utilise this feature.
> 
> If we stick to basic usage of the formatting then we could also use the python checks, which has curly brackets as well. It does seem that Ci4 supports some custom formatting hints that might not be under any default weblate Check, eg, you can format numbers as follows
> 
> ```
> echo lang('{price, number, currency}', ['price' => 7.41], 'en-GB');
> // Displays "$7.41"
> ```
> 
> but currently we do this from PHP itself using our own helper functions that read the application settings for the format., so probably there is no reason to bother and I will try to enable a basic curly bracket check after the updates have been done.

I noticed that when I was doing my conversion and toyed with the idea of adopting CI4 methodology, but decided it was rewriting for the sake of rewriting so left it alone. If it works, don't fix it.

**Comment by jekkos** [comment]
> There are ten Linux Bash scripts altogether: nine doing the work and one controller. I have concentrated on making the scripts consistent as far as possible so they will make useful templates in future. Purists will note I have not concentrated on processing efficiency, but on legibility. This was a deliberate choice because they will be run very infrequently and shaving a few cycles off the execution time is not as important as giving the next person a fair chance of understanding them.

Sounds very nice, thanks for the work here! 
Perhaps we can proceed with two commits in the PR, one with the scripts in the tools folder and then another one with the language files, it will make it easy to review both together but have the diffs separated.

**Comment by owlbrudder** [comment]
> > There are ten Linux Bash scripts altogether: nine doing the work and one controller. I have concentrated on making the scripts consistent as far as possible so they will make useful templates in future. Purists will note I have not concentrated on processing efficiency, but on legibility. This was a deliberate choice because they will be run very infrequently and shaving a few cycles off the execution time is not as important as giving the next person a fair chance of understanding them.
> 
> Sounds very nice, thanks for the work here! Perhaps we can proceed with two commits in the PR, one with the scripts in the tools folder and then another one with the language files, it will make it easy to review both together but have the diffs separated.

Okay, I will make two submissions as described. Can you please clarify what you mean by the tools folder? My installation does not have one and it does not appear in the branch, except for a few in the node_modules tree which are not what I am looking for ..

**Comment by jekkos** [comment]
You can create the folder in the project

**Comment by owlbrudder** [comment]
> You can create the folder in the project

Thank you. I created a branch, made the two commits and pushed up to GitHub before realising I had a problem with right to left languages. The push and commits I made need to be reversed. What is the best way to do this in order to keep the history as clean as possible?

**Comment by jekkos** [comment]
Hi you can do the following

*`git reset HEAD~2`
* Do your changes 
* commit again
* `git push -f origin`

**Comment by owlbrudder** [comment]
> Hi you can do the following on your branch
> 
> * `git reset HEAD~2` soft reset will remove last two commits and put changes in staging
> * Do your changes
> * commit again
> * `git push -f origin`

Excellent. Thank you. I have left a fairly detailed comment on our devroom on gitter and need to get the team's approval for a change of strategy to get the CI4 string interpolations to work with all languages. If my idea is accepted, I can get moving very quickly, but it involves a few more code changes than I originally expected.

**Comment by owlbrudder** [comment]
> * git reset HEAD~2

I have successfully done the git reset HEAD-2. Now I need to refresh just the language tree from ci4-update, to revert the language files in my branch to what they were before I ran my initial scripts - mine are already converted to {named} placeholders which are going to be discarded in favour of numbered {1} placeholders. Is there a simple command for this?

**Comment by jekkos** [comment]
You can use the checkout command again in this case
`git checkout ci4-upgrade app/Language` will checkout all files in that folder from the branch again

**Comment by owlbrudder** [comment]
> You can use the checkout command again in this case `git checkout ci4-upgrade app/Language` will checkout all files in that folder from the branch again

Thank you. I had arrived at that answer as well, but with my luck on this branch so far I felt it wise to check.

**Comment by jekkos** [comment]
work merged in feature branch, will close.
