### ISSUE TITLE
Remove of item pic fails

### ISSUE THREAD

**Issue by meierrom** [opensourcepos/opensourcepos#3831]
Hi folks,

I can easily add an avatar to an item. However, to remove it again always fails.

Any ideas?

Kind regards,
Roman

**Comment by nukerj** [comment]
Can you upload an image of the error?

**Comment by meierrom** [comment]
Hi,

I coudn't find any error message.

However, you can easily reproduce it on the live demo on
https://demo.opensourcepos.org using username admin and password
pointofsale. Go to "Items" and click "Update Item" for an item having
an avatar and try to remove it using the form.

Kind regards,
Roman

2023-09-25 9:05 GMT, Nuker ***@***.***>:

**Comment by meierrom** [comment]
@nukerj : Were you able to reproduce it?

**Comment by objecttothis** [comment]
I was able to reproduce it in the demo.  I'll add this to 3.4.0 as that is the next release.

**Comment by WebShells** [comment]
This was fixed already @objecttothis ? I tested and the pic was removed successfully. 
I think we should remove the file and the thumb from uploads/item_pics also ?

**Comment by objecttothis** [comment]
If you tested and it successfully works then it has been fixed already.  Adding functionality to remove the file from uploads/item_pics should be a different PR since we are just focused on getting our current functionality working in CI4.  When we do implement it though, we need to check that no other items are using the same image before removing the file.
