### ISSUE TITLE
adapting ospos codeigniter 4

### ISSUE THREAD

**Issue by andriux1990** [opensourcepos/opensourcepos#3859]
Hello, I would like to offer significant support in adapting OSPOS to CodeIgniter 4. Please let me know what the priorities are.

**Comment by jekkos** [comment]
Hi, thanks for the volunteering! You can join the conversation on gitter.im. We discuss most things in depth over there. Some of that discussion then is turned into github issues. 

We had quite some issue reports [from a developer](https://github.com/opensourcepos/opensourcepos/issues/created_by/DEV-byoos) and someone should try to decipher this and check if these are still valid issues. If yes then a patch can be done in the ci4-branch.

**Comment by andriux1990** [comment]
I've set up my account. How can I find the group where specific details are discussed regarding the completion of OSPOS in CodeIgniter 4? And how much progress has been made toward full integration with CI4?

**Comment by objecttothis** [comment]
@andriux1990 take a look at https://github.com/opensourcepos/opensourcepos/pull/3858.  It has a list of tasks that need to be worked on.  I'm not working on it today, but I usually am. I sent you an invite to join the opensourcepos/devroom on gitter.  You can download the Element messaging client (https://element.io/download), then login using your github account and set the server where your messages live to gitter.im.  You should be able to join opensourcepos at that time.  There are two rooms. Lobby and devroom.

**Comment by objecttothis** [comment]
@odiea if you feel like it, we could probably use the procedure in the wiki for getting gitter working.  It used to be straightforward, but they switched over to matrix.org so there are now several steps to getting it working.  In short, matrix.org is decoupled from the messaging client.  Most use Element (element.io) and it's also decoupled from the server, so you have to change it from the default matrix.org to gitter.im.  That said, I would recommend us switching to github discussions, but there is no longer a private space that developers can talk in that space.

**Comment by DEV-byoos** [comment]
@andriux1990

Hello from DEV-byoos Gabriel, welcome to OSPOS and I hope you can help us make ci4-ugrade stable, I think everyone's wish.
1) I worked on the line "CI4: Convert File Upload Functionality #3452" with identification of the critical errors then proposed the fix.
tell me where I can send you the code?

2) since April 2023 I have also been working with @steveIrland to stabilize the installer, work done to date.

3) To be clear, I use GITHUB as a repository for DEV-byoos and as a platform for uploading projects that interest me.
it's OSPOS which is the first project on which I work online with a weak Internet network 100-200Kbp/s (Africa) while in the US and EU on average 11Mbp/s... it's a dream.

We can use GITHUB discussions if that suits you.
Well, I'm waiting for your response because I have dozens of critical errors to suggest.
Bye Gabriel

**Comment by jekkos** [comment]
@DEV-byoos please don't post randomly in unrelated issues. If you find bugs and solutions, it's best to log separate tickets so that they can be picked up by someone that has the time to work on it. When you post in random threads, these information will probably be lost.

**Comment by jekkos** [comment]
@DEV-byoos if you have a solution for the file upload conversion you can best post it in that ticket. 

* perhaps check out the github functionality for editing source file directly. It's not ideal as you are not testing code directly. As a workaround we could try to deploy such a branch to dev.opensourcepos.org so you can show the fix there. If that is fine we can accept it.
* This will be more convenient for us as we can look at the changes directly in context. It will also save time as we don't have to insert the patches ourselves.

Thanks for your interest and let me know if this is fine for you.

**Comment by DEV-byoos** [comment]
hello, 
If I can post my fixes on the discussion thread it would be cooler now that I know how to insert source code.
