### ISSUE TITLE
CI3 version and PHP 8+ major issue.

### ISSUE THREAD

**Issue by odiea** [opensourcepos/opensourcepos#3913]
If someone could figure this issue out then CI3 would be compatible with at least PHP 8 with minor changes. 
ERROR - 2023-12-29 11:13:34 --> Severity: error --> Exception: Class Attribute already exists and doesn't extend CI_Model C:\wamp64\www\goodmaster\vendor\codeigniter\framework\system\core\Loader.php 353

**Comment by jekkos** [comment]
I see currently we are using 3.1.11 in master, while 3.1.12 claims to have improved PHP8 support. Did you upgrade the compose dependency?

**Comment by odiea** [comment]
No I did not want to rebuild my branch. Cat it just be copied into this?

**Comment by jekkos** [comment]
It would be a matter of running a composer install after bumping the minor version in the json file, should not give you too much trouble.

**Comment by jekkos** [comment]
I mean upgrading the dependency itself should be easy. After looking at the changelog there might be other things to look into. The custom SameSite cookie flag might interfere with CSRF functionality that was added in 3.1.12.

**Comment by meierrom** [comment]
> If someone could figure this issue out then CI3 would be compatible with at least PHP 8 with minor changes. ERROR - 2023-12-29 11:13:34 --> Severity: error --> Exception: Class Attribute already exists and doesn't extend CI_Model C:\wamp64\www\goodmaster\vendor\codeigniter\framework\system\core\Loader.php 353

I spent a few days testing this a few months ago.

The dirty hack here is to simply duplicate the Attribute model, e.g. Attribute2.php including renaming the class to Attribute2. Then add this "new" module to autoload.php.

Then simply point to this new model instead of the old one, e.g. 

//$definition_names = $this->Attribute->get_definitions_by_flags(Attribute::SHOW_IN_ITEMS);
$definition_names = $this->Attribute2->get_definitions_by_flags(Attribute2::SHOW_IN_ITEMS);

Please keep in mind that OSPOS uses numerous very old libraries that can't be used with php8. I'll take you through when you get there.

Kind regards,
Roman
