### ISSUE TITLE
Receipt printing issues

### ISSUE THREAD

**Issue by silut7** [opensourcepos/opensourcepos#479]
When print receipt with chrome, safari, ie...the long name of item does not
auto word break so after print, the receipt very small so can't read. 
Im using epson t82 with 58mm paper size.
Pls help, many thank.

**Comment by jekkos** [comment]
I think this is more of an enhancement request as ospos wasn't really tested with this paper size in mind. Standard width is 80mm. Shouldn't be too hard to fix (just google a bit and try to modify the `word-break` css property for this field.

**Comment by silut7** [comment]
Tried word-break property but nothing change.  Tried the 80mm paper size, seem like ok but still small. I think the PDF coverter of google chrome printing prevent some css property. Need a solution for this. Responsive design may be helpful.

**Comment by daN4cat** [comment]
Have you tried adjusting the margins in Google Chrome when it comes to print your receipt?

I fixed an issue we had adjusting margins.

**Comment by silut7** [comment]
@daN4cat I tried all opiton of chrome and printer. :(

**Comment by daN4cat** [comment]
@silut7 there is now the support for a shorter version of the receipt.
Just to go Store Config and Receipt tab and instead of default (large) select short.

That should help, if not then change in your installation in views/sales the file receipt_short.php to fit your needs.

If you find something that works fine with 80mm printer please sned the file so I can add it as a new configurable option for 80mm

**Comment by daN4cat** [comment]
Wrapping is supported in receipts. This can be closed.
