### ISSUE TITLE
Idea/Feature Request: Connect to os commerce

### ISSUE THREAD

**Issue by boelle** [opensourcepos/opensourcepos#92]
Hi

could it be possible to connect to a Oscommerce backend?

ie to get products
place orders etc etc

so basicly it would not matter where and order is entered, it would show up the same both places

**Comment by boelle** [comment]
would this not be implemented?

**Comment by dtomlins** [comment]
I wouldn't/didn't implement that way - it is an availability risk unless on the same server.
As well, taxation becomes a huge issue.  OSPOS sells in a store - single tax basis, oscommerce sells everywhere - multiple tax basis(es).
However, I do "periodically" synchronize the available quantity and inventory transactions so that ospos is the master for stock.

**Comment by daN4cat** [comment]
New tax support @steveireland implemented supports the case you mention, @dtomlins
